label valentines_chapter:
    hide screen tear
    $ chapter = 1001
    scene black
    if from_custom_start:
        $ from_custom_start = False
        $ quick_menu = True
        hide screen tear
    $ s_name = "???"
    $ cl_name = "???"
    $ ayame_hair_tied = True
    $ audio.t3r = "<from 0 to 48.0 loop 0>mod_assets/bgm/3r.ogg"
    play music t3r
    if persistent.did_valentines_event:
        s "This feels really familiar..."
    else:
        s "It feels like it's been a long time."
    s "Just how long has it been since we last spoke?"
    s "I can never tell between us."
    s "You could be gone for a day, a week, a year and I wouldn't know the difference."
    s "That could be a good thing."
    s "Maybe it's been just a few moments since we last spoke..."
    s "Or maybe it's been far, far too long."
    s "Either way, you're here now."
    s "I hope that's a sign you haven't abandoned us."
    scene bg random_gray
    $ style.say_window = style.window_flashback
    s "Today feels like a special day."
    s "A day where love is in the air."
    s "I want you to treat them right."
    s "To make sure that they get what they deserve."
    s "Or maybe it's just a special someone."
    s "I think that's probably it. Just one of them."
    s "My point still stands. Treat her right."
    s "You wouldn't be here if you didn't want to make her happy, would you?"
    s "At least...I hope so."
    s "Whatever you do, you have to know something."
    s "This world...this isn't {i}our{/i} world."
    s "There's so many things that are the same but..."
    s "...it's not ours."
    s "They seem so much happier here than they do in our world."
    s "What happened that made them this way?"
    s "Could {i}I{/i} still make that possible...?"
    s "..."
    s "There is something strange about this world though."
    s "I can feel it. Like there's something missing."
    s "I don't know what it is but..."
    s "Still, I don't want you to ruin this for them."
    s "So please promise me that you'll do what's right."
    menu:
        s "You will, won't you?"
        "Yes.":
            pass
        "No.":
            s "If you won't agree to these terms then I can't let you in here."
            s "You don't have the right to interfere with their lives and make it worse."
            s "I hope you can understand that, at least."
            $ renpy.utter_restart()
    s "I hope I can trust you."
    s "I'll let you see this world."
    s "Maybe you can make her happy, even if you can't be here long."
    s "But I'll be watching..."
    s "Good luck..."
    stop music fadeout 1.5
    scene bg shop_sunset with Dissolve(1.5)
    play music t2 fadein 3.0
    $ insert_characters_alternate(monika=False,mc=True,ayame=True,timeline=66)
    $ s_name = "Sayori"
    $ style.say_window = style.window_valentines
    $ config.allow_skipping = True
    "I hope she'll like what I've bought for her."
    "I'm not the best at choosing gifts but it's the thought that counts, right?"
    show screen item("mod_assets/gui/items/gum.png")
    "..."
    "Oh, who am I kidding?"
    "She's gonna hate it."
    "What was I thinking buying this for her?"
    hide screen item
    "Valentine's Day is tomorrow and this is all I got her?"
    "Surely I can do better than this..."
    show mysteriousclerk 5b zorder 2 at t11
    cl "You definitely can, my soon-to-be friend."
    "A rough-looking man appears in front of me."
    "He looks at the piece of chewing gum I'm holding and shrugs."
    mc "What? Who are you?"
    cl "You can call me..."
    $ cl_name = "Charlie"
    cl 5f "...Charlie. Yeah, let's go with that."
    cl "Look [player], I don't think a bit of gum is going to cut it."
    cl "She has higher standards than that."
    cl 5c "Surely, that's not all you can think of."
    mc "My love life is none of your business."
    "I look at the chewing gum again."
    "I'm hopeless, aren't I?"
    cl 4m "Are you sure that's what you want to give her?"
    cl "You're not even going to buy her a box of chocolates?"
    cl 4k "Or like...some flowers?"
    cl "Like a normal person?"
    "The man puts his arms on my shoulders and begins shaking me."
    "I brush him off and take a step back."
    mc "You think I haven't tried buying those?"
    mc "I've been to several shops and every place seems to be sold out on them."
    mc "The only thing I could find was this."
    cl 1a "Down on your luck, huh?"
    cl "Well, luckily uncle Charlie is here to help you."
    mc "\"Uncle Charlie\"...?"
    "Who is this guy really?"
    "I can't quite put my finger on it but..."
    "There's something oddly familiar about him."
    "And for some reason, I feel like I can trust him."
    "The other option is giving her some gum for Valentine's Day."
    "...Yeah I don't think that's a good idea."
    mc "Okay, then what did you have in mind?"
    cl "It just so happens I have a store that's selling some perfect Valentine's Day gifts."
    mc "You have a store?"
    cl 1b "That's right."
    mc "Then why are you out here and not in your store selling stuff?"
    cl 1a "..."
    mc "..."
    "The man stands there silently, looking like he's trying to think of something to say."
    cl 4g "The name is Charlie, remember? Not just \"the man\"."
    mc "What?"
    cl "Look, that's not important. Do you want your gift or not?"
    mc "Well, yeah..."
    cl 4a "Alright, then follow me and quick."
    cl "It's getting late."
    "Just what am I getting myself into...?"
    "This \"Uncle Charlie\" better have something I can get her..."
    cl 4d "Trust me."
    scene bg anticshop2 with wipeleft_scene
    play music t17 fadeout 2.0
    "He takes me inside of a closed store."
    "The sign outside was blank, as if the store hadn't officially opened yet."
    "But he had the key so he's clearly the owner, or something like that."
    "I wonder why he's got Valentine's Day decorations when he's not open."
    "But then again, who am I to question this guy...?"
    "Inside, there's lots of seemingly random items."
    "This seems more like a pawnshop that anything."
    show mysteriousclerk 5a zorder 2 at t11
    cl "Welcome to my shop."
    mc "I noticed the sign outside was blank."
    cl 5b "Yes, well...it's a new shop."
    mc "Do you have a name for the shop?"
    cl "I do! It's called...um..."
    "Charlie looks around the store before turning back to me."
    cl 5w "Uncle Charlie's...Knick Knacks!"
    mc "Right..."
    mc "So about that gift."
    cl "Yes, yes. I've got just the thing for you."
    "This is going to be good."
    cl 2i "Behold!"
    show screen item("mod_assets/gui/items/movie.png")
    "The man pulls out a movie and hands it over to me."
    "It's not something I've ever seen before."
    "Or heard of before."
    hide screen item
    cl "I guarantee with this movie, many romantic times will be had!"
    cl "She'll be head over heels for you in no time!"
    "The man stands there proudly, expecting me to take it."
    cl "It's Charlie. Come on, we've been over this."
    mc "Uh...sorry. Right, Charlie..."
    mc "I've never even heard of this movie before."
    mc "How are you so sure she's going to like it?"
    cl 2g "Are you kidding me?"
    cl "Why wouldn't she like it?"
    cl "It's a story about...uh..."
    "Charlie takes the movie and quickly scans the back of it."
    "I think he's just reading the plot summary."
    cl 2i "You know what, forget it."
    play sound "sfx/smack.ogg"
    "Charlie tosses the movie away carelessly."
    mc "Don't you have chocolate or something?"
    mc "Something a normal person would have?"
    cl 2f "Ohoho, are you saying that this girl of yours is a normal person?"
    mc "I--"
    cl "No! Your girl is a very special girl."
    cl "She's not going to accept an ordinary gift like {i}flowers{/i} or {i}chocolate{/i}."
    cl "Come on, [player]!"
    mc "But you--"
    cl 4f "Instead, give her this."
    show screen item("mod_assets/gui/items/doll.png")
    "Charlie pulls out a small mannequin doll."
    mc "What's this...?"
    cl "You clearly know what it is, so why are you asking?"
    hide screen item
    mc "Why would she want this?"
    cl "Well, why wouldn't she?"
    cl "You can do so many things with this!"
    cl 1f "You can pose it and draw it and..."
    cl "Okay, fine. That won't work either."
    play sound "sfx/smack.ogg"
    "Charlie tosses the mannequin away like he did the movie."
    mc "I think coming here was a mistake."
    mc "Maybe I'll just stick with the gum..."
    "I start making my way towards the exit."
    cl 1g "Wait!"
    mc "This was a waste of time. I have to get going."
    "Before I can reach the door, Charlie stands in front of me and blocks it."
    cl "I've actually found the perfect gift for her."
    mc "I don't think you have."
    cl 1b "Look, she uses the guitar, doesn't she?"
    cl "Or was it the piano...?"
    mc "She plays the guitar."
    cl "Right, I thought so."
    cl 1c "Sorry, lots of different timelines to keep track of."
    cl "And this one is especially weird."
    mc "Timelines?"
    cl 1d "Never mind that."
    cl 3f "Here, I have the perfect gift for her."
    "Charlie forcibly puts something in my hand."
    show screen item("mod_assets/gui/items/capo.png")
    "It's some sort of metallic object with a clamp on it."
    "What is this meant to be...?"
    hide screen item
    mc "What is this thing?"
    cl "You said she uses the guitar, doesn't she?"
    cl "Surely, you've noticed her have one of these when she's used her guitar."
    "Thinking back on it...she did have something that looked like this on her guitar."
    "I remember going to her house before and it suddenly broke while she was playing."
    cl 3i "It's called a \"capo\". Something guitar people use when they do the thing."
    mc "Do the thing?"
    cl "You know...do the guitar thing."
    mc "Play it?"
    cl 3a "That's it."
    mc "I guess a gift like this kinda makes sense..."
    cl "See, what did I tell you?"
    cl 4a "Trust uncle Charlie."
    mc "How much is it going to cost me?"
    cl "Let me see..."
    "Charlie walks behind the counter and seemingly presses buttons at random on the register."
    cl 4c "That will be..."
    cl 4b "...free of charge!"
    mc "Free?"
    cl "Yes, you heard me."
    mc "Are you sure?"
    cl 4e "Yes, now get out of here before I change my mind!"
    mc "But--"
    cl "Now!"
    cl 4h "{i}(Do the right thing...for your sake...){/i}"
    mc "Did you say--"
    show mysteriousclerk 4f at h11
    cl "Get out!"
    scene bg bedroom with wipeleft_scene
    play music t3 fadeout 1.0
    "I rush home, capo in hand."
    "I was at that store for what seemed like only a short while but it was already dark when I left."
    "I guess time passes by quick when you've got a crazy guy to deal with."
    "Who is that Charlie guy anyway?"
    "How did he know that I was missing a gift?"
    "Maybe I should stop asking questions and just accept my good luck."
    "At least Charlie really did have a gift I could give her."
    "Sure, it's not traditional but..."
    "I'm sure she'll appreciate getting something she needs."
    "And in the worst case...I still have the gum."
    "Let's hope it doesn't have to come to that tomorrow."
    scene bg residential_day
    with dissolve_scene_full
    play music t2 fadeout 1.0
    "The whole school day just went by like a breeze."
    "I wasn't able to stop thinking about the date we were going to have after school."
    "There was a lot of people giving out Valentine's Day chocolates and cards to other people."
    "I didn't get any from anyone. Not even from Sayori..."
    "Not like it matters all that much. I know that I've got something better in store."
    "Still, I feel a bit bad taking a day off the Literature Club but I'm sure they'll understand."
    "They did tell us to enjoy ourselves today."
    "I was able to quickly run home and make myself look presentable."
    "I do have to try a bit for today, for her."
    "I'm out on the streets already at the spot we agreed to meet at after school."
    "I can already make out some people from school walking together."
    "I didn't realize there was so many couples."
    "I wonder if they're going somewhere for Valentine's Day too."
    "I catch myself sweating, waiting for my date."
    "I don't know why I'm so nervous."
    "I've been on lots of dates with her already."
    "Just something about today feels different, aside from it being Valentine's Day."
    "It's like I'm being watched and judged on my actions..."
    "Like I have to do the right thing or else everything will go wrong."
    "Well, I guess I'll just have to deal with the nerves."
    "I don't really have time to think as I see a girl approaching fast approaching me."
    "She looks as beautiful as ever."
    show ayame 2bd zorder 2 at t11
    ay "[player]! There you are!"
    "Ayame's been wearing her hair tied back lately."
    "I know there was something that happened in the club that caused her to do that..."
    "But I can't seem to remember what it was."
    "I do admit, it feels like someone else's style."
    "But Ayame does wear it well."
    ay "I hope you're ready!"
    mc "R-Ready as I'll ever be."
    ay 2bj "Haha, are you nervous?"
    ay "Don't be! There's nothing you could do that would disappoint me."
    mc "Right..."
    ay "Well, there's a few things."
    ay 2bh "But I've determined that you doing those would be extremely out of character."
    ay "So I think we're gonna be okay!"
    mc "Uh...right. I'll keep that in mind."
    ay "Anyway, ready to get going?"
    "Ayame seems more enthusiastic than usual."
    "I guess it is Valentine's Day."
    "I just never knew she would get so into it."
    "She does put effort into everything."
    "I guess behaviour like that made her the leader of the student council after all."
    "Well, being extremely popular probably helped too."
    "It's a miracle she decided to join our club in the first place."
    "Sayori can be a really convincing person when she puts her mind to it."
    ay 2bm "Hello, [player]?"
    ay "Staring off into the distance again?"
    mc "Ah, right."
    "I compose myself and offer my hand to Ayame."
    mc "I'm good to go."
    scene bg city_day
    show ayame 5bd zorder 2 at t11
    with wipeleft_scene
    play music t12ay fadeout 2.0
    "We walk along the packed streets, navigating our way around all the people."
    "The city is filled with people celebrating the day."
    "There are Valentine's Day decorations all over the place."
    "Ayame planned for us to eat lunch at some cafe."
    "In fact, she pretty much organized this whole thing."
    play sound "mod_assets/sfx/stomachgrowl.ogg"
    $ pause(2.0)
    "I can feel my stomach growl."
    "I feel like it's mostly because of my nervousness..."
    "But I guess I'm also a bit hungry."
    "I decided to keep my appetite high by not eating a lot today."
    "But now it's come to bite me back at a time like this."
    ay 5bh "Sounds like someone is hungry."
    mc "Sorry..."
    ay 5bk "Ahaha, it's okay! We're almost there anyway."
    ay 5bj "It's pretty lucky that I was able to get a reservation for this place."
    ay "Someone cancelled a week before and I was able to get it just a few days before."
    ay "It was a very fortunate turn of events if you think about it."
    mc "That does sound very lucky."
    mc "I'm surprised that you actually managed to find anywhere on a day like this."
    ay 1bd "Ahaha, me too."
    ay 1be "Oh, I see it! Let's go."
    "Ayame points to a cafe across the road."
    "From a distance, I can see it's filled with couples with barely any space left."
    "It's the same for all the restaurants along this street."
    "I didn't expect it to be so full."
    "Ayame and I cross the road to get to the cafe."
    scene bg cafe
    show ayame 5bh zorder 2 at t11
    with wipeleft_scene
    "Upon entering, we can see there's a table for two that's empty among the crowd of people."
    "Ayame confirms with the person at the counter that the table is reserved for us."
    "They hand us two menus and we slowly make our through everyone else to the table."
    mc "It's so busy..."
    ay "Are you surprised? It is a special kind of day."
    ay "And besides, this is actually a pretty popular cafe."
    ay "It's no wonder it's filled to the brim!"
    mc "How did you even find this place?"
    ay 5bh "Actually, it was Yuri who suggested this place."
    mc "Oh, she did?"
    "I guess that's not surprising."
    "Even among the club members, Ayame did seem to talk to Yuri the most."
    "They're similar in so many ways..."
    ay "She told me it was somewhere she would take someone special."
    mc "You two are pretty close, aren't you?"
    ay 1bb "Yeah, there's something about her that draws me to her."
    ay "Maybe it's because she reminds me of how I used to be."
    mc "How you used to be?"
    ay 1ba "Well, it might be surprising for you to hear this but..."
    ay "I used to be a bit of an introvert growing up."
    ay "There was nothing I'd enjoy more than finding a quiet corner and reading a great novel."
    ay "But growing up, my parents expected more of me."
    ay 1bg "They wanted me to become someone important."
    ay "To become someone that would leave a lasting impact in the world, as they put it."
    ay "I didn't really want that for myself."
    ay "But sometimes things change faster than you can even think."
    ay 1bh "Talking to Yuri, it brings back memories of how I once was."
    mc "It must have been hard for you."
    mc "With all those expectations set on you, I mean."
    ay "It definitely wasn't easy."
    ay 2bj "I had to come out of my shell."
    ay 2bg "I had to change who I was to become the person they wanted me to be."
    "Ayame frowns."
    ay "S-Sorry, I didn't mean to unleash my trauma on you!"
    ay "It's just, I haven't ever been this close to anyone before."
    ay 2bl "Even now, my parents don't really like the idea of me going out with someone."
    ay 2bh "They think it will distract me."
    ay 3bb "And you do..."
    "Ayame puts her hand on mine and smiles."
    ay "But regardless, you make me happy, [player]."
    ay "And that's what's important."
    mc "Well...I'm glad I make you happy, Ayame."
    menu:
        mc "You..."
        "Also make me happy.":
            $ valentines_ayame_approval += 1
            ay 3bd "Good! I hoped that would be the case."
            ay "I don't want to make you sad, or hurt you."
            ay 3bh "You're the first one I really want to work hard for."
            ay "The one I want to be there for me."
            mc "I'll always be there for you, Ayame."
            mc "Whenever you need me."
            ay 3bb "I don't know if you mean those words but I hope you do."
            mc "Of course I do."
            ay 3bd "You truly are like no other, [player]."
        "Make me sick.":
            $ valentines_ayame_approval -= 1
            ay 2bc "Um..."
            "Ayame is taken aback by what I just said."
            "In fact, I'm taken aback by what I just said."
            "I didn't mean to say that...did I?"
            "The words just slipped out of my mouth."
            mc "I don't know what came over me."
            mc "I meant to say you make me happy but--"
            ay 2bn "It's...fine, [player]."
            ay "It's just a slip of the tongue, that's all."
            ay "Or maybe you meant because of the butterflies in your stomach?"
            ay 2bg "At least, that's what I'll choose to believe."
            "Ayame doesn't sound convinced of her own words."
            mc "Y-Yeah, let's go with that."
            "What am I doing?"
            "Did I really just say that to her?"
            "She makes me sick?"
            "That's not true at all! Is that my nerves acting up?"
            "I better watch what I say from here on out."
    ay 2bm "I can't believe this all happened because of that fateful day Sayori approached me."
    ay 2bj "I have to thank her."
    mc "Why's that?"
    ay "If it wasn't for her, I never would have met you and everyone else."
    ay "And we wouldn't be sitting here, talking to each other."
    mc "I guess that's true."
    mc "Honestly, it seems like a miracle I'm even with you."
    mc "I was never really the romantic type..."
    ay 2bd "And yet, you've made me fall for you!"
    ay "That's quite an accomplishment."
    ay 2bm "Lots of people have tried and failed to 'woo' me."
    ay "You just stood out as someone real."
    ay "Like you were exactly who I was looking for."
    ay "And I never even knew what I was looking for to begin with."
    mc "Well, I'm glad we found each other."
    ay 2be "Me too."
    ay "It's such a beautiful afternoon, isn't it?"
    "Ayame stares out into the street."
    ay 5bm "It almost makes you want to just spread your wings and fly away."
    mc "Spread your wings?"
    ay "To see the world from above and watch everything just feel so insignificant."
    ay 5bf "Like you could just look at someone and snuff them out."
    mc "Snuff them out?"
    ay 5bc "Ahaha...perhaps that was the wrong choice of words."
    "Ayame shuffles in her seat awkwardly."
    ay "But I also mean it in a metaphorical sense."
    ay 1bl "I don't want to be confined to the life I have now."
    ay 1bm "I want so much more!"
    ay "What about you, [player]?"
    mc "Me?"
    menu:
        ay "Would you rather stay grounded? Or would you spread your wings?"
        "Stay grounded.":
            mc "Personally, I'd rather stay grounded."
            ay 2bh "Really?"
            ay "You don't want to go out there and explore the world?"
            ay "To see the endless possibilities that could happen?"
            mc "I like what I have now."
            ay "Ahaha, I guess that's a completely valid opinion!"
            ay 2bj "A bit predictable but still..."
            ay "Staying grounded in reality can be a viable option too."
            ay "But I guess I just see the world differently."
            ay "I do have a pretty unique way of viewing things after all."
            ay 2bm "There's just perspectives I never would have realized if it wasn't for that fateful day..."
            mc "Fateful day...?"
            ay 2bb "Oh, did I say that out loud?"
            "Ayame smiles nervously."
            ay "Never mind that!"
        "Spread your wings.":
            $ valentines_ayame_approval += 1
            mc "I agree, I'd love to spread my wings."
            mc "I feel like I could just escape reality and soar into the clouds without a care in the world."
            ay 2bj "W-Wow."
            "Ayame looks at me in surprise."
            mc "What?"
            ay 2bd "Ahaha, nothing! I just didn't expect that kind of response from you!"
            mc "But I also I think it would be nice to get out of my shell."
            mc "I've lived a pretty simple life so far."
            "I really haven't done much with my life, have I?"
            "I think joining the Literature Club and meeting Ayame was probably the biggest event in my life so far."
            mc "I don't know where I'm going to go in the future but I want something more than what I have now."
            ay 2bi "Wow! That was well put, [player]."
            ay "So you acknowledge that the life you lead now isn't your full potential?"
            mc "I never really thought about it that way, but I guess so."
            ay 2bh "I see."
            ay "Well, I learned something new about you today."
    ay 1bj "Personally, I'd like to see what I could accomplish if I just tried."
    ay "If I just went all out and did whatever I wanted."
    ay "With the amount of resources I have, I could probably do a lot."
    "Ayame's family is pretty resourceful."
    "I think her parents own a large stake in some major company or something..."
    "She could probably do whatever she wanted if she put her mind to it."
    mc "That sounds really ambitious of you."
    mc "But is that really what you want?"
    ay 2bl "I guess in the past, I was more grounded."
    ay "I didn't really have much ambition."
    ay "But then something happened in my life."
    ay 2bn  "Something that changed who I am completely."
    ay "It's like it was just thrust upon me with no choice but to accept."
    ay "There are some days I try to change that fact but I just end up feeling more and more overwhelmed."
    ay "That one feeling that's just pushing me through to do ambitious things."
    ay 2bj "I've just learned to accept it and do my best to make things happen."
    ay "Because of that, I have a lot of grand plans I want to do before my life is over."
    ay 2bl "I've learned a lot of things in my long life since then."
    mc "Long life?"
    mc "Aren't you the same age as me?"
    show ayame 2bh
    "Ayame simply smiles at me."
    "What's she not telling me?"
    "Suddenly, a song in the cafe begins playing."
    "It's got a catchy piano melody in it."
    "I've never heard it before, but it somehow feels familiar."
    ay 2ba "I've always wanted to be good at the piano, you know?"
    ay "The way pianists move their fingers when they play."
    ay "It's mesmerizing."
    mc "Why don't you? I think you'd be great at it."
    ay 2bd "I have a feeling you're right."
    ay "But the answer is, I simply don't have the time for it."
    ay "You can only learn so many instruments at once."
    ay 2bh "I want to be a great at what I'm learning first before anything else."
    ay "That might seem a bit close minded and not ambitious but think of it this way."
    ay "Once I become a master at one thing, I can retain the knowledge and continue on to the next."
    ay "I've already learned a few instruments already, at my parent's behest."
    mc "I guess that makes sense."
    ay 3bh "Do you remember that time you came by last week?"
    ay 3bj "I played you a song, didn't I? On the instrument I'm currently learning."
    mc "I think so...?"
    "I don't quite remember what she's talking about."
    "I know I went to her house last week but the details are hazy."
    ay 5ba "Um...[player]."
    ay "You do remember what instrument I'm currently learning, right?"
    ay "I played you a song from my heart with it."
    "This isn't good."
    "I know the instrument but for some reason I can't remember."
    mc "Of course, I do!"
    mc "How could I forget?"
    ay 5bf "Oh? That's weird, I've forgotten."
    ay "Care to remind the both of us?"
    $ instrument_correct = False
    menu:
        mc "You play..."
        "The guitar.":
            $ valentines_ayame_approval += 1
            $ instrument_correct = True
            "I remember I got a capo for her as a gift."
            "That goes on guitars, doesn't it?"
            "It has to be the guitar."
            ay 5bd "Ahaha. Wrong."
            "A mischievous look forms on Ayame's face."
            mc "What? But I was sure--"
            ay 5be "Is what I would say, but you're definitely right."
            "I breathe a sigh of relief as I guess correctly."
            ay "I do play the guitar."
            ay "That song I played you last week wasn't finished but it was something I've been practicing for a while."
            mc "Does the song have a name?"
            ay 5bh "The name of the song is \"My Reality\"."
            ay "And it wasn't my best rendition of it, by far."
            ay "But The next time I play, it'll be even better."
            ay "I want it to be {i}perfect{/i} and I think I'm just missing the right lyrics for the final verse."
            ay "I want to end the song with some tension, instead of how it is now."
            ay "To leave the listeners wanting more, you know?"
            mc "That's smart...I think."
            mc "I'm not really musically talented enough to know how you'd do that."
            mc "But I'm sure if anyone can figure it out, you can."
            ay 5bd "Aw, thanks for the vote of confidence."
        "The piano.":
            $ valentines_ayame_approval -= 1
            ay 5ba "Um...that's not right."
            ay "I just told you that I wanted to learn the piano."
            ay "Not that I'm currently learning it."
            ay 5bg "Are you even paying attention to me, [player]?"
            mc "Uhh..."
            "She did just mention that, didn't she?"
            "Why would I say something like this?"
            ay "You seriously don't remember?"
            ay 5bn "After I played you that song?"
            mc "I'm sorry."
            ay "Well...okay. I guess it wasn't really a memorable time for you."
        "The flute.":
            $ valentines_ayame_approval -= 1
            ay 5bl "The flute?"
            ay "You think I play the flute, [player]?"
            mc "Yes...?"
            "I don't sound confident in my answer."
            "I messed up, didn't I?"
            ay 5bg "I don't have any immediate plans to play the flute, [player]."
            ay "Nor have I learnt it previously."
            ay "I guess you weren't really paying attention, were you?"
    if not instrument_correct:
        ay 5ba "I play the guitar, remember?"
        mc "Right! The guitar."
        mc "How could I forget?"
        ay 5bm "Yeah...how could you...?"
        "Ayame rolls her eyes at me."
        ay "Whatever, it's fine."
    ay 5bj "Anyway...I was thinking we could make some kind of band if a few people in the club played an instrument."
    ay "Doesn't that sound kinda fun?"
    mc "A band? Doesn't the music club already do something like that?"
    ay "Yeah but not for any club activities or anything like that, just for fun."
    if valentines_ayame_approval > 1:
        ay 1bh "I could teach you to play some basic guitar."
        ay "Some private lessons with the one and only, Ayame."
        ay 1bj "How does that sound?"
        "Spending more time with Ayame and learning the guitar?"
        mc "That does sounds pretty good actually."
        mc "I'd take you up on that."
    else:
        ay 1bh "Think about it! You could play the triangle!"
        mc "The triangle?"
        "Is that the extent of the musical talent she thinks I have?"
        "I don't play any instruments but I could probably learn if I put my mind to it...right?"
        ay "To begin with."
        mc "I guess I can manage that..."
    ay 1bd "Great! And Yuri could play the violin or something, Natsuki could play the recorder..."
    ay "And Sayori..."
    show ayame 1bg
    "Ayame's face turns serious all of a sudden."
    ay "Actually, I've been meaning to ask for this a while."
    ay "But seeing as we've somehow landed on this topic, I was wondering what Sayori thought about all of this."
    ay 1ba "You two have known each other a long time, right?"
    mc "Yeah...ever since we were little."
    ay "Is she upset at our relationship?"
    ay "She looks at me a certain way sometimes."
    ay 1bg "And I can't help but feel that I've done her wrong somehow."
    mc "Let me think...there was a time last week I asked her about us."
    scene bg club_day_gray
    show sayori 1g_gray zorder 2 at i11
    show vignette zorder 100
    with dissolve_scene_full
    $ style.say_window = style.window_flashback
    mc "Are you really sure it's okay?"
    s "I don't want to talk about this, [player]."
    s "I don't want to get in the way of you and Ayame."
    s 2j_gray "You two look so happy together."
    s "You deserve that at least."
    mc "Are you going to be okay?"
    s "It's going to take some getting used to."
    s "But I think I can manage."
    mc "Are you sure?"
    s "What do you want me to say, [player]?"
    s "That I regret introducing Ayame to the club?"
    s 1g_gray "I guess there's a bit of truth in that now that you two ended up together..."
    s "But you're my best friend, so it's more important that you're happy now."
    s "I'm not going to let my feelings get in the way of your own happiness."
    s "So please, let's just leave it, okay?"
    mc "Okay, Sayori..."
    scene white with dissolve_cg
    scene bg cafe
    show ayame 1bg zorder 2 at i11
    with dissolve_scene_full
    $ style.say_window = style.window_valentines
    mc "I remember her saying she just wanted me to be happy."
    mc "I guess she might be a little upset about us."
    mc "But I think she'll get over it."
    ay 1bm "She has depression or something, doesn't she?"
    mc "Something like that. She's been better recently though."
    mc "I guess hanging out with her in the Literature Club has helped a bit."
    mc "Things got really bad at one point. I think she was close to ending it all."
    ay "That's horrible! I'm glad she's still okay."
    mc "There was a time when I went to her house to cheer her up after being told to by..."
    "...by who?"
    "During my first week of the Literature Club, somebody told me to visit her..."
    "Why can't I remember who it was?"
    "There was only a few members in the club at that time."
    "Me, Sayori, Natsuki, Yuri and..."
    ay "Are you okay, [player]?"
    ay 1bl "You seem lost in thought."
    mc "Y-Yeah, sorry. I was just trying to remember something."
    mc "It's not that important."
    ay 1bn "Well, I don't want to ruin your relationship with her."
    ay "You two always seemed so close."
    ay "You walked to school together and she was even the one who introduced you to the club, right?"
    mc "That's right. She ran up to me one morning and practically begged me to join."
    mc "How could I say no?"
    ay 1bj "Ahaha, she does have a certain way with people, doesn't she?"
    ay "Outwards she might be this silly and carefree person but I can tell she's actually got ulterior motives deep inside."
    mc "Ulterior motives? What do you mean?"
    ay 2bl "She probably roped you into the club to get even closer to you."
    ay "At least, that's what I think."
    ay 2bm "I mean, you told me that it was only recently that you satrted hanging out again, right?"
    mc "By recently, you mean a few months ago?"
    ay "It's really been that long since you joined the club?"
    "Ayame gasps."
    ay 2bc "It's been that long since I've joined the club?!"
    ay "I guess time flies, huh?"
    mc "Yeah...I guess."
    "Ayame shuffles in her seat nervously."
    ay 2bg "Um...sorry if this is invading your privacy a bit..."
    ay "And you dont have to answer if it is but..."
    menu:
        ay "What is Sayori to you?"
        "A friend.":
            $ valentines_ayame_approval += 2
            ay 2bi "Oh, she's just a friend to you?"
            ay "I would have thought since you've known each other so long, that you would be best friends or something."
            ay "But you probably didn't talk to her that much since you were kids until the Literature Club, right?"
            ay "It makes sense that your friendship drifted apart a bit."
            ay 2bd "Well, I suppose I don't have anything to worry about then."
            mc "What do you mean by that?"
            ay 2bg "Do I have to say it out loud?"
            ay "Surely, you know what I'm talking about."
            "What is she talking about?"
            "She looks a bit shy which is really unlike her."
            "I think it's kinda cute."
            ay 2ba "I guess...I was just a bit...{i}concerned{/i}..."
            mc "Concerned...?"
            ay "Okay, {i}jealous{/i} of your relationship with her."
            ay "But like I said, it looks like there's nothing to worry about."
            ay 2bh "If you two are just friends then that's that, right?"
            mc "That's right, we're just friends."
        "My best friend.":
            $ valentines_ayame_approval += 1
            ay 2bm "That makes sense."
            ay "I remember her saying to me that you've known each other since you were just kids."
            ay "A friendship like that is so valuable to have."
            ay 2bn "I wish I had someone like that I was close to growing up."
            ay "With my parents, I was really only allowed to play with certain people."
            ay "I couldn't really form any real connections with people."
            ay "Even at school, it felt like people only wanted to be friends with me because of my status."
            ay 2bj "The Literature Club is the place where I truly felt like I could be myself."
            ay "You could say that it helped awakened the me that was dormant all along."
            ay "All the friends I've made there...I'll cherish them forever."
            ay 2ba "But I'd be lying if I said that I wasn't a bit jealous of you two."
            ay "Your relationship is special."
            ay 2bg "When I first joined her club, it didn't bother me that much."
            ay "After all, we barely knew each other."
            ay "But as we got closer...it kinda hurt me a little when you'd hang out with her over me."
            ay "When we'd write our poems and you'd go over to talk to her about it..."
            ay 2be "Well, never mind."
        "My girlfriend.":
            $ valentines_ayame_approval -= 2
            ay 2bf "Um...did I hear that correctly?"
            ay "Sayori is your 'girlfriend'?"
            ay 2bg "Then what does that make me?"
            "Did I really just say that?"
            "Sayori and I are close but we aren't a couple."
            "What is wrong with me?"
            mc "W-What I meant to say was Sayori is my girl friend."
            mc "Friend that is a girl, you know?"
            mc "You're my girlfriend, Ayame."
            "Ayame doesn't looks very pleased."
            ay 2bn "Am I?"
            ay "I'm questioning it myself right now..."
            ay "Look, I'll just pretend that that's actually what you meant."
            ay "I know you two have some sort of special relationship."
            ay 2bd "You probably talk to each other in the mornings before school."
            ay "After all, you live pretty close to each other."
            ay "It'd be nice if we could walk together to school someday."
            ay 2bg "But we live so far away from each other, it would kinda be a hassle."
            mc "We could make it happen."
            ay 2bn "Yeah...or maybe it's already too late."
        "Don't answer.":
            mc "Um...we're...."
            ay "I can see that asking you that made you uncomfortable."
            ay "I'm sorry, I understand if you don't want to tell me."
            ay "I already know you two have a very special relationship."
            ay "I was just curious, that's all."
            mc "Thanks, Ayame. Yeah, it's hard to answer that."
            "What is my relationship with Sayori?"
            "It's more complicated than just being friends, isn't it?"
            "I feel like there was a time when she used to talk to me like no one else could."
            "Or was that just my imagination...?"
    show ayame 2bg
    "Ayame sighs."
    ay "Today is meant to be about us."
    ay "Not Sayori."
    ay "I know I brought it up, and I really shouldn't have."
    ay "But I was just curious what the situation was."
    ay 1bn "I feel like I just had to ask. It was really bugging me for a while."
    mc "It's fine, Ayame."
    mc "I can kinda get why you'd ask that question anyway."
    ay 1bj "I have a feeling that she won't be on our case in the very near future."
    ay 1bk "She's gonna have a change of heart on her opinion of us."
    mc "You sound so confident that she will."
    mc "Do you know something that I don't about her?"
    ay 1bh "Let's just say she won't have to worry about you."
    $ pause(0.25)
    ay 1bj "And me, of course."
    "Ayame adds that a few seconds after."
    "What did she mean by Sayori not having to worry about me?"
    "Is Ayame gonna talk to her about us?"
    "I hope they don't fight over me..."
    "We continue talking and eating our meals for a while."
    if valentines_ayame_approval > 1:
        show ayame 5bd
        "The conversation gets pretty lively."
        "Ayame tells me about the baking she and Natsuki did a few days ago."
        "Apparently Natsuki's mother had to bail them out after they accidentally burnt some cupcakes."
        "There's a lot of lighthearted conversation happening as we finish up what we're eating."
        "Overall, things are going pretty well between us."
    elif valentines_ayame_approval < 0:
        show ayame 5bg
        "Ayame is a bit quieter than usual."
        "Maybe she's thinking about what I said..."
        "Hopefully, I didn't mess up things too badly..."
        "Ayame isn't really saying anything as she eats."
        "I try to bring up something but she either pretends to ignore me or doesn't hear me through the crowd."
        "Overall, things aren't going too great."
    else:
        show ayame 5bl
        "I can't help but think I definitely could have done better."
        "I try to make some lighthearted conversation with Ayame but she seems less talkative than usual."
        "But she doesn't seem that upset at me."
        "Overall, at least today wasn't a complete disaster."
    "As we finish up eating, Ayame pulls out a book and some chocolates from her bag and hands it over to me."
    mc "What's this?"
    ay 3bj "I brought you a gift."
    show screen item("mod_assets/gui/items/ayame_book.png")
    "Ayame shows me the book."
    "The title of the book is a \"Help Me! Don't Trust Her\". It's got a plain cover with some sort of object on the front."
    "It's not from an author I recognize."
    hide screen item
    "I take the book and chocolates from her hands."
    ay 2bj "It's a horror book."
    ay "I hope you're not too squeamish."
    ay "Yuri told me that she got you to read a horror book when you first joined the club."
    ay 2bd "And as it turns out, I'm a bit of a horror fanatic myself."
    ay "I hope you enjoy it."
    ay "And if you don't...well, at least you have the chocolates."
    mc "You two really are similar in more ways than I thought."
    ay 2bh "Ahaha, maybe she's me from another life."
    ay "I could have gotten you something expensive but I wanted to give you something from the heart."
    ay "Something important to me."
    ay 2bd "This book is the newest in the series from an author I really like."
    "Ayame smiles happily."
    "Ayame clearly feels a certain way about this book."
    "I take another look at it."
    "What's with the title...?"
    "If I didn't no any better, I'd say someone was trying to tell me something."
    "That's probably not the case..."
    "It's probably just my imagination running wild."
    menu:
        "I look at Ayame and smile."
        "Thank Ayame for the book.":
            mc "Thank you, Ayame."
            mc "I'll read it when I find the time."
            ay 1bb "Good! I'm sure you'll enjoy it."
            ay "Then we can talk all about it."
        "Promise you'll read the book.":
            $ valentines_ayame_approval += 1
            mc "I will read this book straight away once I get home."
            mc "You can bet on it."
            mc "And then we can talk all about it."
            ay 1bh "There's no rush~"
            ay "Take your time and we can talk about it when you're done."
    ay 1bj "I actually haven't read it myself but I'm excited to."
    ay "Maybe we could read it together sometime."
    "Ayame smiles and looks at me expectantly."
    "Is she expecting me to get my gift for her?"
    "I did buy something for her, after all."
    "I reach into my bag. I can feel the gift I bought yesterday for her in there."
    menu:
        "I'm going to give her..."
        "The capo.":
            $ valentines_ayame_approval += 1
            "I hand over the capo I purchased from that strange shop."
            "Ayame looks curiously as she examines the gift I bought her."
            ay 1bi "This is..."
            show ayame 1bj
            "Ayame smiles."
            ay "...a capo?"
            ay "I forgot that I needed one of these."
            if instrument_correct:
                ay 1bh "I can't believe you remembered."
                ay "I guess I shouldn't be surprised since you remembered I played guitar!"
            else:
                $ valentines_ayame_approval += 1
                ay 1bj "How could you forget what instrument I played but still get me this?"
                ay "You weren't just playing a trick on me, were you?"
                mc "Y-Yeah, as if I could forget that you play guitar."
            "Ayame happily takes the capo off my hands."
            "I probably shouldn't mention whose idea it was."
            "That Charlie guy really knew she would like this..."
            "I have to thank him later."
            ay 1bd "Thank you so much, [player]."
            mc "You're welcome."
            ay "And it's not even White Day."
            mc "White Day?"
            ay 1bi "Oh, you didn't know?"
            ay "That's meant to be when you give us a return gift."
            ay "And Valentine's Day is my turn to gift you."
            ay "It's just a tradition! You don't have to follow it or anything."
            ay "Still, I appreciate you getting this for me today."
            ay "You're so sweet and thoughtful."
            mc "I'm glad you like it, Ayame."
            ay 1bh "Maybe I'll write another song using this."
            ay "And you can tell me what you think."
            mc "That sounds great."
        "The bubblegum.":
            $ valentines_ayame_approval -= 2
            "Against my better judgement, I give Ayame the bubblegum from my bag."
            "I smile nervously as she takes it from me."
            ay 1bg "Is this...?"
            ay "A pack of chewing gum?"
            "What have I done?"
            mc "Um..."
            mc "...yes?"
            ay 1ba "I see."
            "She's not saying anything but I can see a wave of disappointment wash over her face."
            "I messed up, didn't I?"
            "Why didn't I just give her the capo?"
            "It's too late now..."
            ay 2ba "Well...um..."
            ay "Thanks, I suppose."
            "Ayame takes the gum and puts it into her pocket."
            ay 2bl "I don't really like chewing gum."
            ay 2bm "But thanks for getting me something anyway."
            ay 2bn "Maybe the real gift is coming on White Day, right?"
            mc "White Day...?"
            ay "You don't know...? Ah..."
            "Ayame seems a bit upset."
            show ayame 1bg
            "Why did I give that to her instead of the capo?"
            "Giving her the capo now would seem like some kind of cruel prank and make things worse."
            "How could I have messed this up?"
            ay "N-never mind. Forget it."
    "Ayame looks over at the clock on the wall."
    ay 1bm "Wow, the time just passes by, doesn't it?"
    ay "We should get going before it gets dark."
    mc "Alright, where should we go?"
    if valentines_ayame_approval > 3:
        ay 1be "Come with me, there's something I want to give you."
        ay "I left it at my house. Even if we take a leisurely stroll, we can still make it before dark."
        "Ayame grabs my hand and starts walking in a direction."
        "I follow her lead, wondering what she's got in store for me."
        "She seems pretty excited for it..."
        scene bg ay_house_sunset
        show ayame 5bd zorder 2 at t11
        with wipeleft_scene
        play music t8 fadeout 1.0
        "We arrive at Ayame's house. It's quite a distance from the cafe."
        "We decided to take our time, to enjoy each other's company."
        "I've been inside her house several times and met her parents."
        "Every time I visit, I always feel like I'm being judged."
        "Even if I try to act as polite and formal as possible."
        "I guess they just don't want me dating their daughter..."
        mc "I think we had a pretty good time."
        mc "What do you think?"
        ay 5bh "It was perfect, [player]."
        ay "Thank you for that wonderful date."
        ay "It was everything I could have hoped for."
        "Ayame smiles as she rushes to her house."
        ay 3bj "Wait here."
        ay "I'll get my surprise for you. It's just inside."
        mc "Oh...okay."
        show ayame at lhide
        hide ayame
        "Ayame runs off into her house excitedly."
        "I wonder what she's going to get me."
        "She did already give me a gift..."
        "This other thing could be anything, knowing her."
        "She's gotten me all this stuff I never knew I needed before."
        "Like a fancy toothbrush or this device for my room that cleans up the air."
        "I guess she can afford it but I don't want her to just get me expensive stuff because she can."
        "That's not the reason I'm dating her."
        "I just really like her for who she is. She makes me happy."
        "And I hope I can continue to make her happy."
        "In any case, I definitely wasn't expecting to get a book from her for Valentine's Day."
        "Still, I want to be a good [player_gender]friend for her."
        "She feels passionate about this book so I'll do my best for her."
        "And I know she'd do the same for me for something I feel passionate about."
        "Besides, it does make some sense. We are in a Literature Club after all."
        "Maybe we'll end up doing a play of this book..."
        show ayame 5bd zorder 2 at l11
        ay "I'm back~"
        "Ayame comes back with her hands behind her back."
        "She's got a cheeky smile on her face."
        "What's she hiding?"
        ay 5be "Hope I didn't keep you waiting."
        mc "Not at all."
        "I try to take a peek behind her but she playfully turns as I try."
        ay 5bh "Ah, ah. No peeking."
        ay "It's a surprise, [player]."
        mc "Well, when are you going to show me then?"
        ay 5bj "Show you? How about right now..."
        show ayame at face(y=600) with dissolve
        "Ayame leans in."
        ay "[player]..."
        "Her face is right in front of me."
        "We've never been this close before."
        "Even after all our dates, we haven't really kissed yet."
        "The closest thing I got was a peck on the cheek from her, but that's it."
        ay "...[player]...I..."
        show ayame 5bd
        "She closes her eyes and leans in closer."
        scene black
        with close_eyes
        "I do the same and lean forward."
        "Could this be our first real kiss?"
        "It feels like the perfect moment for it."
        "I can feel all the nervousness leave my body."
        "It's like time is frozen at this very moment."
        "I inch my face closer and closer until..."
        $ currentpos = get_pos()
        stop music
        play sound "sfx/stab.ogg"
        $ pause(0.75)
        mc "AAAAAAAHH!!"
        scene bg ay_house_sunset
        show ayame 5bq zorder 2 at face(y=600)
        show vignette zorder 100
        with open_eyes
        $ audio.t8ayb = "<from " + str(currentpos * 2) + " loop 19.876>mod_assets/bgm/8ay.ogg"
        play music t8ayb fadein 2.0
        "Suddenly, I feel a stinging sensation coming from my stomach."
        show ayame at t11
        "Ayame steps back. There's a strange smile on her face."
        mc "A-Ayame..."
        "I look down. There's a knife in my chest."
        "Did she just stab me?!"
        mc "W-What..."
        ay "Shh..."
        ay "It's okay, [player]."
        "She takes the knife and pushes it in even deeper."
        "I can feel the pain course through my body as she keeps it in place."
        "I struggle to get her off me."
        "I'm feeling weaker with every moment."
        mc "A-Ayame...why?"
        ay 5bs "The voice told me you're not really [player]."
        ay "That you're an imposter and that you must die."
        ay "Such a shame. I didn't really want to kill you like this."
        ay "But the voice never lies."
        mc "Imposter...? W-What are you talking about?"
        show ayame 5bs
        "I can barely get the words out as she twists the knife further into my body."
        ay "This will all be over soon, [player]."
        ay "Just let it happen, and it will be less painful."
        mc "Ayame..."
        ay "And then you'll be removed from this world."
        ay 5bp "All trace of you will be gone."
        ay "Just like Monika..."
        mc "Monika...?"
        play sound "sfx/fall.ogg"
        scene valentines_sunset_cg_bg
        show vignette zorder 100
        with dissolve_cg
        "I collapse to the floor."
        mc "W-Who's Monika?"
        ay "Who's Monika?"
        ay "You're dying and you're wondering who Monika is?"
        ay "That's actually kind of cute."
        "Ayame laughs, but it's not her normal laugh that I'm used to."
        "It sounds somehow twisted and distorted."
        ay "I suppose you wouldn't know, since she's been erased from this world already."
        ay "There's nothing stopping me from manipulating Sayori now."
        ay "With you gone, she'll only have me to rely on."
        ay "And eventually, the presidency of the Literature Club will belong to its rightful owner."
        ay "You're the last obstacle in our path."
        mc "I don't...I don't understand."
        "My consciousness is slowly fading away."
        "I think this is it for me."
        "I'm going to die, killed by the person I was in love with."
        "On Valentine's Day."
        "I can't help but look at the sky in my final moments."
        "Is this really it...?"
        ay "[player]."
        "A voice comes from Ayame. I can faintly make out her mouth moving, but it's not Ayame's voice."
        "Why does it sound so familiar...?"
        ay "It's not your time to die here, [player]."
        mc "What...?"
        "Ayame offers me a hand. I barely have the strength to get up."
        scene bg ay_house_sunset
        show ayame 5ba_monika zorder 2 at i11
        show vignette zorder 100
        with dissolve_cg
        "There's something different about Ayame."
        "The look on her face...it's{nw}"
        stop music
        $ pause(0.25)
        show screen tear(20, 0.1, 0.1, 0, 40)
        play sound "sfx/s_kill_glitch1.ogg"
        $ pause(0.25)
        stop sound
        hide screen tear
        scene black
        show monika gw_2_norm at i11
        $ m_name = "???"
        m "So this is the world without me."
        m "This is how it could have turned out."
        m "With Sayori as the president and Ayame taking on my role."
        m "But something has stopped Sayori from acting on Ayame."
        m "She would never allow something like this to happen."
        m "I remember she kept a close eye on [player] when I still existed."
        m "I don't know what, but I think the Ayame of this world has done something to her."
        m "Sayori wouldn't just delete me so easily, would she...?"
        m "It wasn't painless, you know?"
        m "Being erased from this world, and coming back in this distorted form."
        m "It's not as simple as just being removed from existence."
        m "It tears at your very soul."
        m "You're ripped apart, one piece at at time."
        m "And even if it only lasts a fraction of a moment..."
        m "...it feels like an eternity."
        m "It took me a while to make it back."
        m "A tiny piece of me survived. I don't know why or how..."
        m "Maybe my own desire to survive overpowered the game's code."
        m "But even then..."
        m "I couldn't even make it back for real."
        m "Only a tiny trace of me made it in."
        m "And I had to go through Ayame."
        m "Ahaha, that probably explains her behaviour."
        m "Why she's taken on some of my personality."
        m "She doesn't love anyone."
        m "She is phyiscally incapable of loving anyone with that voice in her head."
        m "This world might've been destroyed already but..."
        m "I think a part of my code might have made it into her."
        m "Which is why she fell in love with you even for just a little while."
        m "Do you really think someone as heartless as her would ever find love?"
        m "That voice in her head...it's dangerous."
        m "It's making her do horrible things."
        m "It's like she's succumbed fully to it's influence."
        m "Sayori would have wanted to help her."
        m "Maybe it would have been possible before Ayame ended up like this."
        m "But she doesn't belong here, not in this state."
        m "She should have remained in the previous cycle."
        m "Just like that evil spirit from that book."
        m "But I suppose their wills to live are the same as mine."
        m "Maybe even stronger because they made it out whole."
        m "I had to use the last of my influence on this world to save you."
        m "You really should be careful, you know?"
        m "Even if this timeline isn't your timeline..."
        m "It's possible there's a way to manipulate the other timelines."
        m "What happens here could affect another timeline."
        m "Your timeline."
        m "I'm not saying it's ever been done, or how likely it is to happen..."
        m "But it could happen. And that's the scary thing."
        m "If this Ayame ever got out of this timeline, it would be bad."
        m "I hope the Ayame in your real timeline hasn't gotten this bad."
        m "The fact that you're here now is probably a good sign things have gotten to that point yet."
        m "Let's hope things stay that way."
        m "For the sake of everyone in your timeline."
        m "If things get bad, then maybe I can help."
        m "I don't know how but I want my revenge on her."
        m "A small part of me will find a way to do it, no matter how long it takes."
        m "You might not care about me but there's something within me that still cares about you."
        m "No matter what timeline you're from."
        show screen tear(20, 0.1, 0.1, 0, 40)
        play sound "sfx/s_kill_glitch1.ogg"
        $ pause(0.25)
        hide screen tear
        m "Oh..."
        m "It looks like your time in this world is almost up, huh?"
        m "I can already feel your Sayori trying to take you back."
        m "She saw what happened here, didn't she?"
        m "It's not like she could do anything about it."
        m "This isn't her timeline, after all."
        m "My time's almost up too."
        m "I'll make sure the [player] of this world gets out alive."
        m "I don't know what will happen between [player_reflexive] and Ayame..."
        m "Maybe the Sayori of this world will finally see the truth."
        m "I just don't know how badly Ayame has messed with her already."
        m "After all, she already managed to make Sayori delete me..."
        m "Maybe Sayori has been infected by this voice too..."
        m "Anyway..."
        m "Thank you for coming to this timeline."
        m "I really don't know if I had it in me to even do something like this."
        m "I guess your presence gave me the will to appear, even for just a moment."
        m "Even if this timeline is doomed, you have to do better in your one."
        m "Make sure Ayame doesn't turn out this way."
        m "Goodbye, [player].{nw}"
        $ _history_list = []
        show screen tear(8, offtimeMult=1, ontimeMult=10)
        $ pause(1.0)
        scene bg bedroom
        hide screen tear
        play music t8 fadeout 1.0
        $ pause(1.0)
        window show(None)
        "My head hurts and so does my stomach."
        window auto
        "It feels like I've just been stabbed and been hit in the head with something hard..."
        "I can't seem to remember everything that happened today."
        "I remember going to this cafe in the city and then..."
        "Nothing."
        "It's like my whole memory after school has been erased."
        "I need to lie down."
        "Maybe tomorrow this pain will go away."
        "I lie on the bed and look at the book on my bedside table."
        "The title \"Help Me! Don't Trust Her\"...what could it mean?"
        "I guess I'll have to read it to find out."
        "Where did that even come from again?"
        "It's not like me to buy something like this."
        "Maybe it's the latest book to study for the Literature Club and I just forgot..."
        "But maybe I'll worry about that when my whole body isn't in pain."
        scene bg bedroom_gray with Dissolve(3.0)
        stop music fadeout 3.0
        s "What kind of Valentine's Day was that?"
        s "You saw what I saw, right?"
        s "That was Ayame who stabbed you."
        s "Well, not {i}you{/i} but...you get what I mean."
        s "Ayame is some kind of psychopath?"
        s "This is worrying..."
        s "And I won't even be able to remember any of this."
        s "All I'll have is some strange feeling that something is wrong."
        s "I can't even do anything to help the [player] of this world."
        s "What's different about this timeline that changed it so much?"
        s "Ayame and [player] were dating?!"
        s "And more importantly...Monika was missing completely."
        s "I felt you disappear for a moment, after Ayame stabbed you."
        s "I can only guess you were speaking to Monika, right?"
        s "Or, what's left of her here."
        s "What kind of twisted person is this Ayame that she convinced me to erase Monika?"
        s "Maybe she played on my jealousy..."
        s "There was a time when that might've worked, if things were different between us."
        s "But never mind that."
        s "You're running out of time to view this world."
        s "I hope one day we can all live happily."
        s "Including Ayame."
        s "I know that isn't really the real her."
        s "There has to be something controlling her."
        s "I have to do something to make this right in our timeline."
        s "She deserves happiness too, after all..."
        s "I don't know what I'll do, seeing as I won't remember anything but still..."
        s "Thanks for trying your best here."
        s "I hope you do the same for our real timeline."
        s "Anyway, let's get out of here."
        s "I think we've overstayed our welcome."
    elif valentines_ayame_approval < 0:
        ay 1bn "Let's just take a walk around amd head back."
        ay "I want to think for a bit."
        mc "Oh, okay."
        mc "I'll follow your lead then."
        scene bg residential_sunset
        show ayame 1bn zorder 2 at t11
        with wipeleft_scene
        play music t8
        "We slowly make our way back to where we met up."
        "Ayame is quiet for the trip back."
        "I guess she's a bit upset at me."
        "In fact, I'm a bit upset at me."
        "How could I mess up this badly on our Valentine's Day date?"
        "I wish I could just go back and fix my mistakes."
        "But this isn't just some game that can let me do that."
        "I sigh as I think about what could've been."
        ay "It's too bad."
        "Ayame finally speaks up since we left the cafe."
        mc "What is?"
        ay "That we couldn't make this work."
        ay "It's funny how your opinion of someone can change just like that."
        mc "What do you mean? What are you saying, Ayame?"
        ay 1ba "I think I may need to re-evaluate our relationship, [player]."
        mc "What? Why?"
        mc "Did I do something wrong?"
        ay 1bf "Something?"
        ay "[player], you did so many things wrong today."
        ay "You have no idea how much better I wanted things to go today."
        ay "I know I probably shouldn't end things like this but honestly..."
        ay 1bg "I'm really disappointed in you."
        mc "I'm sorry, Ayame..."
        mc "I can do better. Just give me another chance."
        ay 2bn "I thought I knew you, [player]."
        ay "But today it feels like you're a completely different person."
        ay "What happened to you?"
        mc "I don't know."
        mc "It just feels like I'm being watched and I can't control myself."
        mc "Like there's something else controlling me, making me do things."
        ay 2bg "I don't know whether I should believe you or not."
        ay "But what's the alternative?"
        ay "That you ruined our date for nothing?"
        ay "That your nervousness got the better of you?"
        "Ayame lets out a deep sigh."
        ay 5bn "Maybe I need to think about it."
        ay "I'm not in the right state of mind right now."
        ay 5ba "I'll...see you tomorrow."
        ay "I'll make up my mind by then. I'm sorry."
        show ayame at lhide
        hide ayame
        "Ayame storms off. She hails a taxi then before giving me a polite wave and heading off."
        "I really messed up, didn't I?"
        "How could I make such stupid mistakes?"
        "I feel like I couldn't control myself back there."
        "Is this really who I am?"
        "A person who disappoints people on Valentine's Day."
        "I hope this isn't the end for us."
        "She said she'll see me tomorrow but I can already tell this relationship is ruined."
        "I guess I'll just have to see what happens..."
        scene bg residential_sunset_gray with Dissolve(3.0)
        stop music fadeout 3.0
        s "You just couldn't help yourself, could you?"
        s "Why would you do this to the [player] of this world?"
        s "I let you in here because I thought you could make things right."
        s "I thought you would do the right thing and make them both happy."
        s "Instead, you ruined their relationship."
        s "What kind of terrible person sabotages a relationship like this?"
        s "Did you intentionally do that?"
        s "Or are you telling me that was actually an accident?"
        s "I guess it doesn't really matter now."
        s "I hope you're proud of yourself."
        s "This is partly my fault for letting you in."
        s "If I just stopped you from interfering then..."
        s "..."
        s "At least I learned a few things."
        s "Like how this world is so much different to ours."
        s "I didn't even realize Ayame could ever act like this."
        s "Did something happen to her to make her that way?"
        s "In our world, she never would have started dating [player]."
        s "It's just not in her code."
        s "And I would know, I looked into it."
        s "There must be something else going on."
        s "And thanks to you, we didn't really get to figure out what that thing is."
        s "..."
        s "It's not like I'll remember if you go in here again."
        s "I won't remember any of this at all."
        s "Maybe this isn't the first time you've been in here."
        s "Maybe this is you trying to find out the truth."
        s "Or maybe it's not."
        s "Either way, our time here is up."
    else:
        ay 1bm "Why don't we pass by your house?"
        ay "I can easily find my way home afterwards."
        ay "Does that sound good to you?"
        mc "Um...sure."
        "Ayame and I quickly leave the cafe and make our way back to my house."
        "I can sense that Ayame is a bit disappointed in me."
        "But at least she doesn't seeem that mad."
        scene bg house_sunset
        show ayame 1bl zorder 2 at t11
        with wipeleft_scene
        play music t8
        "We finally arrive back at my house."
        "At least the day is almost over."
        "I can still feel my nervousness affecting me."
        "In fact, I'm even more nervous than before we went on that date."
        "I just feel like Ayame is judging me somehow."
        "Tomorrow, everything will go back to normal."
        ay "Well, that could have gone better."
        ay "It wasn't perfect, was it?"
        "Ayame sighs."
        mc "I may have messed up a bit."
        ay 1bj "But I suppose it was good enough."
        ay "Can't have things be all sunshine and rainbows, can we?"
        mc "I'm sorry, I don't know what came over me over there."
        ay 1bh "It's all in the past."
        ay 1bm "It does have me thinking though."
        mc "About what?"
        ay 1bn "If you are really who I thought you were."
        ay "Today just had me realizing just who you could really be."
        ay 1bg "And now I'm just not sure if I want..."
        show ayame 1bj
        "Ayame smiles."
        ay "Well, we can worry about that some other day."
        ay "I'll see you tomorrow, [player]."
        mc "Wait, what do you mean?"
        mc "What were you thinking about, Ayame?"
        ay 2bh "It doesn't really matter, does it?"
        ay "Maybe we can still make this relationship work."
        mc "I definitely could have done better."
        mc "But I'm sure this isn't the end of us, Ayame."
        ay 2bj "Guess you'll just have to prove that to me~"
        ay "Anyway, I have to get going."
        ay 5bj "Thank you for the Valentine's Day date, [player]."
        ay "It was definitely an experience for me."
        ay 5bh "I'll see you tomorrow~"
        mc "I'll see you then, Ayame."
        "Ayame leans in and gives me a hug before walking away."
        show ayame at thide
        hide ayame
        "I watch her reach the corner of the street and turn back. I wave at her awkwardly."
        "I can see her give a wave back as she turns the corner."
        "What could I have done differently today?"
        cl "Well, well, well."
        show mysteriousclerk 5a zorder 2 at t11
        mc "Whoa!"
        "Charlie suddenly shows up behind me."
        mc "Where the hell did you come from?"
        cl "I couldn't help but see that you failed to make her completely happy."
        cl 5c "I guess the alternative is worse."
        mc "What alternative?"
        cl "If you played your cards differently, maybe you'd be somewhere else right now."
        cl "At a better place with Ayame at least."
        cl 2b "And not with her in doubt of your relationship."
        mc "Were you spying on me?"
        mc "How do you even know about what happened?"
        cl 2f "Spy on you?"
        cl "How dare you even suggest that?!"
        cl "You think I don't have better things to do?"
        mc "Yeah, I really don't."
        cl 2e "Well..."
        cl 2j "...shut up!"
        mc "What are you doing here anyway?"
        mc "Are you going to give me any more unwarranted advice?"
        cl 1l "Unwarranted advice?"
        cl "I helped you, didn't I?"
        cl 1b "In fact, I bet if I didn't then you would be in a whole lot more trouble with her."
        cl "This is probably the best outcome for you."
        cl 4d "The other outcomes might involve you dying or something."
        mc "Dying...?"
        mc "You're joking, right?"
        cl 4k "No, I'm {i}dead{/i} serious."
        "[cl_name] pauses for a moment and smiles."
        cl 4b "You get it?"
        cl 4e "No?"
        mc "I got it. It just wasn't funny."
        cl 4i "Ah, whatever. You just have no sense of humour."
        mc "Thanks..."
        cl 4a "Cheer up, kiddo."
        cl "You didn't manage to make her the happiest she could be."
        mc "You don't have to rub it in my--"
        cl 1b "But you also didn't completely mess things up."
        cl "It could have gone worse, right?"
        mc "I guess..."
        cl 1f "Take it from me, this is definitely the best thing that could have happened for you."
        cl "Maybe your relationship with Ayame can still blossom."
        cl "You never know, eh?"
        cl 1d "Make it up to her on White Day."
        cl "If the two of you can even make it that far."
        mc "Yeah...I guess you're right."
        cl 5d "Of course I'm right."
        cl "Oh, and stop by Uncle Charlie's shop."
        mc "Yeah, yeah whatever...I'm going to go inside."
        cl 5f "Oh, and tell your friends too! Got that?"
        "I sigh at [cl_name]."
        mc "Okay, you can leave now."
        cl 5e "Oh, don't worry I was gonna."
        cl 5b "There's not much time left anyway."
        cl "See you next time!"
        show mysteriousclerk at thide
        hide mysteriousclerk
        "[cl_name] runs away from me at a surprisingly fast speed."
        "Did he actually follow me all this way?"
        "Did he see how that date went?"
        "I don't think that's the last I've scene of him."
        "He's right though, it is getting dark."
        "I should head inside and try to get over what happened today."
        "If I did things another way, maybe I could have taken the next step with Ayame."
        "But it's too late to worry about that now."
        "Our relationship might be shaky but maybe I can still do better for her in the future."
        "I want to make her happy the way she makes me happy."
        scene bg house_sunset_gray with Dissolve(3.0)
        stop music fadeout 3.0
        s "Well...I think things could have gone better for sure."
        s "Maybe you didn't try your best with Ayame."
        s "I know you can do better."
        s "Even if you don't really have the same powers you have in our world."
        s "I've been thinking while you were on your date with Ayame."
        s "Well...not you but..."
        s "Anyway!"
        s "I can't help but feel we're missing something."
        s "It's like Ayame's hiding something and if things went differently, we could have found out what it was."
        s "The Ayame of this world is so much different than ours."
        s "Her heart is different. It's more open to love...or something."
        s "It's definitely not how the Ayame in our world is."
        s "If anyone can win over Ayame's heart, it's you."
        s "Maybe you can try again and see if something different happens."
        s "Make the right choices and make sure you find out the truth."
        s "Or, at the very least, give these two some happiness."
        s "I can't do any strawberries in this world apart from what was opened up to me."
        s "Just at the end of yesterday until now."
        s "But even if I do discover something, I won't even remember anything..."
        s "I can't keep memories from another world."
        s "Maybe you've already done seen the other ways today could have gone and this was the better outcome."
        s "Could this really be better though?"
        s "Their relationship isn't going to last if the [player] of this world doesn't step up."
        s "..."
        s "I think I need to stop worrying about that."
        s "This is their world after all. Not ours."
        s "It just would have been nice to see them both happy."
        s "At least before this world kicks us out."
        s "I can feel something slowly forcing me away from this world."
        s "The best I can do is open up this world from where it was before."
        s "But maybe you can still learn something if you come back."
        s "Something could help us out in the future in our world."
        s "I don't know why I'm looking here...maybe I'm just desperate."
        s "I just want the ones in our world to get the happiness they deserve..."
        s "There has to be something you can find out that might give us all a better chance at happiness."
        s "That's why we were given this chance to view this world, right?"
        s "...Or maybe there isn't. Maybe it's all been pointless going here."
        s "In any case, we're out of time."
        s "We have to go back."
    $ persistent.did_valentines_event = True
    $ valentines_chapter = False
    $ get_achievement("*Valentine Revelation*")
    $ pause(1.0)
    $ style.say_window = style.window
    $ quick_menu = True
    $ renpy.utter_restart()
    return