label yuri_exclusive_1:
    scene bg club_day
    with wipeleft_scene
    "I'm really curious to talk to Yuri a little bit more..."
    "But at the same time, I would feel bad for distracting her from reading."
    "I catch a glimpse of the cover of her book."
    "It looks like the same book that she lent to me..."
    "More than that, she seems to be on the first few pages."
    play music t6 fadeout 1.0
    show yuri 4a zorder 2 at t11
    y "Ah..."
    "Crap--"
    "I think she noticed me looking at her..."
    "She sneaks another glance at me, and our eyes meet for a split second."
    y 4b "..."
    "But that only makes her hide her face deeper in her book."
    mc "Sorry..."
    mc "I was just spacing out..."
    "I mutter this, sensing I made her uncomfortable."
    y 1i "Oh..."
    y "It's fine..."
    y 1a "If I was focused, then I probably wouldn't have noticed in the first place."
    y "But I'm just re-reading a bit of this, so..."
    mc "That's the book that you gave me, right?"
    y "Mhm."
    y "I wanted to re-read some of it."
    y 2q "Not for any particular reason...!"
    mc "Just curious, how come you have two copies of the same book?"
    y "Ah..."
    y "Well, when I stopped at the bookstore yesterday--"
    y 3o "Ah, that's not what I meant..."
    y "I mean--"
    y 1w "I...just happened to buy two of them."
    mc "Ah, I see."
    "There's something fairly obvious here that Yuri isn't telling me, but I decide to let it go."
    mc "I'll definitely start reading it soon!"
    y 2u "I'm glad to hear..."
    y "Once it starts to pick up, you might have a hard time putting it down."
    y 2c "It's a very engaging and relatable story."
    mc "Is that so...?"
    mc "What's it about, anyway?"
    y 1f "Well..."
    y "Mmm..."
    "Yuri closes the book and scans her eyes over the back."
    "The book is titled \"Portrait of Markov\"."
    "There's an ominous-looking eye symbol on the front cover."
    y 1a "Alright..."
    y "I just wanted to make sure I don't accidentally give anything away."
    y "Basically, it's about this girl in high school who moves in with her long-lost younger sister..."
    y "But as soon as she does so, her life gets really strange."
    y 1m "She gets targeted by these people who escaped from a human experiment prison..."
    y "And while her life is in danger, she needs to desperately choose who to trust."
    y 1i "No matter what she does, she ends up destroying most of her relationships and her life starts to fall apart..."
    mc "That's kind of--!"
    "That's kind of dark, isn't it?"
    "Yuri made it sound like it was going to be a nice story, so that dark turn came from nowhere."
    y 1c "Ahaha."
    "Yuri gently giggles, all of a sudden."
    y "Are you not a fan of that sort of thing, [player]?"
    mc "No, it's not that..."
    mc "I mean, I can definitely enjoy those kinds of stories, so don't worry."
    y 2u "I hope so..."
    "Yeah... I totally forgot that Yuri is into those things."
    "She's so shy and reclusive on the outside, but her mind seems to be completely different."
    y "It's just that those kinds of stories..."
    y 1a "They challenge you to look at life from a strange new perspective."
    y "When horrible things happen not just because someone wants to be evil..."
    y 1m "But because they have their own goals, or their own philosophy that they believe in."
    y "Then suddenly, when you thought you related to the protagonist..."
    y "They're made out to be the naive one for letting their one-sided morals interfere with the villain's plans."
    y 3v "I'm...I'm rambling, aren't I...?"
    y "Not again..."
    y 4b "I'm sorry..."
    mc "Hey, don't apologize...!"
    mc "I haven't lost interest or anything."
    y "Well..."
    y "I guess it's alright, then..."
    y 4a "But I feel like I should let you know that I have this problem..."
    y "When I let things like books and writing fill my thoughts..."
    y "I kind of forget to pay attention to other people..."
    y 3t "So I'm sorry if I end up saying something strange!"
    y "And please stop me if I start talking too much!"
    mc "That's--"
    mc "I really don't think you need to worry..."
    mc "That just means you're passionate about reading."
    mc "The least I can do is listen."
    mc "It's a literature club, after all..."
    y 4a "Ah--"
    y "That's..."
    y "Well, that's true..."
    mc "In fact..."
    mc "I might as well get started reading it, right?"
    y 3n "Y-You don't have to!"
    mc "Ahaha, what are you saying?"
    mc "Just a moment ago, you said you were looking forward to it."
    y 3o "..."
    mc "Let me just get the book..."
    "I quickly retrieve the book that I had put into my bag."
    mc "Alright...it's fine if I sit here, right?"
    "I slip into the seat next to Yuri's."
    y 3n "Ah...!"
    y "Yeah..."
    mc "Are you sure?"
    mc "You seem a little apprehensive..."
    y "That's..."
    y 4b "I'm sorry..."
    y "It's not that I don't want you to!"
    y "It's just something I'm not very used to..."
    y "That is, reading in company with someone."
    mc "I see..."
    mc "Well, just tell me if I end up distracting you or anything."
    y "A-Alright..."
    show yuri zorder 1 at thide
    hide yuri
    "I open the book and start the prologue."
    "I soon understand what Yuri means about reading in company."
    "It's as if I can feel her presence over my shoulder as I read."
    "It's not a particularly bad thing."
    "Maybe a little distracting, but the feeling is somewhat comforting."
    "Yuri is in the corner of my eye."
    "I realize that she's not actually looking at her own book."
    "I glance over."
    "It looks like she's reading from my book instead--"
    show yuri 3n zorder 2 at t11
    y "S-Sorry!"
    y "I was just--!"
    mc "Yuri, you really apologize a lot, don't you?"
    y "I...I do?"
    y 4a "I don't really mean to..."
    y "Sorry..."
    y 4c "I mean--!"
    mc "Ahaha."
    mc "Here, this should work, right?"
    "I slide my desk until it's up against Yuri's, then hold my book more between the two of them."
    y 2v "Ah..."
    y "I suppose so..."
    "Yuri timidly closes her own copy."
    "Once we each lean in a little bit, our shoulders are almost touching."
    "It feels like my left arm is in the way, so instead I use my right hand to hold the book open."
    mc "Ah, I guess that makes it kind of difficult to turn the page..."
    y "Here..."
    $ persistent.clear[2] = True
    $ renpy.save_persistent()
    scene y_cg1_base with dissolve_cg
    "Yuri takes her left arm and holds the left side of the book between her thumb and forefinger."
    mc "Ah..."
    "I do the same with my right arm, on the right side of the book."
    "That way, I turn a page, and Yuri slides it under her thumb after it flips to her side."
    "But in holding it like this..."
    "We're huddled even closer together than before."
    "It's actually kind of distracting me...!"
    "It's as if I can feel the warmth of Yuri's face, and she's in the corner of my vision..."
    show y_cg1_exp1 at cgfade
    y "...Are you ready?"
    mc "Eh?"
    y "To turn the page..."
    mc "Ah...sorry!"
    mc "I think I got a bit distracted for a second..."
    "I glance over at Yuri's face again, and our eyes meet."
    "I don't know how I'll be able to keep up with her..."
    y "Ah..."
    show y_cg1_exp2 at cgfade
    y "That's okay."
    y "You're not as used to reading, right?"
    y "I don't mind being patient if it takes you a bit longer..."
    y "It's probably the least I can do..."
    y "Since you've been so patient with me..."
    mc "Y-Yeah..."
    mc "Thanks."
    hide y_cg1_exp1
    hide y_cg1_exp2
    "We continue reading."
    "Yuri no longer asks me if I'm ready to turn the page."
    "Instead, I just assume that she finishes the page before me, so I turn it by my own volition."
    "We continue the first chapter in silence."
    "Even so, turning each page almost feels like an intimate exchange..."
    "My thumb gently letting go of the page, letting it flutter over to her side as she catches it under her own thumb."
    mc "Hey, Yuri..."
    mc "This might be a silly thought, but..."
    mc "The main character kind of reminds me of you a little bit."
    show y_cg1_exp1 at cgfade
    y "You...think so?"
    y "How does she?"
    mc "Well, I guess she's more blunt in a lot of ways..."
    mc "But she also second-guesses all of the things that she says and does."
    mc "Like she's afraid she'll do something wrong."
    mc "It's not like I can see into your head or anything..."
    mc "But they're kind of reminiscent of some of your mannerisms."
    y "I-I see..."
    scene bg club_day
    show yuri 2t zorder 2 at i11
    with dissolve_cg
    "Yuri remains silent for a moment."
    y "But [player]..."
    y "That's probably..."
    y "...a terrible thing to have in common with her!"
    y 4b "Uuuh, that's so embarrassing that you think that..."
    mc "W-Wait!"
    mc "I didn't mean it in a bad way or anything!"
    mc "Sorry, I really didn't know you were self-conscious about that sort of thing..."
    y "..."
    mc "I guess I more meant that it's kind of cute..."
    y 3q "A-Ah--"
    y "What are you saying all of a sudden...?"
    y "I...!"
    show monika 4 at l31
    m "Okay, everyone!"
    show yuri 3n at h11
    y "...!"
    show monika zorder 3 at f31
    m "I think it's about time we share today's poems with each other."
    m "We might not have enough time if we wait too long."
    show monika zorder 2 at t31
    show yuri zorder 3 at f11
    y 3w "Ah..."
    "Yuri exhales, spared from finishing her thought."
    show yuri zorder 2 at t11
    show monika zorder 3 at f31
    m 1 "Is that alright, Yuri?"
    m "You look kind of down..."
    m "I'm sorry if you haven't been looking forward to this..."
    show monika zorder 2 at t31
    show yuri zorder 3 at f11
    y 3v "Ah, it's not..."
    y "...It's fine."
    show yuri zorder 2 at t11
    show monika zorder 1 at thide
    hide monika
    "Yuri releases her hand from the book, causing it to close on top of my thumb."
    mc "Alright..."
    mc "I guess I'll do some more reading tonight."
    mc "Or would you prefer I only read it with you?"
    y 2f "Um...!"
    y "I...guess I don't have too much of a preference either way..."
    mc "Hmm..."
    mc "In that case, I'll read a little more tonight."
    mc "It'll be more fun to read with you after it picks up a bit, you know?"
    y 2a "That's good reasoning."
    y "In that case, feel free to finish the first two chapters in your own time."
    mc "Alright!"
    show yuri zorder 1 at thide
    hide yuri
    "I stand up."
    "I make a mental note of where I left off in the book, then slip it back into my bag."
    return

label yuri_exclusive_2:
    $ y_exclusivewatched = True
    play music t6 fadeout 1.0
    scene bg club_day
    with wipeleft_scene
    mc "Hey, Yuri."
    show yuri 2f zorder 2 at t11
    y "Eh?"
    mc "Ah..."
    "I suddenly notice that Yuri is reading a different book from the one we've been reading together."
    mc "Sorry! I didn't mean to interrupt..."
    y 2m "Ah, no..."
    y "I was kind of just waiting for you..."
    show yuri 2a
    mc "Ah, if that's the case..."
label yuri_exclusive_2_ch3:
    mc "Why don't we go ahead and get started?"
    y 2c "Yes, let's!"
    y 3a "Actually, I have a request..."
    y "...Do you mind if I make some tea first?"
    mc "Not at all."
    y 1c "Thanks very much."
    y 1a "If there's one thing that can make my reading time here any better, it's a nice cup of tea."
    y "Not to mention for yourself, as well."
    show yuri zorder 1 at thide
    hide yuri
    "Yuri stands up and makes her way to the closet."
    "I follow and watch as she retrieves a small water pitcher from the shelf - the kind with a filter inside."
    show yuri 1f zorder 2 at t11
    y "Can you hold this for a second?"
    mc "Sure..."
    "Yuri hands me the water pitcher and also fetches an electric kettle."
    y "I'm going to plug this in at the teacher's desk, and then we'll go get some water."
    show yuri zorder 1 at thide
    hide yuri
    "She walks past me and sets the kettle down on the teacher's desk."
    "I simply watch her movements."
    "To my surprise, the way she moves really contrasts her speaking mannerisms."
    "Especially because of her long legs, Yuri appears elegant and methodical."
    show yuri 1f zorder 2 at t11
    y "Okay, may I have the water pitcher?"
    y 1a "Thanks. I'll be right back."
    mc "Ah, I might as well walk with you..."
    y 1s "Yeah...why not?"
    y "Shall we go, then?"
    mc "Yeah..."
    show monika 2a at l31
    m "Hm? Where are you two off to?"
    show yuri 2e
    mc "Eh?"
    mc "We're just...Yuri was going to make some tea, so..."
    "I suddenly realize how weird it sounds to explain this to Monika."
    mc "We're just filling the water pitcher..."
    show monika zorder 3 at f31
    m "Ah, okay!"
    m 4j "Sorry, I was just a bit curious..."
    m "That's kind of a one-person job, isn't it?"
    show monika 4a zorder 2 at t31
    mc "That's--"
    show yuri zorder 3 at f11
    y 1k "Monika, please mind your own business for once."
    y "Or do you want to tell me there's something wrong with helping involve [player] in club activities?"
    show yuri zorder 2 at t11
    show monika zorder 3 at f31
    m 1g "E-Eh...?"
    show monika zorder 2 at t31
    mc "--!"
    "My mouth gapes."
    show monika zorder 3 at f31
    m 5a "I..."
    m "I suppose there's nothing wrong with that..."
    show monika zorder 2 at t31
    show yuri zorder 3 at f11
    y 2l "Hmph..."
    y "Then let's go, [player]."
    show yuri zorder 2 at t11
    mc "Ah..."
    "Yuri quickly exits the room, and I follow."
    stop music fadeout 1.0
    scene bg corridor
    show yuri 4c zorder 2 at t11
    with wipeleft_scene
    "Once in the hallway, she suddenly puts her forehead against the wall."
    y "I spoke without thinking..."
    y "How could I say something like that...?"
    mc "Yuri..."
    y 4b "I just..."
    y "Something about the way she said that..."
    y "It made me feel so...irritated."
    y "What's wrong with me...?"
    mc "No, Yuri."
    mc "I think...you did the right thing!"
    mc "I wasn't expecting it, but..."
    mc "It's also not right for Monika to judge people like that."
    play music t9
    y 4a "[player]..."
    y "How come even when I do something bad..."
    y "You're being nice to me?"
    mc "Because."
    mc "Nothing that you do is as bad as you make it seem in your head."
    mc "Nobody's perfect."
    mc "We have emotions, and we can't always hide them away."
    mc "But you always amplify things in your head..."
    mc "Your mind turns a light rain shower into a hurricane."
    y 3q "Ah..."
    y "N-No..."
    y "Wouldn't you hate me for something as terrible as that...?"
    mc "Why would I hate you?"
    mc "I can't hate someone for having emotions..."
    mc "What kind of friend would do that?"
    y 4c "Friend...you say?"
    y "Ah...um..."
    "Yuri lifts her head."
    y 3w "[player]..."
    y 3t "I really like...being friends with you!"
    mc "Ahaha..."
    mc "Thanks, Yuri."
    mc "I like being friends with you too..."
    "I feel kind of awkward saying something like that..."
    "But I'm doing my best to help Yuri feel better."
    mc "Anyway...!"
    y 3u "Ah-- Yeah..."
    y "Shall we go?"
    mc "Yeah."
    show yuri zorder 1 at thide
    hide yuri
    "Yuri and I walk to the nearest water fountain."
    "Once we fill up the water pitcher, we return to the classroom."
    play music t6 fadeout 1.0
    scene bg club_day
    show yuri 1a zorder 2 at t11
    with wipeleft_scene
    y "[player], do you like oolong tea?"
    mc "Ah, yeah."
    mc "Anything is fine."
    y "Very well."
    "Yuri sets the temperature on the kettle to 200 degrees."
    y 1f "Now it's time to get the teapot."
    mc "You really do this properly, don't you?"
    y 1u "Of course..."
    y "I shouldn't do any less when I'm making tea for others."
    mc "Even if I'm not an expert on tea or anything...?"
    y 2m "Huhu."
    y 2a "In that case, you'll only be even more impressed."
    mc "Ah...perhaps I will!"
    show yuri zorder 1 at thide
    hide yuri
    "Yuri fetches the teapot and begins measuring the tea leaves."
    "To my surprise, she even starts humming a little to herself."
    show yuri 1c zorder 2 at t11
    mc "You must be in a good mood now..."
    y 1a "Is that so?"
    y "I was letting it show..."
    y "And you noticed."
    y 2u "I was doing a bit of thinking..."
    y "And I decided that I would try expressing myself a little bit more."
    y "It turns out it's not very hard for me to do..."
    y 1c "When it's you who's around, anyway."
    mc "Ah..."
    mc "That's great, Yuri!"
    mc "Just don't push yourself too much."
    y 3u "You're always worrying about me, [player]..."
    y "It's very endearing."
    mc "That's..."
    "Yuri wasn't kidding..."
    "I don't even know if I can keep up with this...!"
    "I watch Yuri pour a cup of tea for each of us."
    y 1a "[player], I have another request."
    y "Do you mind if we sit on the floor today?"
    mc "Eh? Why's that?"
    y 1h "It's a little bit easier on my back..."
    y "I can read with my back against the wall rather than bending over at my desk."
    mc "Ah, sorry, I didn't realize."
    y 1a "No worries."
    y "I just have back pain fairly regularly, so I do my best to manage it."
    mc "Is that so?"
    mc "I wonder why that is..."
    y 1f "It's most likely because my--"
    y 1n "Ah--"
    y 1o "M-My..."
    mc "Your posture, right?"
    mc "Always hunched over like that while reading..."
    y 2p "Yes!"
    y 2q "I have terrible reading posture!"
    y "So that's why we should sit on the floor."
    mc "Fair enough."
    mc "I'll go ahead and get the book."
    show yuri zorder 1 at thide
    hide yuri
    "I retrieve the book from my bag."
    mc "Ah, I have some chocolate as well..."
    "It's a bag of small chocolate candies that I kept hidden from Sayori's candy radar."
    "I take it, since it'll go well with the tea."
    "Yuri and I then sit against the wall, teacups at our sides."
    "As if in sync, we assume the same reading position as last time, each holding one half of the book."
    "Except this time..."
    "Our bodies are even closer to each other."
    show yuri 2h zorder 2 at t11
    y "I can't see too well..."
    mc "--!"
    show yuri 2e at d11
    "Yuri slides closer until our shoulders are touching."
    "How am I supposed to focus on reading like this...?!"
    "Yuri was always kind of cute, but..."
    "When she's being less apprehensive, it's almost more than I can handle!"
    y 2f "Your teacup..."
    "Yuri hands me my teacup."
    "Holding it with my hand that's not holding the book, I end up in a position that makes it even harder to focus."
    "Because now I need to worry about making sure I don't accidentally touch her chest...!"
    "Meanwhile, Yuri hasn't noticed a single thing."
    "She wears her intense reading expression, and I can only presume the world around her has faded away."
    "I use all of my willpower to focus on reading."
    "..."
    "After a few minutes, I finally manage to relax a little."
    "I put the teacup between my legs and fumble with the chocolate wrapper."
    mc "Ah, sorry..."
    "I briefly let go of the book to finish opening the wrapper."
    mc "You can have as much as you want."
    y 2s "Ah, that's..."
    y "That's okay, I won't take any..."
    mc "Eh? Are you sure?"
    y 2v "Well..."
    y "If I touch it, then it might get smudges on the pages..."
    mc "Ah, you're right..."
    mc "I didn't even think about that."
    mc "My bad..."
    y 2a "No need to apologize."
    y "I'll hold the book, okay?"
    mc "Are you sure...?"
    y "Of course."
    $ persistent.clear[3] = True
    $ renpy.save_persistent()
    scene y_cg2_bg
    show y_cg2_base
    show y_cg2_details
    show y_cg2_nochoc
    show y_cg2_dust1
    show y_cg2_dust2
    show y_cg2_dust3
    show y_cg2_dust4
    with dissolve_cg
    "Yuri opens the book with both hands."
    "She holds it so that I don't have any harder of a time reading from it."
    "But as a result, her left arm is practically resting on top of my leg."
    mc "Well, in that case..."
    "Yuri is already totally focused on reading again."
    "I take a chocolate candy and pop it into my mouth."
    "Then, I take another chocolate..."
    "And I hold it up to Yuri."
    "She doesn't even look away from the book."
    "She simply parts her lips, as if this situation was completely natural."
    "But that means I can't stop here!"
    hide y_cg2_nochoc
    "I apprehensively place the chocolate in her mouth."
    "Just like that, Yuri closes her lips over it."
    y "Eh...?"
    show y_cg2_exp2
    "Yuri's expression suddenly breaks."
    y "Did..."
    y "Did I just..."
    "Yuri looks at me like she needs to confirm what just happened."
    show y_cg2_exp3
    show y_cg2_nochoc:
        alpha 0
        linear 0.5 alpha 1
    hide y_cg2_exp2
    y "U-Um..."
    y "[player]..."
    mc "S-Sorry!"
    mc "I guess I shouldn't have done that..."
    y "Ah, that's..."
    y "Well..."
    y "Y-You were just helping..."
    y "That's something that...friends do..."
    y "...Right?"
    mc "I mean..."
    "Not really in this kind of context, but..."
    mc "Yeah..."
    mc "...That's all it was."
    y "Yeah..."
    y "Then..."
    y "You don't need to stop or anything..."
    mc "I-I see..."
    hide y_cg2_exp3
    "The situation has gotten really tense..."
    "Yuri tries to return to the book."
    "But I can tell just by her expression that even she can't focus now."
    "My heart is pounding..."
    "I nervously take another chocolate between my fingers."
    "But this time, Yuri's eyes meet mine."
    show y_cg2_exp3
    y "..."
    "How did it even come to this...?"
    "Yuri doesn't avert her gaze."
    "I notice her chest rising and falling to the rhythm of her breaths."
    "I raise my arm..."
    y "Ah..."
    "Like before, Yuri parts her lips."
    "But...it's different this time."
    hide y_cg2_nochoc
    "I take the chocolate and place it in her mouth."
    "I feel her hot breath on my fingers."
    stop music
    window hide(None)
    scene bg club_day
    window show(None)
    window auto
    show monika 4b zorder 2 at l31
    m "Okay, everyone!"
    mc "Uwa--"
    show yuri 3p zorder 2 at t11
    y "A-Ah!"
    play music t3
    "Yuri jolts back."
    show yuri 3n
    show monika zorder 3 at f31
    m "It's time to share poems!"
    m "[player], you can help Yuri put away the tea stuff, right?"
    show monika zorder 2 at t31
    mc "Y-Yeah...of course."
    show monika zorder 3 at f31
    m "Okay, thanks!"
    show monika zorder 1 at thide
    hide monika
    "The spell is abruptly broken."
    y 4c "I'll..."
    y "I'll take care of the cups..."
    mc "Yeah..."
    show yuri zorder 1 at thide
    hide yuri
    "Yuri picks up the teacups from the floor."
    "I pick up the bag of chocolates."
    "In the end, we hastily clean up without so much as a word between us."
    "I get the feeling this is something neither of us will have the courage to bring up..."
    return

label yuri_exclusive_3:
    $ ch5_name = "Yuri"
    if ch4_name == "Yuri":
        mc "Well, I did intend on spending some time with Yuri."
        mc "We really made a connection on Sunday with all the decorations we made."
    else:
        mc "I didn't get to spend any time with Yuri on the weekend."
        mc "So I'm going to make it up to her by spending this time with her now."
    m 1a "Alright [player]~"
    m "You know where the arts and crafts section is, right?"
    mc "Yeah, I think I do."
    m "Well, have fun with Yuri!"
    play music t6 fadeout 1
    scene bg corridor
    with wipeleft_scene
    "I make my way out the clubroom and see Sayori talking to some people."
    show sayori 4d zorder 2 at t11
    s "Hi [player]~"
    s "Where are you going?"
    mc "I was just going to see Yuri before we do our thing."
    mc "Are you holding up okay?"
    s 4a "Yeah, just fine."
    s 4q "In fact, look at everybody who wants to see what we have planned!"
    "She points excitedly at the dozen or so people talking to each other."
    mc "Wow, that's definitely a lot more than I expected."
    s 4d "Yeah, I promised each of them two cupcakes..."
    mc "Do we even have that many?"
    show sayori 5b at s11
    s "Well..."
    s "Maybe?"
    show sayori 4j at t11
    s "Um...anyway you should go find Yuri now, right?"
    mc "Oh, yeah. Good luck!"
    "I give her a wave before heading off to the arts and crafts area."
    scene bg rooftop
    with wipeleft_scene
    "The arts and crafts area is usually on the rooftop of the school."
    "Someone told me that the view helps people find inspiration or something."
    "I look for Yuri among the people here."
    "There isn't many, so I find her rather quickly."
    show yuri 1a at t11
    mc "Hi, Yuri."
    mc "Are you enjoying yourself?"
    y 1f "[player]..."
    y "I didn't expect to see you here."
    if ch4_name == "Yuri":
        y "I'm sorry about earlier..."
        y "I don't know what came over me."
    elif sayori_confess:
        y "I thought you were going to be spending time with Sayori."
    else:
        y "I thought you'd be going to be time with Natsuki."
    y 1h "But if you still want to spend time with me..."
    y "Well, I can't really stop you."
    mc "Am I that unlikeable?"
    y 1p "N-No!"
    y 1q "Um...what I meant to say is..."
    y "It's the opposite."
    y "I like spending time with you."
    show yuri at s11
    y 1t "But if you don't feel the same..."
    mc "Yuri, calm down."
    mc "I really do want to spend time with you today."
    mc "I didn't come all the way up here for nothing."
    y "..."
    show yuri 1s at t11
    y "Okay...I believe you."
    "Now that the tension is all gone, I can finally spend some time with Yuri."
    mc "So, what are you doing up here?"
    y 1f "I'm just looking..."
    y "But I don't really intend to join any of the clubs here."
    y 1a "I'm content in the Literature Club."
    mc "So what are you looking at exactly?"
    y 1h "Mmm..."
    y "I don't know how you'll react if I tell you."
    mc "Yuri, I'm not really a judgmental person."
    mc "You can tell me."
    y "Well..."
    y 1f "Okay."
    y "I was looking at knives."
    mc "Knives?"
    mc "Why?"
    y 1p "Ah--"
    y "I thought you weren't going to judge me..."
    mc "Well, I'm just curious as to why you're looking at knives."
    mc "I thought you'd be more interested in the sculptures or paintings here."
    y 1t "Do you remember what was in my poems?"
    "Everything in my memory is kinda hazy."
    "Instead of lying to make her feel better, I'm just going to be honest with her."
    mc "No, not really."
    mc "Sorry, my memory is a little fuzzy."
    y 1h "Really?"
    y "Mine is too, it's a little odd."
    y 3e "I can't remember what happened this morning after I got to the clubroom."
    if ch4_name == "Yuri":
        y "I just remember having an argument with you...then ending up here."
        y "But I can't seem to remember what we were arguing about."
    else:
        y "I just remember arriving and then ending up here."
    mc "Yeah, after I got to the club today I just remember waking up."
    mc "I must have taken a nap or something..."
    y "..."
    y 3i "Well, instead of trying to remember my poems..."
    y "I think it's easier if I just tell you..."
    y 3s "But promise me you won't be weirded out."
    mc "Alright, I promise."
    if ch4_name == "Yuri":
        y 3t  "Do you remember on Sunday, when I showed you that knife?"
        y 3v "...Sorry, I shouldn't be asking these sorts of questions with your memory acting up..."
        mc "Now that you mention it..."
        mc "I actually do remember that, I still have the cut."
        "I show her my index finger with the tiny cut on it."
        y 3u "A-Alright..."
        y 2t "Well then you should remember that I'm kind of into knives."
        "She pulls out a pocket knife, different from the one on Sunday."
        "This knife is just as beautiful as the one on Sunday."
    else:
        y 3q "The thing is, I'm kind of into knives..."
        y "They're just...so pretty..."
        y 2v "I-I can't help it!"
        y "I don't know what it is..."
        y "The combination of craftsmanship and feeling of danger, maybe..."
        y 4b "Uu, what am I saying...?"
        y "You're secretly judging me, aren't you...?"
        mc "Ahaha."
        mc "It's...well, it's an interesting thing to be into, I guess."
        mc "But I think it kind of suits you."
        y 2t "Suits me...?"
        mc "Yeah... It's kind of intense. Ahaha."
        "Yuri pulls out a pocket knife."
        "The knife is strangely beautiful."
    "The golden handle has an intricate pattern of chains etched into it."
    "The blade itself is a careful mix orange and red."
    mc "That's..."
    mc "Pretty cool!"
    y 4b "Eh...?"
    mc "Do they have any knives up here like that one?"
    y 4a "N-No...it looks like the knives here are pretty plain."
    mc "Well, I can see why you're into knives."
    mc "I don't really see myself collecting knives like that."
    mc "But to each their own, right?"
    y 3s "Right..."
    "Yuri giggles shyly."
    mc "Did I say something funny?"
    y "No...it's just..."
    y "I really enjoy spending time with you [player]."
    y 3v "It's a shame we didn't get to spend more time in the club before now."
    mc "Yeah..."
    mc "But we have to make the most of our time now, right?"
    mc "Besides, after our little performance we can still hang out."
    mc "It's not like the performance goes until the end of today."
    y 3u "I suppose you're right."
    "Yuri walks over to the balcony."
    "I follow behind her."
    scene y_cg4_base with dissolve_cg
    y "Even if there are people here..."
    y "It's quite peaceful..."
    show y_cg1_exp1 at cgfade
    #show y_cg1_exp2 at cgfade
    y "[player]..."
    y "People say they take inspiration from looking at the view..."
    y "Personally, I don't find that to be the case."
    mc "How so?"
    hide y_cg1_exp1
    y "Well, there's nothing to take inspiration from up here."
    y "There's just buildings in all directions..."
    y "How could you possibly find anything inspiring from that?"
    mc "I guess you have a point there."
    mc "You can't deny the view is beautiful though."
    show y_cg1_exp2 at cgfade
    y "Y-Yeah..."
    y "How about you?"
    show y_cg1_exp1 at cgfade
    y "Can you find any inspiration here?"
    "I take a good look at what's ahead of me."
    "She's right, there's mainly buildings all the way to the horizon."
    "The only thing that stands out is a park out in the distance."
    mc "Ah..."
    mc "Maybe that park?"
    mc "It's a little patch of nature in a place surrounded by civilization."
    mc "Maybe there's still hope for it, despite the odds..."
    mc "..."
    mc "Yeah...maybe you're right about that whole inspiration thing."
    hide y_cg1_exp1
    "Yuri giggles again."
    y "Well, [player]..."
    y "At least you found something..."
    y "You even made it sound poetic."
    y "Hmm..."
    y "There really is nothing up here."
    y "No knives, no inspiration, nothing..."
    "She walks back from the balcony."
    scene bg rooftop
    show yuri 1u zorder 2 at i11
    with dissolve_cg
    mc "Well, there's one thing..."
    y 1t "And what would that be?"
    mc "Good company."
    show yuri 4c
    "Yuri visibly blushes and turns away."
    y "Eh?"
    y "Y-You can't possibly think that I'm good company..."
    y "I'm weird!"
    mc "You're not--"
    y "I like knives and..."
    mc "Ahaha..."
    mc "I already told you I'm not going to judge you Yuri."
    mc "This time, I'm being honest."
    y 3f "Time?"
    y "W-We should get back [player]!"
    y 3n "We still have to do our poetry performances!"
    y 3p "Ah..."
    y "...I didn't mean to raise my voice..."
    y 1n "I'm sorry."
    mc "Yuri, you really don't need to keep apologizing for stuff like that."
    mc "There's no need to be so reclusive around me."
    y 1n "You're right..."
    y 1o "I'm sor--"
    "She stops herself."
    y "..."
    y 1q "Well, we should head back to the club..."
    "I nod and follow her to the clubroom."
    # Basically Copy Paste This Part For Natsuki
    scene bg corridor
    show natsuki 1a zorder 2 at i21
    show sayori 1a zorder 2 at i22
    with wipeleft_scene
    "Yuri and I make our way back to the clubroom."
    "Natsuki and Sayori are already waiting outside."
    show yuri 1n zorder 2 at l31
    show natsuki zorder 2 at t32
    show sayori zorder 2 at t33
    "The amount of people ready to see what we have in store hasn't changed."
    "That means Sayori didn't let them get too bored at least."
    show yuri 1p zorder 3 at f31
    y "I apologize if we're late!"
    y "We um...lost track of time and..."
    "Yuri looks towards me for assistance."
    show yuri zorder 2 at t31
    mc "It's my fault."
    mc "If I didn't distract her then she would have been here earlier."
    mc "I'm sorry if I caused any trouble."
    show sayori 1r zorder 3 at f33
    s "Ehehe~"
    s "It's alright you two. You're just in time!"
    s 1d "Besides, Monika isn't here yet..."
    s "But I'm sure she won't be too long, so let's head inside."
    return

label yuri_exclusive_4:
    $ yuri_approval = 3
    show yuri 2by5 zorder 2 at t11
    y "[player], you're finally here!"
    y "Quick! Follow me upstairs!"
    scene bg y_bedroom
    with wipeleft_scene
    play music t6 fadeout 1.0
    "Yuri practically dragged me up the stairs into her room."
    "Her house has this odd aroma of metal emitting from the walls."
    "The bedroom also seems very familiar."
    "It looks almost exactly like my own..."
    show yuri 3by5 zorder 2 at t11
    y "What do you think, [player]?"
    y "Do you like what I've done?"
    mc "This is..."
    mc "...really weird."
    y 2bb "I did this in preparation for you, [player]."
    y "It took me a while but it's almost perfect."
    y 2bc "I hope you feel right at home."
    mc "Eh?"
    mc "What do you mean in preparation for me?"
    mc "Were you expecting me to come here?"
    y 2by3 "Y-Yes!"
    y 2bq "I-I mean not exactly..."
    if ch4_name == "Yuri":
        mc "You've seen my room, right?"
        mc "It looks almost exactly alike!"
        mc "What a coincidence."
        y 2bf "I don't think so."
        y "I went to your house."
        y 2bk "It was very difficult to get there without arousing suspicion."
        y "Especially since {i}she{/i} is always walking with you."
        y 1bw "But since you were talking to Monika yesterday, you were preoccupied."
        y "So I went into your house and into your room."
        y "I was there for a while."
        y 1by6 "I even left my scent for you in some of your belongings."
        y 1by1 "Then I took lots of pictures of your room so I could make it myself."
        y "That's why it looks perfect."
    else:
        mc "You were never at my house, were you?"
        mc "It must be a coincidence that your room looks almost exactly like mine."
        y 2bf "It's not a coincidence."
        y 2bs "I followed you home, [player]."
        y 2bk "It was difficult without looking suspicious."
        y "Especially since {i}she{/i} is always walking with you."
        y "I had to be really careful about it."
        y 1bj "But I got the perfect chance yesterday."
        y "After Monika finished speaking with you, you were alone."
        y 1by6 "So I just followed you until you got to your house."
        y "And when you were talking to Sayori..."
        y 1by1 "I made sure to take lots of pictures."
        y "So I could recreate your room perfectly.."
    y "Do you like it?"
    menu:
        y "Tell me you like it, [player]."
        "Yes":
            $ yuri_approval -= 1
            $ persistent.sayori_reload_yuri = True
            y 1by5 "Ahaha, I'm so glad."
            y "I did all of this for you."
            y "I want to revolve my whole life around you, [player]."
            y 1bs "Isn't that nice?"
            y "Does it feel good to have someone care about you so much, [player]?"
            y 3bd "This is the best day of my life."
            y 3bf "What do we do?"
            y 3bk "We don't have to read that novel anymore."
            y "After all, you're staying right here forever."
            y 3by4 "It will be just us in this room."
            y "I'm going to take care of you."
            y "There's no need to worry..."
            y 3by5 "Right, [player]?"
            y "..."
            y 1bo "You're really quiet, aren't you?"
            y "That's okay."
            y "You don't need to say anything."
            y 1by3 "All I need is you here."
            if persistent.sayori_reload_yuri_message:
                $ currentpos = get_pos()
                $ audio.t6b = "<from " + str(currentpos) + " loop 10.893>bgm/6.ogg"
                stop music
                show yuri glitch_sayori zorder 2 at t32
                $ y_name = "Yuri?"
                $ pause(1.2)
                $ config.skipping = False
                $ config.allow_skipping = False
                y "Um..."
                if persistent.sayori_yuri_bad_ending:
                    y "We've been here before..."
                    y "You know what to do, right?"
                    y 1brs "So please, you have to go back."
                    y "Just before you enter her room."
                    y "Better yet..."
                    y "Choose someone else entirely."
                    y 1bvs "..."
                    y "Well..."
                    y "This is it, isn't it?"
                    y "Please, [player]."
                    y "I can't do this anymore..."
                    y "I hope you do the right thing."
                else:
                    y "Sorry."
                    y "I didn't want to have to do this."
                    y 1brs "But I really don't want [player] to have to get hurt."
                    y "I'm sure you know this was a bad idea."
                    y "I should have said something in the meeting."
                    y "In case you haven't noticed, it's not Yuri talking to you right now."
                    y "I won't be here for long, so I'll be quick."
                    y 1bfs "If you really want to risk [player]'s life here..."
                    y "And ruin everything we've worked for."
                    y 1brs "Then just keep playing."
                    y "This is all a game to you after all, isn't it?"
                    y 1bvs "If only you knew what this felt like."
                    $ stream_list = ["obs32.exe", "obs64.exe", "obs.exe", "xsplit.core.exe", "livehime.exe", "pandatool.exe", "yymixer.exe", "douyutool.exe", "huomaotool.exe"]
                    if not list(set(process_list).intersection(stream_list)):
                        if currentuser != "" and currentuser.lower() != player.lower():
                            y "Please, [currentuser]..."
                    y "You have to understand what this means to me."
                    y "I hope you have a save.{nw}"
                    show screen tear(20, 0.1, 0.1, 0, 40)
                    window hide(None)
                    play sound "sfx/s_kill_glitch1.ogg"
                    $ pause(0.25)
                    stop sound
                    hide screen tear
                    window show(None)
                    y "I hope you have a save.{fast}"
                    window auto
                    y "You have to go back."
                    y 1bts "Choose a different person, please..."
                    y "Or at the very least go back to {i}right{/i} before you went to Yuri's room..."
                    y "It's the only way I can help in the case that..."
                    y "...this really is what you want."
                    y "..."
                    y 1brs "You aren't changing your mind, are you?"
                    y "..."
                    y 1bvs "Then I hope you know what you're doing."
                show yuri glitch_sayori zorder 2 at t32
                $ y_name = "Yuri"
                $ persistent.sayori_reload_yuri_message = False
                $ pause(1.2)
                $ _history_list = []
                $ config.allow_skipping = True
                play music t6b
                y 1by2 "W-What?"
                y "What just happened?"
                y 1by3 "It doesn't matter."
            $ persistent.sayori_reload_yuri = False
            y 1by1 "Do you want to look at my knife collection?"
            y "I'm sure you do."
            y 1by3 "You aren't objecting."
            y "Ahaha."
            y 2by4 "I'll just be a minute, don't you dare move."
            show yuri at thide
            hide yuri
            "..."
            "..."
            "..."
            show yuri 2by1 zorder 2 at t11
            y "You're still here!"
            y "I'm so glad."
            y 3by6 "I was just testing you."
            y "I really thought you would have left me."
            y 3by4 "If you did, I would have found you."
            y "And neither of us would want what would have happened next."
            y "..."
            y 3br "Why aren't you talking?"
            y "[player]!"
            y 3bs "You must still be taking it in."
            y "Accepting that we were meant to be."
            y "That has to be it."
            y 3by1 "There's no other reason."
            y 1by3 "It's not like those other three--"
            y 1by7 "They didn't call you, did they?"
            y "Did they tell you about me?"
            y "How much does she know?"
            stop music
            y 1by3 "I'm going to kill them."
            y "Tomorrow in the club meeting..."
            y 1by4 "I'm going to kill them all."
            y "One by one."
            y 1by1 "I'm going to watch the life drain from their eyes."
            y "I can't wait."
            y "I feel like cutting myself just thinking about it."
            y "..."
            y 1by6 "Don't tell me..."
            y "You haven't read the ending of the book, have you?"
            y 1bk "Do you want to know what happens?"
            y 3bs "By that expression on your face, I'm going to guess you do."
            y 3bl "The wanderer made one of the daughters kill herself."
            y "Everyone was devastated, with the wanderer feigning grief."
            y "Through that, the lumberjack and the wanderer grew closer."
            y 3bs "But the wife knew what was happening."
            y "And so did the wanderer."
            y 1bd "So she started manipulating the wife and her other daughter."
            y "She made the wife crazy."
            y 1by2 "Not like me!"
            y "I'm not crazy, am I [player]?"
            y 1by1 "We both know I'm just obsessed with you."
            y "There's nothing wrong with that."
            y 1by3 "Ahaha, anyway...!"
            y 1by4 "She started making the other daughter more cold to everyone else."
            y "And the wife started harming herself."
            y 1by1 "She'd find time to be alone and just start ripping through her own skin."
            y "Of course, the lumberjack knew nothing and the wanderer just grew closer and closer to him."
            y 1by6 "Wow, maybe I was wrong."
            y 2bc "This sounds a lot like a horror book now."
            y 2ba "Eventually the wife and the daughter kill themselves."
            y 2bb "And it's just the wanderer and the lumberjack left."
            y "But..."
            y 2bk "The wanderer starts to feel regret."
            y "She does all she can to make things right."
            y "And eventually everyone ends up alive again, in a world where she never existed."
            y "And they all live {i}happily ever after{/i}."
            y 1by3 "What a pathetic story, right?"
            y 1by1 "Hmm...that gives me an idea."
            y "I'm not going to kill them straight away."
            y "Instead, in the play, I'm going to bring my sharpest knife."
            y 1by4 "I know for a fact that Sayori is going to choose that chapter where the wife and the older daughter kill themselves."
            y "She's trying to help me, isn't she?"
            y 1by3 "Ahaha, well, I'm going to kill everyone."
            y "I'll do it for us."
            y 1by6 "That's what both of us want, right?"
            y 1by7 "Don't tell me you have feelings for them."
            y "They are nothing."
            y "Now..."
            y 1bs "I need to prepare some things for tomorrow."
            y "So you stay here."
            y 1by3 "Don't move an inch, okay?!"
            y "This will only take all night..."
        "Yuri, what the hell?!" if persistent.sayori_reload_yuri:
            stop music
            show yuri 3bn zorder 1 at h11
            y "W-What?"
            y "What did you just say?"
            mc "This isn't right."
            mc "You have to stop doing this Yuri."
            mc "I know you're dealing with some issues."
            mc "So please, let me help!"
            y 3bo "..."
            play music t9
            mc "Yuri, I know you harm yourself."
            mc "It's why you wear clothes that cover your arms."
            mc "It's why you isolate yourself..."
            mc "So you don't accidentally harm those you care about."
            mc "And..."
            mc "There's something else, isn't there?"
            "I don't know what's come over me."
            "I just felt like I needed to say that."
            "Those words must have some effect on her, right?"
            $ needs_to_read = True
            if read_book or did_all_tasks:
                $ yuri_approval += 1
                y "..."
                y 3bt "Um...?"
                y "Why am I doing this?"
                y "I..."
                y 1bv "I have a problem..."
                mc "Yuri...?"
                y 1bt "Please, [player]."
                y "I don't want to hurt you."
                y "I don't want to hurt them."
                y 1br "Get out of here..."
                y 1bv "Before it's too late..."
                y "I should have listened..."
                y 1bw "I should have listened to Monika."
                y "Why did I..."
                mc "Yuri, let me help you."
                mc "You're really important to me."
                if sayori_confess:
                    y 1bs "That's not true...[player]."
                    y 1bt "I know that you and Sayori are together..."
                    y "I've had to cut myself more because of it..."
                else:
                    y 1bv "I..."
                    y "I've been cutting myself more..."
                    y 1bt "...because I had a feeling you felt the same about me."
                y 1bw "But it can't be helped..."
                y "I've really tried, [player]."
                y "You have to believe me when I say I did..."
                y "No matter what I did..."
                y 3bt "I would just end up cutting myself more and more."
                mc "We're trying to help you, Yuri."
                mc "We know this isn't the real you."
                y 3bv "We?"
                y "What...do you mean?"
                "I can't even comprehend my own words right now."
                "It's like someone else is speaking through me."
                "Even still, I mean those words."
                mc "We--"
                mc "I want to help you get through this."
                mc "I know you're not in control when you cut yourself."
                mc "It's like someone is making you do it..."
                mc "And all you feel is ecstacy..."
                mc "Right?"
                y 3bt "How..."
                y "...did you know that?"
                "The truth is, I didn't."
                "But whatever is making me talk like this seems to."
                y 3bv "[player]..."
                y "It's better if you leave while..."
                y 3bs "...I'm still myself."
                y "But you have to read the novel."
                y 3bv "You have to...find out how it ends."
                y "It will be really important for tomorrow."
                y 3bw "Now..."
                y "Please, you have to go."
                mc "Okay, Yuri..."
                mc "I'll see you tomorrow."
                scene bg y_house
                with wipeleft_scene
                "With that, I leave Yuri's house."
                "I don't know what's going on with her."
                "But I feel completely helpless."
                "If only there was someway I could help her..."
                "I just hope everything will get better tomorrow."
                stop music fadeout 2.0
                scene black
                with dissolve_scene_full
            else:
                $ yuri_approval -= 1
                stop music
                y 2by4 "You're wrong [player]."
                y "I've never felt better."
                y 2by3 "I don't need anyone's help."
                y 2by7 "Especially not from the likes of you."
                y "..."
                y 2by4 "Why did you come here?"
                y "[player]..."
                $ style.say_dialogue = style.edited
                y 2by3 "YOU DON'T KNOW WHAT YOU'RE TALKING ABOUT."
                y "DO YOU HEAR ME?"
                y "I DON'T NEED YOUR SYMPATHY."
                y 2by4 "I ONLY NEED YOU."
                y "IF YOU HAD JUST LET ME HAVE YOU, THEN WE'D ALL BE HAPPY."
                y 2by1 "NOW YOU'LL NEVER KNOW THE END OF THAT STUPID CLUB BOOK."
                y "I WONDER IF YOU EVEN KNOW WHAT YOU'RE DOING."
                scene bg y_house
                with wipeleft_scene
                $ style.say_dialogue = style.normal
                "What was that?"
                "I was imagining that, right?"
                "I must be..."
                "And when I wake up tomorrow, everything is going to be fine..."
                "...Right?"
                scene black
                with dissolve_scene_full
    return
