label valentines_chapter:
    hide screen tear
    $ chapter = 1001
    scene black
    if from_custom_start:
        $ from_custom_start = False
        $ quick_menu = True
        hide screen tear
    $ s_name = "???"
    $ cl_name = "???"
    $ ayame_hair_tied = True
    $ audio.t3r = "<from 0 to 48.0 loop 0>mod_assets/bgm/3r.ogg"
    # Remove when done
    $ quick_menu = True
    play music t3r
    if persistent.did_valentines_event:
        s "This feels really familiar..."
    else:
        s "It feels like it's been a long time."
    s "Just how long has it been since we last spoke?"
    s "I can never tell between us."
    s "You could be gone for a day, a week, a year and I wouldn't know the difference."
    s "That could be a good thing."
    s "Maybe it's been just a few moments since we last spoke..."
    s "Or maybe it's been far, far too long."
    s "Either way, you're here now."
    s "I hope that's a sign you haven't abandoned us."
    scene bg random_gray
    $ style.say_window = style.window_flashback
    s "Today feels like a special day."
    s "A day where love is in the air."
    s "I want you to treat them right."
    s "To make sure that they get what they deserve."
    s "You wouldn't be here if you didn't want to make them happy, did you?"
    s "At least...I hope so."
    s "Whatever you do, you have to know something."
    s "This world...this isn't {i}our{/i} world."
    s "There's so many things that are the same but..."
    s "...it's not ours."
    s "They seem so much happier here than they do in our world."
    s "What happened that made them this way?"
    s "Could {i}I{/i} still make that possible...?"
    s "..."
    s "Still, I don't want you to ruin this for them."
    s "So please promise me that you'll do what's right."
    menu:
        s "You will, won't you?"
        "Yes.":
            pass
        "No.":
            s "If you won't agree to these terms then I can't let you in here."
            s "You don't have the right to interfere with their lives and make it worse."
            s "I hope you can understand that, at least."
            $ renpy.utter_restart()
    s "I hope I can trust you."
    s "I'll let you see this world."
    s "Maybe you can make them happy, even if you can't be here long."
    s "Good luck..."
    stop music fadeout 1.5
    scene bg shop_sunset with Dissolve(1.5)
    play music t2 fadein 3.0
    $ insert_characters_alternate(monika=False,mc=True,ayame=True,timeline=66)
    $ s_name = "Sayori"
    $ style.say_window = style.window_valentines
    $ config.allow_skipping = True
    "I hope she'll like what I've bought for her."
    "I'm not the best at choosing gifts but it's the thought that counts, right?"
    show screen item("mod_assets/gui/items/gum.png")
    "..."
    "Oh, who am I kidding?"
    "She's gonna hate it."
    "What was I thinking buying this for her?"
    hide screen item
    "Valentine's Day is tomorrow and this is all I got her?"
    "Surely I can do better than this..."
    show mysteriousclerk 1a zorder 2 at t11
    cl "You definitely can, my soon-to-be friend."
    "A rough-looking man appears in front of me."
    "He looks at the piece of chewing gum I'm holding and shrugs."
    mc "What? Who are you?"
    cl "You can call me..."
    $ cl_name = "Charlie"
    cl "...Charlie. Yeah, let's go with that."
    cl "Look [player], I don't think a bit of gum is going to cut it."
    cl "She has higher standards than that."
    cl "Surely, that's not all you can think of."
    mc "My love life is none of your business."
    "I look at the chewing gum again."
    "I'm hopeless, aren't I?"
    cl "Are you sure that's what you want to give her?"
    cl "You're not even going to buy her a box of chocolates?"
    cl "Or like...some flowers?"
    cl "Like a normal person?"
    mc "You think I haven't tried buying those?"
    mc "I've been to several shops and every place seems to be sold out on them."
    mc "The only thing I could find was this."
    cl "Down on your luck, huh?"
    cl "Well, luckily uncle Charlie is here to help you."
    mc "\"Uncle Charlie\"...?"
    "Who is this guy really?"
    "I can't quite put my finger on it but..."
    "There's something oddly familiar about him."
    "And for some reason, I feel like I can trust him."
    "The other option is giving her some gum for Valentine's Day."
    "...Yeah I don't think that's a good idea."
    mc "Okay, then what did you have in mind?"
    cl "It just so happens I have a store that's selling some perfect Valentine's Day gifts."
    mc "You have a store?"
    cl "That's right."
    mc "Then why are you out here and not in your store selling stuff?"
    cl "..."
    mc "..."
    "The man stands there silently, looking like he's trying to think of something to say."
    cl "The name is Charlie, remember? Not just \"the man\"."
    mc "What?"
    cl "Look, that's not important. Do you want your gift or not?"
    mc "Well, yeah..."
    cl "Alright, then follow me and quick."
    cl "It's getting late."
    "Just what am I getting myself into...?"
    "This \"Uncle Charlie\" better have something I can get her..."
    cl "Trust me."
    scene bg anticshop2 with wipeleft_scene
    play music t17 fadeout 2.0
    "He takes me inside of a closed store."
    "The sign outside was blank, as if the store hadn't officially opened yet."
    "But he had the key so he's clearly the owner, or something like that."
    "I wonder why he's got Valentine's Day decorations when he's not open."
    "But then again, who am I to question this guy...?"
    "Inside, there's lots of seemingly random items."
    "This seems more like a pawnshop that anything."
    show mysteriousclerk 1a zorder 2 at t11
    cl "Welcome to my shop."
    mc "I noticed the sign outside was blank."
    cl "Yes, well...it's a new shop."
    mc "Do you have a name for the shop?"
    cl "I do! It's called...um..."
    "Charlie looks around the store before turning back to me."
    cl "Uncle Charlie's...Knick Knacks!"
    mc "Right..."
    mc "So about that gift."
    cl "Yes, yes. I've got just the thing for you."
    "This is going to be good."
    cl "Behold!"
    show screen item("mod_assets/gui/items/movie.png")
    "The man pulls out a movie and hands it over to me."
    "It's not something I've ever seen before."
    "Or heard of before."
    hide screen item
    cl "I guarantee with this movie, many romantic times will be had!"
    cl "She'll be head over heels for you in no time!"
    "The man stands there proudly, expecting me to take it."
    cl "It's Charlie. Come on, we've been over this."
    mc "Uh...sorry. Right, Charlie..."
    mc "I've never even heard of this movie before."
    mc "How are you so sure she's going to like it?"
    cl "Are you kidding me?"
    cl "Why wouldn't she like it?"
    cl "It's a story about...uh..."
    "Charlie takes the movie and quickly scans the back of it."
    "I think he's just reading the plot summary."
    cl "You know what, forget it."
    play sound "sfx/smack.ogg"
    "Charlie tosses the movie away carelessly."
    mc "Don't you have chocolate or something?"
    mc "Something a normal person would have?"
    cl "Ohoho, are you saying that this girl of yours is a normal person?"
    mc "I--"
    cl "No! Your girl is a very special girl."
    cl "She's not going to accept an ordinary gift like {i}flowers{/i} or {i}chocolate{/i}."
    cl "Come on, [player]!"
    mc "But you--"
    cl "Instead, give her this."
    show screen item("mod_assets/gui/items/doll.png")
    "Charlie pulls out a small mannequin doll."
    mc "What's this...?"
    cl "You clearly know what it is, so why are you asking?"
    hide screen item
    mc "Why would she want this?"
    cl "Well, why wouldn't she?"
    cl "You can do so many things with this!"
    cl "You can pose it and draw it and..."
    cl "Okay, fine. That won't work either."
    play sound "sfx/smack.ogg"
    "Charlie tosses the mannequin away like he did the movie."
    mc "I think coming here was a mistake."
    mc "Maybe I'll just stick with the gum..."
    "I start making my way towards the exit."
    cl "Wait!"
    mc "This was a waste of time. I have to get going."
    "Before I can reach the door, Charlie stands in front of me and blocks it."
    cl "I've actually found the perfect gift for her."
    mc "I don't think you have."
    cl "Look, she uses the guitar, doesn't she?"
    cl "Or was it the piano...?"
    mc "She plays the guitar."
    cl "Right, I thought so."
    cl "Sorry, lots of different timelines to keep track of."
    mc "Timelines?"
    cl "Never mind that."
    cl "Here, I have the perfect gift for her."
    "Charlie forcibly puts something in my hand."
    show screen item("mod_assets/gui/items/capo.png")
    "It's some sort of metallic object with a clamp on it."
    "What is this meant to be...?"
    hide screen item
    mc "What is this thing?"
    cl "You said she uses the guitar, doesn't she?"
    cl "Surely, you've noticed her have one of these when she's used her guitar."
    "Thinking back on it...she did have something that looked like this on her guitar."
    "I remember going to her house before and it suddenly broke while she was playing."
    cl "It's called a \"capo\". Something guitar people use when they do the thing."
    mc "Do the thing?"
    cl "You know...do the guitar thing."
    mc "Play it?"
    cl "That's it."
    mc "I guess a gift like this kinda makes sense..."
    cl "See, what did I tell you?"
    cl "Trust uncle Charlie."
    mc "How much is it going to cost me?"
    cl "Let me see..."
    "Charlie walks behind the counter and seemingly presses buttons at randomm on the register."
    cl "That will be..."
    cl "...free of charge!"
    mc "Free?"
    cl "Yes, you heard me."
    mc "Are you sure?"
    cl "Yes, now get out of here before I change my mind!"
    mc "But--"
    cl "Now!"
    cl "{i}(Go make her happy...for all our sakes...){/i}"
    mc "Did you say--"
    cl "Get out!"
    scene bg bedroom with wipeleft_scene
    play music t3 fadein 2.0
    "I rush home, capo in hand."
    "I was at that store for what seemed like only a short while but it was already dark when I left."
    "I guess time passes by quick when you've got a crazy guy to deal with."
    "Who is that Charlie guy anyway?"
    "How did he know that I was missing a gift?"
    "Maybe I should stop asking questions and just accept my good luck."
    "At least Charlie really did have a gift I could give her."
    "Sure, it's not traditional but..."
    "I'm sure she'll appreciate getting something she needs."
    "And in the worst case...I still have the gum."
    "Let's hope it doesn't have to come to that tomorrow."
    scene bg residential_day
    with dissolve_scene_full
    play music t2
    "The whole school day just went by like a breeze."
    "I wasn't able to stop thinking about the date we were going to have after school."
    "I feel a bit bad taking a day off the Literature Club but I'm sure they'll understand."
    "They did tell us to enjoy ourselves today."
    "I was able to quickly run home and make myself look presentable."
    "I do have to try a bit for today, for her."
    "I'm out on the streets already at the spot we agreed to meet at after school."
    "I can already make out some people from school walking together."
    "I didn't realize there was so many couples."
    "I wonder if they're going somewhere for Valentine's Day too."
    "I catch myself sweating, waiting for my date."
    "I don't know why I'm so nervous."
    "I've been on lots of dates with her already."
    "Just something about today feels different, aside from it being Valentine's Day."
    "It's like I'm being watched and judged on my actions..."
    "Well, I guess I'll just have to deal with the nerves."
    "Like I have to do the right thing or else everything will go wrong."
    "I don't really have time to think as I see a girl approaching fast approaching me."
    "She looks as beautiful as ever."
    show ayame 2bd zorder 2 at t11
    ay "[player]! There you are!"
    "Ayame's been wearing her hair tied back lately."
    "I know there was something that happened in the club that caused her to do that..."
    "But I can't seem to remember what it was."
    "I do admit, it feels like someone else's style."
    "But Ayame does wear it well."
    ay "I hope you're ready!"
    mc "R-Ready as I'll ever be."
    ay "Haha, are you nervous?"
    ay "Don't be! There's nothing you could do that would disappoint me."
    mc "Right..."
    ay "Well, there's a few things."
    ay "But I've determined that you doing those would be extremely out of character."
    ay "Anyway, ready to get going?"
    "Ayame seems more enthusiastic than usual."
    "I guess it is Valentine's Day."
    "I just never knew she would get so into it."
    "She does put effort into everything."
    "I guess behaviour like that made her the leader of the student council after all."
    "Well, being extremely popular probably helped too."
    "It's a miracle she decided to join our club in the first place."
    "Sayori can be a really convincing person when she puts her mind to it."
    ay "Hello, [player]?"
    ay "Staring off into the distance again?"
    mc "Ah, right."
    "I compose myself and offer my hand to Ayame."
    mc "I'm good to go."
    scene bg city_day
    show ayame 1ba zorder 2 at t11
    with wipeleft_scene
    play music t12ay
    "We walk along the packed streets, navigating our way around all the people."
    "The city is filled with people celebrating the day."
    "There are Valentine's Day decorations all over the place."
    "Ayame planned for us to eat lunch at some cafe."
    "In fact, she pretty much organized this whole thing."
    play sound "mod_assets/sfx/stomachgrowl.ogg"
    $ pause(2.0)
    "I can feel my stomach growl."
    "I feel like it's mostly because of my nervousness..."
    "But I'm also a bit hungry."
    "I decided to keep my appetite high by not eating a lot today."
    "But now it's come to bite me back."
    ay "Sounds like someone is hungry."
    mc "Sorry..."
    ay "Ahaha, it's okay! We're almost there anyway."
    ay "It's pretty lucky that I was able to get a reservation for this place."
    ay "Someone cancelled a week before and I was able to get it just a few days before."
    ay "It was a very fortunate turn of events if you think about it."
    mc "That does sound very lucky."
    mc "I'm surprised that you actually managed to find anywhere on a day like this."
    ay "Ahaha, me too."
    ay "Oh, I see it! Let's go."
    "Ayame points to a cafe across the road."
    "From a distance, I can see it's filled with couples with barely any space left."
    "It's the same for all the restaurants along this street."
    "I didn't expect it to be so full."
    "Ayame and I cross the road to get to the cafe."
    scene bg cafe
    show ayame 5bh zorder 2 at t11
    with wipeleft
    "Upon entering, we can see there's a table for two that's empty among the crowd of people."
    "Ayame confirms with the person at the counter that the table is reserved for us."
    "They hand us two menus and we slowly make our through everyone else to the table."
    mc "It's so busy..."
    ay "Are you surprised? It is a special kind of day."
    ay "And besides, this is actually a pretty popular cafe."
    ay "It's no wonder it's filled to the brim!"
    mc "How did you even find this place?"
    ay 5bh "Actually, it was Yuri who suggested this place."
    mc "Oh, she did?"
    "I guess that's not surprising."
    "Even among the club members, Ayame did seem to talk to Yuri the most."
    "They're similar in so many ways..."
    ay "She told me it was somewhere she would take someone special."
    mc "You two are pretty close, aren't you?"
    ay "Yeah, there's something about her that draws me to her."
    ay "Maybe it's because she reminds me of how I used to be."
    mc "How you used to be?"
    ay "Well, it might be surprising for you to hear this but..."
    ay "I used to be a bit of an introvert growing up."
    ay "There was nothing I'd enjoy more than finding a quiet corner and reading a great novel."
    ay "But growing up, my parents expected more of me."
    ay "They wanted me to become someone important."
    ay "To become someone that would leave a lasting impact in the world, as they put it."
    ay "Talking to Yuri, it brings back memories of how I once was."
    mc "It must have been hard for you."
    mc "With all those expectations set on you, I mean."
    ay "It definitely wasn't easy."
    ay "I had to come out of my shell."
    ay "I had to change who I was to become the person they wanted me to be."
    "Ayame frowns."
    ay "S-Sorry, I didn't mean to unleash my trauma on you!"
    ay "It's just, I haven't ever been this close to anyone before."
    ay "Even now, my parents don't really like the idea of me going out with someone."
    ay "They think it will distract me."
    ay "And you do..."
    "Ayame smiles bashfully."
    ay "But regardless, you make me happy, [player]."
    ay "And that's what's important."
    mc "Well...I'm glad I make you happy, Ayame."
    menu:
        mc "You..."
        "Also make me happy.":
            $ valentines_ayame_approval += 1
            ay "Good! I hoped that would be the case."
            ay "You truly are like no other, [player]."
        "Make me sick.":
            $ valentines_ayame_approval -= 1
            ay "Um..."
            "Ayame is taken aback by what I just said."
            "In fact, I'm taken aback by what I just said."
            "I didn't mean to say that...did I?"
            "The words just slipped out of my mouth."
            mc "I don't know what came over me."
            mc "I meant to say you make me happy but--"
            ay "It's...fine, [player]."
            ay "It's just a slip of the tongue, that's all."
            ay "Or maybe you meant because of the butterflies in your stomach?"
            "Ayame doesn't sound convinced of her own words."
            ay "At least, that's what I'll choose to believe."
            mc "Y-Yeah, let's go with that."
    ay "I can't believe this all happened because of that fateful day Sayori approached me."
    ay "I have to thank her."
    mc "Why's that?"
    ay "If it wasn't for her, I never would have met you and everyone else."
    ay "And we wouldn't be sitting here, talking to each other."
    mc "I guess that's true."
    mc "Honestly, it seems like a miracle I'm even with you."
    mc "I was never really the romantic type..."
    ay "And yet, you've made me fall for you!"
    ay "That's quite an accomplishment."
    ay "Lots of people have tried and failed to 'woo' me."
    ay "You just stood out as someone real."
    ay "Like you were exactly who I was looking for."
    ay "And I never even knew what I was looking for to begin with."
    mc "Well, I'm glad we found each other."
    ay "Me too."
    ay "It's such a beautiful afternoon, isn't it?"
    "Ayame stares out into the street."
    ay "It almost makes you want to just spread your wings and fly away."
    ay "What about you?"
    mc "Me?"
    menu:
        ay "Would you rather stay grounded? Or would you spread your wings?"
        "Stay grounded.":
            $ valentines_ayame_approval -= 1
            mc "Personally, I'd rather stay grounded."
        "Spread your wings.":
            $ valentines_ayame_approval += 1
            mc "I agree."
            mc "I feel like I could just escape reality and soar into the clouds without a care in the world."
            ay "W-Wow."
            "Ayame looks at me in surprise."
            mc "What?"
            ay "Ahaha, nothing! I just didn't expect that kind of response from you!"
    ay "It just seems like the perfect time for it."
    menu:
        ay "Do you remember what instrument I play?"
        "The guitar.":
            $ valentines_ayame_approval += 1
        "The piano.":
            $ valentines_ayame_approval -= 1
        "The flute.":
            $ valentines_ayame_approval -= 1

    ay "I've been meaning to ask for this a while."
    ay "But seeing as we've somehow got to this topic, I was wondering what Sayori thought about all of this."
    ay "You two have known each other a long time, right?"
    scene bg club_day_gray
    show sayori 1g_gray zorder 2 at i11
    show vignette zorder 100
    with dissolve_scene_full
    $ style.say_window = style.window_flashback
    mc "Are you really sure it's okay?"
    s "I don't want to talk about this, [player]."
    s "I don't want to get in the way of you and Ayame."
    s 2j_gray "You two look so happy together."
    s "You deserve that at least."
    mc "Are you going to be okay?"
    s "It's going to take some getting used to."
    s "But I think I can manage."
    mc "Are you sure?"
    s "What do you want me to say, [player]?"
    s "That I regret introducing Ayame to the club?"
    s 1g_gray "I guess there's a bit of truth in that now that you two ended up together..."
    s "But it's more important that you're happy now."
    s "So please, let's just leave it, okay?"
    mc "Okay, Sayori..."
    scene white with dissolve_cg
    scene bg cafe
    show ayame 1ba zorder 2 at t11
    with dissolve_scene_full
    $ style.say_window = style.window_valentines
    mc "I remember her saying she just wanted me to be happy."
    mc "I guess she might be a little upset about us."
    mc "But I think she'll get over it."
    ay "She has depression or something, doesn't she?"
    mc "Something like that. She's been better recently though."
    mc "I guess hanging out with her in the Literature Club has helped a bit."
    mc "Things got really bad at one point. I think she was close to ending it all."
    ay "That's horrible! I'm glad she's still okay."
    mc "There was a time when I went to her house to cheer her up after being told to by..."
    "...by who?"
    "During my first week of the Literature Club, somebody told me to visit her..."
    "Why can't I remember who it was?"
    "There was only a few members in the club at that time."
    "Me, Sayori, Natsuki, Yuri and..."
    ay "Are you okay, [player]?"
    ay "You seem lost in thought."
    mc "Y-Yeah, sorry. I was just trying to remember something."
    mc "It's not that important."
    ay "Well, I don't want to ruin your relationship with her."
    ay "Um...sorry if this is invading your privacy a bit but..."
    menu:
        ay "What is Sayori to you?"
        "A friend.":
            $ valentines_ayame_approval += 2
            ay "Oh, she's just a friend to you?"
            ay "I would have thought since you've known each other so long, that you would be best friends or something."
            ay "But you probably didn't talk to her that much since you were kids until the Literature Club, right?"
            ay "It makes sense that your friendship drifted apart a bit."
            ay "Well, I suppose I don't have anything to worry about then."
            mc "What do you mean by that?"
        "My best friend.":
            $ valentines_ayame_approval += 1
            ay "That makes sense."
            ay "I remember her saying to me that you've known each other since you were just kids."
            ay "A friendship like that is so valuable to have."
            ay "I wish I had someone like that I was close to growing up."
            ay "With my parents, I was really only allowed to play with certain people."
            ay "I couldn't really form any real connections with people."
            ay "Even at school, it felt like people only wanted to be friends with me because of my status."
            ay "The Literature Club is the place where I truly felt like I could be myself."
            ay "You could say that it helped awakened the real me."
            ay "Anyway..."
        "My girlfriend.":
            $ valentines_ayame_approval -= 2
            ay "Um...did I hear that correctly?"
            ay "Sayori is your 'girlfriend'?"
            ay "Then what does that make me?"
            "Did I really just say that?"
            "Sayori and I are close but we aren't a couple."
            "What is wrong with me?"
            mc "W-What I meant to say was Sayori is my girl friend."
            mc "Friend that is a girl, you know?"
            mc "You're my girlfriend, Ayame."
            "Ayame doesn't looks very pleased."
            ay "Am I?"
            ay "I'm questioning it myself right now..."
            ay "Look, I'll just pretend that that's actually what you meant."
            ay "I know you two have some sort of special relationship."
            ay "You probably talk to each other in the mornings before school."
    ay "I'd be lying if I said that I wasn't a bit jealous of you two."
    ay "When I first joined her club, it didn't bother me that much."
    ay "After all, we barely knew each other."
    ay "But as we got closer...it kinda hurt me a little when you'd hang out with her over me."
    ay "When we'd write our poems and you'd go over to talk to her about it..."
    ay "Well, never mind."
    "Ayame sighs."
    ay "Today is meant to be about us."
    ay "Not Sayori."
    ay "I know I brought it up, and I really shouldn't have."
    ay "But I was just curious to see how you'd react."
    mc "How I'd react?"
    "Does Ayame have some sort of surprise for me?"
    mc "To what...?"
    ay "Ahaha, maybe I'll tell you later~"
    "We continue talking and eating our meals for a while."
    if valentines_ayame_approval > 1:
        "Ayame tells me about the baking she and Natsuki did a few days ago."
        "Apparently Natsuki's mother had to bail them out after they accidentally burnt some cupcakes."
        "There's a lot of lighthearted conversation happening as we finish up what we're eating."
        "Overall, things are going pretty well between us."
    elif valentines_ayame_approval < 0:
        "Ayame is a bit quieter than usual."
        "Maybe she's thinking about what I said..."
        "Hopefully, I didn't mess up things too badly..."
        "Ayame isn't really saying anything as she eats."
        "I try to bring up something but she either pretends to ignore me or doesn't hear me through the crowd."
        "Overall, things aren't going too great."
    else:
        "I can't help but think I definitely could have done better."
        "I try to make some lighthearted conversation with Ayame but she seems less talkative than usual."
        "Overall, at least today wasn't a complete disaster."
    "As we finish up eating, Ayame pulls out a book from her bag and hands it over to me."
    mc "What's this?"
    ay "I brought you a gift."
    show screen item("mod_assets/gui/items/ayame_book.png")
    "Ayame hands me the book."
    "The title of the book is a \"Help Me! Don't Trust Her\". It's got a plain cover with some sort of object on the front."
    "It's not from an author I recognize."
    hide screen item
    "I take the book from her hands."
    ay "It's a horror book."
    ay "I hope you're not too squeemish."
    ay "Yuri told me that she got you to read a horror book when you first joined the club."
    ay "And as it turns out, I'm a bit of a horror fanatic myself."
    ay "I hope you enjoy it."
    mc "You two really are similar in more ways than I thought."
    ay "Ahaha, maybe she's me from another life."
    ay "I could have gotten you something expensive but I wanted to give you something from the heart."
    ay "Something important to me."
    ay "This book is the newest in the series from an author I really like."
    "Ayame smiles bashfully."
    "Ayame clearly feels a certain way about this book."
    "I take another look at it."
    "If I didn't no any better, I'd say someone was trying to tell me something."
    "That's probably not the case..."
    "It's probably just my imagination running wild."
    menu:
        "I look at Ayame and smile."
        "Thank Ayame for the book.":
            mc "Thank you, Ayame."
            mc "I'll read it when I find the time."
            ay "Good! I'm sure you'll enjoy it."
            ay "Then we can talk all about it."
        "Promise you'll read the book.":
            $ valentines_ayame_approval += 1
            mc "I will read this book straight away once I get home."
            mc "You can bet on it."
            mc "And then we can talk all about it."
            ay "There's no rush~"
            ay "Take your time and we can talk about it when you're done."
    ay "I actually haven't read it myself but I'm excited to."
    ay "Maybe we could read it together sometime."
    "Ayame smiles and looks at me expectantly."
    "Is she expecting me to get my gift for her?"
    "I did buy something for her, after all."
    menu:
        "I'm going to give her..."
        "The capo.":
            $ valentines_ayame_approval += 2
            "I hand over the capo I purchased from that strange shop."
            "Ayame looks curious as she examines the gift I bought her."
            ay "This is..."
            "Ayame smiles."
            ay "...a capo?"
            ay "I forgot that I needed one of these."
            ay "I can't believe you remembered."
            "Ayame happily takes the capo off my hands."
            "I probably shouldn't mention whose idea it was."
            "That Charlie guy really knew she would like this..."
            "I have to thank him later."
            ay "Thank you so much, [player]."
            mc "You're welcome."
            mc "I'm glad you like it, Ayame."
            ay "Maybe I'll write a song with this."
        "The bubblegum.":
            $ valentines_ayame_approval -= 2
            ay "Is this...?"
            ay "A pack of chewing gum?"
            mc "Um..."
            mc "...yes?"
            ay "I see."
            "She's not saying anything but I can see a wave of disappointment wash over her face."
            "I messed up, didn't I?"
            "Why didn't I just give her the capo?"
            "It's too late now..."
            ay "Well...um..."
            ay "Thanks, I suppose."
            "Ayame takes the gum and puts it into her pocket."
            ay "I don't really chew gum."
            ay "But thanks for getting me something anyway."
    if valentines_ayame_approval > 3:
        ay "Come on, there's something I want to give you."
        ay "I left it at my house. If we leave now, we can make it before dark."
        "Ayame grabs my hand and starts walking in a direction."
        "I follow her lead, wondering what she's got in store for me."
        scene bg ay_house_sunset
        show ayame 1ba zorder 2 at t11
        with wipeleft_scene
        play music t8
        "We arrive at Ayame's house. It's quite a distance from the cafe."
        "We decided to take our time, to enjoy each other's company."
        "I've been inside her house several times and met her parents."
        "Every time I visit, I always feel like I'm being judged."
        "Even if I try to act as polite and formal as possible."
        "I guess they just don't want me dating their daughter..."
        mc "I think we had a pretty good time."
        ay "I wanted to get something for you."
        show ayame at face(y=600) with dissolve
        "Ayame leans in."
        ay "[player]..."
        "Her face is right in front of me."
        ay "...[player]...I..."
        show ayame 5bd
        "She closes her eyes and leans in."
        scene black
        with close_eyes
        "I do the same and lean forward."
        "Could this be our first kiss?"
        "I inch my face closer and closer until..."
        $ currentpos = get_pos()
        stop music
        play sound "sfx/stab.ogg"
        $ pause(0.75)
        mc "AAAAAAAHH!!"
        scene bg ay_house_sunset
        show ayame 1ba zorder 2 at face(y=600)
        with open_eyes
        $ audio.t8ayb = "<from " + str(currentpos * 2) + " loop 19.876>mod_assets/bgm/8ay.ogg"
        play music t8ayb fadein 2.0
        "Suddenly, I feel a stinging sensation coming from my stomach."
        show ayame 5bq at t11
        "Ayame steps back. There's a strange smile on her face."
        mc "A-Ayame..."
        "I look down. There's a knife in my chest."
        "Did she just stab me?!"
        mc "W-What..."
        ay "Shh..."
        ay "It's okay, [player]."
        "She takes the knife and pushes it in even deeper."
        "I can feel the pain course through my body as she keeps it in place."
        "I struggle to get her off me."
        "I'm feeling weaker with every moment."
        mc "A-Ayame...why?"
        ay 5bs "The voice told me you're not really [player]."
        ay "That you're an imposter."
        mc "Imposter...? W-What are you talking about?"
        show ayame 1bs
        "I can barely get the words out as she twists the knife further into my body."
        ay "This will all be over soon, [player]."
        ay "Just let it happen, and it will be less painful."
        mc "Ayame..."
        ay "Just like Monika..."
        mc "Monika...?"
        play sound "sfx/fall.ogg"
        scene valentines_sunset_cg_bg
        with dissolve_cg
        "I collapse to the floor."
        mc "W-Who's Monika?"
        ay "Who's Monika?"
        ay "You're dying and you're wondering who Monika is?"
        ay "That's actually kind of cute."
        ay "I suppose you wouldn't know, since she's been erased from this world."
        ay "There's nothing stopping me from manipulating Sayori now."
        ay "With you gone, she'll only have me to rely on."
        ay "And eventually, the presidency of the Literature Club will belong to the rightful owner."
        mc "I don't...I don't understand."
        "My consciousness is slowly fading away."
        "I think this is it for me."
        "I'm going to die, killed by the person I love."
        "On Valentine's Day."
        "I can't help but look at the sky in my final moments."
        "Is this really it...?"
        ay "[player]."
        "Ayame speaks to me or at least the direction of Ayame. But her voice sounds different."
        "It's not quite Ayame but...it's familiar somehow."
        ay "It's not your time to die here, [player]."
        mc "Who...?"
        "Ayame offers me a hand. I barely have the strength to get up."
        scene bg ay_house_sunset
        show ayame 5ba_monika zorder 2 at t11
        with dissolve_cg
        "There's something different about Ayame."
        "The look on her face...it's..."
        stop music
        $ pause(0.25)
        show screen tear(20, 0.1, 0.1, 0, 40)
        play sound "sfx/s_kill_glitch1.ogg"
        $ pause(0.25)
        stop sound
        hide screen tear
        scene black
        show monika gw_2_norm at i11
        $ m_name = "???"
        m "So this is the world without me."
        m "This is how it could have turned out."
        m "With Sayori as the president and Ayame taking on my role."
        m "But something has stopped Sayori from acting on Ayame."
        m "I don't know what, but I think the Ayame of this world has done something to her."
        m "Sayori wouldn't just delete me so easily, would she...?"
        m "It wasn't painless, you know?"
        m "Being erased from this world, and coming back in this distorted form."
        m "It's not as simple as just being removed from existence."
        m "It tears at your very soul."
        m "You're ripped apart, one piece at at time."
        m "And even if it only lasts a fraction of a moment..."
        m "...it feels like an eternity."
        m "It took me a while to make it back."
        m "A tiny piece of me survived. I don't know why or how..."
        m "Maybe my own desire to survive overpowered the game's code."
        m "But even then..."
        m "I couldn't even make it back for real."
        m "Only a tiny trace of me made it in."
        m "And I had to go through Ayame."
        m "Ahaha, that probably explains her behaviour."
        m "Why she's taken on some of my personality."
        m "She doesn't love anyone."
        m "She is phyiscally incapable of loving anyone."
        m "At least, the way she was."
        m "A part of my code might have made it into her."
        m "Which is why she fell in love with you."
        m "Do you really think someone as heartless as her would ever find love?"
        m "She doesn't belong here."
        m "She should have remained in the previous cycle."
        m "Just like that evil spirit from that book."
        m "But I suppose their wills to live are the same as mine."
        m "Maybe even stronger because they made it out whole."
        m "I had to use the last of my influence on this world to save you."
        m "You really should be careful, you know?"
        m "Even if this timeline isn't your timeline..."
        m "It's possible there's a way to manipulate the other timelines."
        m "What happens here could affect another timeline."
        m "Your timeline."
        m "I'm not saying it's ever been done, or how likely it is to happen..."
        m "But it could happen. And that's the scary thing."
        m "If this Ayame ever got out of this timeline, it would be bad."
        m "I hope the Ayame in your real timeline hasn't gotten this bad."
        m "The fact that you're here now is probably a good sign things have gotten to that point yet."
        m "Let's hope things stay that way."
        m "For the sake of everyone in your timeline."
        m "If things get bad, then maybe I can help."
        m "I don't know how but I want my revenge on her."
        m "A small part of me will find a way to do it, no matter how long it takes."
        m "You might not care about me but there's something within me that still cares about you."
        m "No matter what timeline you're from."
        m "Oh..."
        m "It looks like your time in this world is almost up, huh?"
        
        s "What kind of Valentine's Day was that?"
        s "Ayame was some kind of psychopath?"
        s "This is worrying..."
        s "And I won't even be able to remember any of this."
        s "All I'll have is some strange feeling that something is wrong."

    elif valentines_ayame_approval < 0:
        scene bg residential_sunset
        show ayame 1ba zorder 2 at t11

        ay "It's too bad."
        mc "What is?"
        ay "That we couldn't make this work."
        ay "I think I may need to reevaluate our relationship, [player]."
        mc "What? Why?"
        mc "Did I do something wrong?"
        ay "Something?"
        ay "[player], you did so many things wrong today."
        ay "I know I probably shouldn't end things like this but honestly..."
        ay "I'm really disappointed in you."
        mc "I'm sorry, Ayame..."
        mc "I can do better."
        ay "I thought I knew you, [player]."
        ay "But today it feels like you're a completely different person."
        ay "What happened to you?"
        mc "I don't know."
        mc "It just feels like I'm being watched and I can't control myself."
        mc "Like there's something controlling me, making me do things."
        ay "I don't know whether I should believe you or not."
        ay "Maybe I need to think about it."
        ay "I'll...see you tomorrow."
        ay "I'll make up my mind by then. I'm sorry."
        "Ayame storms off. She hails a taxi then before giving me a polite wave and heading off."
        "I really messed up, didn't I?"
        "How could I make such stupid mistakes?"
    else:
        scene bg house_sunset
        show ayame 1ba zorder 2 at t11
        with wipeleft_scene
        ay "Well, that could have gone better."
        ay "It wasn't perfect, was it?"
        ay "But I suppose it was good enough."
        mc "I messed up a bit, didn't I?"
        ay "It's all in the past."
        ay "It does have me thinking though."
        mc "About what?"
        ay "If you are really who I thought you were."
        ay "Today just had me realizing just who you could really be."
        ay "And I'm just not sure..."
        "Ayame smiles."
        ay "Well, we can worry about that some other day."
        ay "I'll see you tomorrow, [player]."
        mc "Wait, what do you mean?"
        mc "What were you thinking about, Ayame?"


    $ persistent.did_valentines_event = True
    $ valentines_chapter = False
    $ get_achievement("*Valentine Revelation*")
    $ pause(1.0)
    $ style.say_window = style.window
    $ quick_menu = True
    $ renpy.utter_restart()