# Seperate into two different files because ch016 was getting huge
label ch16_mainb:
    scene black
    stop music
    "Before I can even react, my whole vision turns dark."
    "I try to move my body but it's like I don't have one."
    "It's a very strange sensation."
    "I can't feel anything, all I have is my thoughts."
    "Is this the next world?"
    "Or was that portal a fake somehow?"
    "No...Ayame was so sure it wasn't."
    "Maybe I did something wrong?"
    "Ayame!"
    "Can she even hear me right now?"
    "I can't even tell if I'm saying this out loud or if it's all in my head."
    "I guess I'll just wait until I hear something..."
    "Any second now..."
    "Any...second..."
    "Maybe I have to do something."
    "I can't just float here and do nothing."
    "But what can I even do?"
    "I don't have a body. It's like I'm just my consciousness."
    "Like a dream..."
    "But if this is like a dream, then I can make it whatever I want it to be...right?"
    "That's it, that's the key."
    "I try to imagine arms and hands."
    "I can sense the feeling of my hands returning."
    "But they feel...different, somehow."
    "They're definitely my hands, they feel like they're not the same."
    "I'm getting sidetracked."
    "I need to get the rest of my body back."
    "One by one, my sense of feeling is coming back to me."
    "As my head comes back, I take a deep breath."
    "There's no air."
    "In my panic, I take another breath. There's still no air."
    "I'm suffocating! What do I do?!"
    "I was just fine before. Why is this happening now?!"
    "Think of air, [player]! Think of air!"
    "I gasp for air."
    "This time I can breath properly."
    "I hyperventilate for a few moments to calm myself down from what just happened."
    "Where the hell did we end up?"
    "There's just nothing here."
    "Do I have to come up with the others as well?"
    "Or do they have to do it themselves?"
    "What if I think about the wrong things and they end up messed up somehow?"
    "They won't be the same person..."
    "Just my perception of them."
    "I have to think. There must be something I can do."
    "Maybe some place for us to be at would be a good start."
    scene bg bedroom_gray
    "Okay...why is it all in black and white?"
    "Is this what this world is?"
    "Or was that because of me?"
    "I examine my hands and notice they're also just black and white."
    "At least it seems familiar."
    "Maybe this world is just another copy?"
    "Sayori wouldn't make it that easy, would she?"
    "Okay, I can do this."
    "I was alone before, I can regroup with them again."
    "How many times are we going to go through this to get to Sayori?"
    "We have to be getting closer."
    ay "We are getting closer."
    "Whoa! What the hell was that?"
    "It sounded like Ayame's voice."
    "But where is she...?"
    "Her voice sounds like it's coming from all directions."
    ay "Yes, hello. It's me."
    ay "I don't have a corporeal form here."
    ay "I guess it's just a side effect of this world."
    ay "You have to give me a form, [player]."
    ay "Something I can use to interact with the world."
    ay "Anything."
    mc "But how do I do that?"
    mc "Do I just think of you?"
    mc "Of what you look like?"
    ay "No. You don't have to do that."
    ay "If you looked at the mirror you could see how well that turned out."
    mc "...Huh?"
    ay "Let's just say you didn't exactly give yourself the best embodiment."
    ay "For me, just imagine something simple."
    ay "Something that I can easily embody and navigate through the world with."
    ay "I don't think we'll be here long, so anything will do."
    ay "After that, we can work out where to go next."
    mc "Okay, here goes nothing."
    ay "Remember, simple."
    ay "Nothing complicated. I wouldn't want to end up like you."
    mc "Got it..."
    "Something simple..."
    "I think I have something in mind."
    "I mean what could be more simple than that, right?"
    "Like Ayame said, we won't be here long."
    "Just something to get the job done..."
    "I think I've done it. But how is she going to embody it?"
    mc "Okay."
    ay "Are you serious?"
    mc "I couldn't think of a more simple thing."
    mc "It's enough, right?"
    ay "...I suppose."
    "Ayame doesn't seem satisfied with what I came up with."
    "But what else could I have done?"
    ay "It won't matter anyway."
    ay "Here goes nothing..."
    "Ayame's voice is gone."
    "For a little while, I'm left alone again."
    mc "Ayame, are you--"
    ay "Yeah...I'm here."
    "The figure I came up with suddenly begins to come to life."
    "I guess she figured it out."
    show ayame stick zorder 2 at t11
    ay "I can't believe you did this."
    "Ayame's voice seems to be coming from the thing I created now."
    "So I think that's a good sign."
    mc "You did say simple."
    mc "You can't possibly put all of the blame of this on me."
    ay "Whatever, let's just get this over with."
    if ch16_ay_companions == 4:
        ay "You need to do the same for the other two as well."
        mc "How come I can't hear their voices?"
        ay "I...don't know. It might be because I'm the only one you still have a link to."
        ay "We didn't exactly re-establish it."
        mc "So what do we do then?"
        ay "They should be around here somewhere, right?"
        ay "Try coming up with something for them to embody."
        ay "Maybe that'll work."
        ay "And maybe--"
        "Before Ayame can finish her sentence, I come up with two more things that mildly resemble Yuri and Natsuki."
        ay "...make it more sophisticated."
        ay "Never mind."
        mc "Well, what do we do now?"
        ay "We wait. Hopefully, they'll begin to move soon."
        ay "All they have to do is walk into it."
        ay "Or...float into it."
        mc "Then how did I start moving?"
        ay "I don't know. Maybe you created it where you were and did it automatically."
        mc "I guess so."
    elif ch16_ay_companions == 3:

    elif ch16_ay_companions == 2:

    elif ch16_ay_companions == 1:

    elif ch16_ay_companions == 0:

    return
