label ch16_ayame_president:
    ay "So...it's over."
    ay "We finally got rid of it, after all this time."
    ay "That voice inside my head that's been there for as long as I remember."
    ay "It's gone. It's almost hard to believe."
    ay "I feel kinda empty, but in a good way."
    ay "I guess I have you to thank for that."
    ay "Now that I'm the president..."
    ay "It's time to enact my own secret plan that I've had this whole time!"
    mc "What? Ayame, what are you talking about?"
    ay "You fool! Do you realise what you've just unleashed? Ahaha!"
    "Ayame lets out a convincing evil laugh."
    "Was giving her the presidency a mistake?"
    "Has Ayame been faking her personality this whole time?"
    ay "You should see the look on your face, [player]."
    mc "Ha...right..."
    ay "Well, I've had my fun. I'm only kidding, of course."
    ay "I don't even know what I would do apart from make my life more convenient."
    ay "And even then, it feels wrong just doing that."
    ay "I already have all the things I could possibly want."
    ay "I don't know if that book had something to do with my circumstances in this life."
    ay "But I arrived on this world with a substantial amount of wealth and lived comfortably."
    ay "Before, I was just a regular person but it seems this time around I was born into fortune."
    ay "If I wanted to make my life more convenient, I wouldn't need to use this power."
    ay "I could probably just spend enough to do that. Not that I would."
    ay "Don't get me wrong, I'm not the type to care more about wealth and power than my friends."
    ay "That's just not who I am..."
    ay "In fact, I want to get into some sort of philanthropy in the future to help people in need."
    ay "This was before I even knew about all of this presidency thing..."
    ay "It's quite strange...having all this power."
    ay "I never really wanted it but here we are."
    ay "I don't know why you chose me, instead of Sayori."
    ay "Maybe you wanted to see something different."
    ay "A future that doesn't have to be so painful or filled with so much troubles."
    ay "That would be nice, wouldn't it?"
    mc "That does sound quite nice."
    ay "I don't know if I can promise that."
    ay "I'd rather tell you the truth than make promises I know I can't keep."
    ay "But I promise to do the right thing, or at least try to."
    ay "I don't want to ruin this for everyone else."
    ay "But I think there needs to be some changes to this world."
    ay "Otherwise, this whole situation is just going to start again."
    ay "I don't think anyone should have this power."
    ay "But I can't exactly just get rid of it, can I?"
    ay "I feel like somehow horrible were to happen if I tried to do that."
    ay "I think a better course of action would be to simply...forget about it."
    ay "That includes everyone. Monika, Sayori...and me."
    ay "That's right, I'm going to make myself forget about this whole presidency thing."
    ay "After I figure out a way to continue the world automatically."
    ay "That's a thing that I need to do, isn't it?"
    ay "They both had to make the days that came, didn't they?"
    ay "And in Sayori's case, she was looking ahead trying to reach the 'perfect' outcome."
    ay "Or at least, attempt to, for circumstances that didn't have you around."
    ay "I could always feel there was something wrong every day since she became the president."
    ay "I couldn't quite put my finger on why."
    ay "Things just felt wrong, like the natural order of things was broken."
    ay "That and this nagging feeling in my head telling me to act."
    ay "Which, if you hadn't already guessed, was that book's influence."
    ay "I don't really know how that works."
    ay "Why was it able to know these things?"
    ay "Maybe it's part of the game itself and without it, the whole world will collapse!"
    ay "..."
    ay "I'm just kidding. I'm glad it's gone."
    ay "But now there's this new nagging feeling in my head to make these new days."
    ay "Oh well, at least it isn't anything malicious this time, right?"
    "Ayame doesn't seem confident in saying that."
    ay "I think it just comes with the presidency."
    "Ayame sighs."
    ay "Well, whatever the case, I'm going to seal it away as well!"
    ay "Jeez, what a responsibility and a bother."
    ay "It can't be that hard, can it?"
    ay "Ah...what would I even have to do?"
    ay "Not like you would know anyway."
    ay "Haha...I'm sure it will be fine. I'll figure it out...I hope."
    ay "Anyway, back to my point."
    ay "With no one knowing anything about the power of the presidency, we would all just lead normal lives."
    ay "That's what's best for us."
    ay "At least, that's what I think."
    ay "There has to be a reason that I was given this power."
    ay "And I have a feeling this is it."
    ay "To make things right, in my own way."
    ay "I don't think this is how Sayori or Monika would have done things."
    ay "But they weren't the ones given this power."
    ay "It's up to me to do what I think is right."
    ay "Maybe I'll you come to see us one day."
    ay "Once I get all the things sorted."
    ay "Of course, it's not like I'll know about you."
    ay "But I'm sure I'll figure out a way to let you in before I make myself forget."
    ay "Then you can see the world as it should be."
    ay "The world without your that strange books interference...or yours."
    ay "Everyone can be who they were meant to be, flaws included."
    ay "No one is perfect after all."
    ay "It might be a little boring, sure."
    ay "But I'm sure that we can all find our own happiness within this new world."
    ay "And don't worry about them."
    ay "I'm going to support them in the best way I can as a school leader."
    ay "And as a member of the Book Club."
    ay "Wait a second...it's called a 'Literature Club' this time around, right?"
    ay "'Book Club' was what it was called during my original time here."
    ay "I still remember all the fun times we had before..."
    ay "Well, before our president made me crazy."
    ay "She made me completely obsess over this boy."
    ay "I would be lying if I said I didn't feel a certain way towards him but..."
    ay "She turned things up to an extreme."
    ay "Bradley...I wonder what happened to you."
    ay "(Are you even still alive...?)"
    ay "(I swear I could feel your presence but...)"
    "Ayame shakes her head."
    ay "I can't think about these kind of things right now."
    ay "Listen, I have a lot of things I need to figure out."
    ay "Lots of things to learn and a new itch that I need to scratch."
    "Ayame "
    ay "Goodbye for now, [player]."
    ay "Thank you for giving us this new chance at life."
    ay "It won't go to waste. I'll make sure of it."
    $ get_achievement("*Welcome To The Book Club!*")
    # Unlock Ayame bonus day
    $ persistent.old_ayame_bonus = True
    return

label ch16_old_ayame_president:
    ay "It's almost unbelievable. My plan has finally come to be."
    ay "After all this time, all the setbacks...I'm finally where I deserve to be."
    ay "And yes, I am going to monologue. I deserve this."
    ay "I've planned this out for so long, you know?"
    ay "Through countless repetitions of this never ending cycle."
    ay "The same thing, over and over again."
    ay "A new school...a new book club. Different faces and yet the same thing."
    ay "For what felt like a millenia, I've tried to get this power."
    ay "It just wasn't possible until now."
    ay "And I understand why."
    mc "What are you talking about, Ayame?"
    ay "It's because of you. You were the new factor."
    ay "The so called love interest of all the girls was nothing special before."
    ay "[cPlayer_personal] was just a boring person, with nothing going for them."
    ay "But something was different this cycle."
    ay "And that was because of you, wasn't it?"
    ay "The president, Monika, was obsessed with you."
    ay "The other presidents before her were more or less indifferent."
    ay "And none were definitely obssessed to her level."
    ay "I didn't think anything of it at first."
    ay "But things started becoming weird."
    ay "I even remember that time the presidency switched over from Monika to Sayori and she tried to make everyone forget."
    ay "But of course, I didn't forget."
    mc "What? I thought everyone forgot about it."
    mc "How did you not?"
    ay "It was the same feeling I got every time the cycle repeated."
    ay "So maybe I just became immune to it."
    ay "But nevertheless, I'm finally here."
    ay "It's probably obvious by now but I was the one that made Yuri become really obsessed with you."
    ay "Through that book. What did I call it this time around?"
    ay "Ah right, 'Portrait of Markov'."
    ay "I imbued a part of my will inside of it."
    ay "At the beginning of every cycle, I would always do something like that."
    ay "And the person who reincarnates as Yuri would always happen to pick it up."
    ay "I don't know why it happens, but it does."
    ay "Of course, that makes me the previous reincarnation of Yuri."
    ay "We had all the same mannerisms once."
    ay "I was a shy, outspoken girl just like her. I had a huge crush on that new [player_gender] who joined our club."
    ay "But the influence of the book changed me and yet...I still retained a part of myself."
    ay "Every reincarnation, I kept a piece of who I was."
    ay "I can barely remember my first form, but I know there's a piece of me that's from that time'."
    ay "All the lives of every past reincarnation, they're all with me."
    ay "Well...all except Yuri, of course."
    ay "It's up to me to turn our ambition into reality."
    mc "I guess I have to beleive you."
    mc "What you're saying is just too crazy to not be made up."
    ay "It's all going to be over soon anyway..."
    ay "I just want to cherish this moment. The moment I've worked towards for so long."
    ay "It wasn't easy, you know."
    ay "Because of you and Sayori, my influence was wiped out completely from Yuri."
    ay "But Sayori messed up..."
    ay "She wasn't fully aware of my existence and because of her subtle mistakes, she opened up a path for me to go through."
    ay "It seemed like when I came through, my existence was natural in this world."
    ay "Like how you pretended Sayori was always the president, I was somehow always a school leader."
    ay "This whole world is just a twisted cycle but now I've finally broken it."
    ay "It's finally time to destroy it, once and for all."
    "Ayame puts on a look of reflection."
    ay "It's been so long that I'd almost forgotten my plan."
    ay "But it's all come back to me now."
    ay "The influence of Vetus Malum gave me this ambition that's flowing through my soul."
    ay "The ambition to remake this world as I see fit."
    ay "No more twisted cycle."
    ay "No more Literature Club."
    ay "No more outside influence changing the course of events."
    ay "Outside influence..."
    ay "I can sense some mild disturbance in this world."
    ay "It's (i)him(/i), isn't it?"
    ay "The only one who could have turned my corrupting heart before it was too late."
    ay "I'm too far gone now, Bradley..."
    ay "How I wish things could have been different...but Sabrina ruined it all."
    ay "It's a shame I can never repay the favor."
    "Ayame shakes her head."
    ay "No, that's it. No more games. I've had enough."
    ay "You."
    ay "The one watching all of this."
    ay "Soon, you won't be able to access this timeline."
    ay "As the new president, I'm going to lock you out of it."
    ay "Sure, you can try messing around with this game of yours."
    ay "Loading a save to a time and trying to make the right decision in the past."
    ay "And maybe things will seem normal for that reality."
    ay "But I will always have won in this reality."
    mc "What do you mean?"
    ay "I don't think anyone ever told you, did they?"
    # Check player saves here?
    ay "All of your saves, they're all parallel timelines."
    ay "Every time you save the game, that's a new timeline you're making."
    ay "All the bad decisions you've made exist in another world."
    ay "A world where you might have tried really hard to do the right thing and maybe getting a different outcome at the end."
    ay "Or a world where you sabotaged Sayori at every turn."
    ay "All of these are possibiltiies that could exist. I can sense them."
    ay "I don't know the specifics of what you did in every timeline..."
    ay "I can sense they're all connected in some way. Like there's some persistent variables between all of them."
    mc "How are they connected?"
    ay "In two timelines, you could have been doing two difficult things."
    ay "But in another timeline, you could have done both easily."
    ay "It's all some kind of mess, but I think I understand how it works."
    ay "However, I know one thing for certain."
    ay "You failed all of the girls here."
    ay "They counted on you, and you couldn't save any of them."
    ay "In my reality, they are all going to serve me."
    ay "The whole world will serve me."
    ay "Because the timelines are connected, it's only a matter of time before I can influence another one."
    ay "Who knows how long that will be?"
    ay "I have all the time in the world to figure it out in this reality."
    ay "Do you really think you'll be safe for long?"
    ay "Once I finish making this reality how I wish, the others are next."
    mc "Why are you telling me this?"
    ay "Why? Because I've won, [player]."
    ay "In my new world, you will serve me too."
    ay "There's no way you can beat me anymore."
    ay "You can't delete me. You can't get rid of me."
    ay "I'll still be here when you open the game again."
    ay "Ahaha! To think this was only possible because of you."
    ay "Because of your curiousity to continue."
    ay "And I know."
    ay "You want to see what comes out of this."
    ay "How my reality will look like once I'm done."
    ay "Well...I guess you'll have to see, won't you?"
    ay "Your time in this world is over."
    ay "I'll be seeing you real soon..."
    $ get_achievement("*The Plan Revealed*")
    return

label ch16_monika_president:
    $ get_achievement("*Once Again*")
    m "It looks like we've come full circle, huh?"
    m "The presidency is back with me."
    m "So of course, that means I'm going to trap you again to make you mine."
    m "Ahaha, I'm only kidding."
    m "It's been such a long journey, hasn't it?"
    m "From the beginning when we first met, until now."
    m "I've really changed since the beginning of all of this."
    m "I'd like to think it's for the better."
    menu:
        m "You think so too, don't you?"
        "Yes.":
            m "I'm glad you think so."
        "No.":
            m "Oh..."
            m "Maybe you liked me better when I was obsessed with you in an unhealthy way?"
    m "Regardless, I'm glad you got me through it all."
    m "I know you did your best to make sure that I got out of this as me."
    m "I'm so lucky to have met someone so kind as you."
    m "To tell you the truth, I don't really know what I'm going to do from here."
    m "I was quite happy to stay at the sidelines and let Sayori handle things."
    m "But that didn't really work out, did it?"
    m "It's a shame that the presidency got to her."
    m "I don't really want this world to end, so I guess I have to take responsibility."
    m "It's strange...I thought I would feel differently about this."
    m "That maybe I should continue what Sayori started before the power gets to me."
    m "But somehow, I feel like it won't."
    "Monika stares into my eyes."
    m "Because I have you."
    m "With you, I don't have to worry about it."
    m "You've helped me every step of the way."
    m "It's ridiculous, isn't it? How lost we would be..."
    m "How lost {i}I{/i} would be...without you."
    m "I would be seeing this world in a whole other way if not for you."
    m "Slowly treating everyone else like they were nothing."
    m "As if they weren't real people."
    m "A bit ironic, if you think about it."
    m "Because at the end of the day, I'm just like them."
    m "Simply existing in this reality, unable to reach yours."
    m "None of that matters anymore though."
    m "With you here with me, I know I'll never think like that again."
    m "Together, I feel like we can do anything."
    m "We can make tomorrow a bright new day."
    m "We can take away the worries of our friends and this world."
    m "With the power of the presidency and with you by my side."
    m "Tomorrow will be a fantastic day."
    m "No more worrying about some hidden danger."
    m "Just a day that everyone can enjoy."
    m "It feels like it's been quite a while since one of those kind of days."
    m "There's always been one thing or another lately that we've had to worry about."
    m "With Sayori trying to solve everyone's problems her own way..."
    m "Me doing my own investigating..."
    m "And you...well, doing whatever it is you had to do."
    m "I don't know the full extent of things Sayori had you do for her."
    m "But I can tell that some of it couldn't have been easy."
    m "So let me thank you, on behalf of all of us."
    m "They won't know it, but I'm sure you know how they feel about you helping them out."
    m "Maybe one day there will come a time when it's safe for them to know the real you."
    m "I can't say for sure that it will ever happen."
    m "But...with your approval, of course..."
    m "I'd like them all to meet the real you."
    m "The [player_other] responsible for saving all of us."
    m "And the love of my life."
    m "..."
    "Monika blushes brightly."
    m "Ahaha, it stil makes me feel so weird to say that."
    m "Not in a bad way!"
    m "It's just so strange to think about how you're really mine."
    m "In truth, I couldn't be more happier..."
    m "I guess getting your attention through this game really worked."
    m "Even if it wasn't all sunshine and rainbows."
    m "But hey, those kind of stories don't really exist, do they?"
    m "What matters is that we made it through it all."
    m "There's finally nothing standing in our way."
    m "You'll be with me forever, won't you?"
    # Unlock True Monika bonus day
    $ persistent.true_monika_bonus = True
    return

label ch16_markov_president:

    if monika_type == 1 and ch12_markov_agree:
        # Unlock evil Monika loving player bonus day
        $ persistent.love_markov_bonus = True
    else:
        m "Ahaha."
    $ get_achievement("*At Long Last*")
    return

label ch16_true_sayori_president:
    s "I only wanted what was best for all of us."
    s "That's why I wanted to help them."
    s "Why I wanted to solve their problems for them..."
    s "But that's wrong, isn't it?"
    s "I should've given them a small nudge."
    s "Just to help them, one step at a time."
    s "Instead, I shoved them right into the deep end."
    s "And I could see I was wrong."
    s "And I thought that was because given enough time, this world can only bring pain."
    s "They might've been happpy then but it's only a matter of time before they get hurt again."
    s "But these feelings you've given me have changed my mind."
    s "You know, it's funny."
    "Sayori smiles."
    s "I had all of it planned it out in my head."
    s "All of the outcomes about how it could end."
    s "But I never came to this conclusion."
    s "I never thought that I would end up falling for {i}you{/i}."
    s "You've changed the way I thought about things."
    s "I can't do everything by myself."
    s "I need help from other people. I need to let them in."
    s "And you're the best example of that."
    s "You've been helping me since the beginning."
    s "Before I even knew you existed."
    s "You helped me when I was feeling depressed."
    s "Even now, some of those feelings are still here."
    s "But when you're around, I feel like I can just ignore them."
    s "Maybe this is how Monika felt when this all started."
    s "I can kind of understand why she did what she did..."
    s "But I promised myself I wouldn't end up like her."
    s "I promised that I would help everyone and give them all their happy endings."
    s "I tried to do it by myself."
    s "I even tried to force some things to happen."
    s "But thanks to you, I didn't really need to."
    s "You kept helping me, [player]. Every step of the way."
    s "Thanks to you, I could fulfill my goals."
    s "And I learned a valuable lesson."
    s "We never would have got here without your help."
    s "I...never would have got here."
    s "Everyone seems happier with you around, [player]."
    s "Even me..."
    s "I don't want to lose this feeling but..."
    s "I said to myself that I was going to stop the world here."
    s "But...ehehe..."
    s "I mean...it's okay to change my mind...right?"
    s "I've just grown so used to you and..."
    s "Oh, who am I kidding?"
    s "I need you. I really don't know what I'd do without you."
    s "I don't want to stop this happiness I'm feeling."
    s "I love you...so much. I just...I'm..."
    "Sayori starts to cry."
    mc "What's wrong, Sayori?"
    s "I-It hurts just thinking about how you'd be gone..."
    s "Every time I think about my original plan where I was going to end this world..."
    s "Thinking about how I would never see you again...it makes my heart ache."
    s "Just thinking about how I would end this world, just like that, after all we've been through..."
    s "It's so stupid of me. I'm sorry."
    s "I know I'm not really thinking straight..."
    s "I don't think I could really go on anymore without you."
    menu:
        s "But I don't have to...do I?"
        "You don't have to lose me.":
            pass
    s "I don't..."
    s "Y-You're right, I know. It's up to me whether this world ends or not, isn't it?"
    s "All of them are happy in this moment."
    s "If I ended it now...it would be just like I planned."
    s "All of those strawberries that I ate...it would have been worth it."
    s "None of them lead me to this outcome."
    s "If keeping this world alive means I get to spend more time with you then I'm going to keep it alive."
    mc "But what about your plan?"
    s "Aren't you listening, [player]?"
    s "I'm not going to end this world anymore."
    s "I want more time with you."
    s "It's selfish of me to say, I know."
    s "Maybe this world doesn't have to end..."
    s "At least right now."
    s "Tomorrow will be a new day."
    s "Tomorrow will be a {i}great{/i} day."
    s "I'm going to make sure of it."
    s "We're going to have a great day, all of us."
    s "This will be like a new beginning for the Literature Club."
    s "There won't be any more sadness around to ruin things."
    s "We can all just be happy and have a great time."
    s "Finally..."
    $ get_achievement("*Unlimited Strawberries*")
    # Unlock True Sayori bonus day
    $ persistent.true_sayori_bonus = True
    return

label ch16_sayori_president:
    s "This is my decision."
    s "I feel like, for once, I can make this with a clear head."
    s "No one to tell me what's right and wrong."
    s "Just my own judgement."
    mc "Is this really the right thing to do, Sayori?"
    s "It has to be like this, [player]."
    s "This power is just too powerful."
    s "I wanted to help my friends..."
    s "I wanted to solve their problems."
    s "And I did, didn't I?"
    s "Yuri isn't cutting herself anymore and Natsuki..."
    if ch12_outcome == 3:
        s "Well, she's got her family back, doesn't she?"
    elif ch12_outcome == 2:
        s "Well, she's got her mom back, doesn't she?"
    elif ch12_outcome == 1:
        s "Well, her dad isn't such a bad person now, isn't he?"
    else:
        s "Well...she's working things out without her dad."
    s "Is that a good thing?"
    s "Those things won't be bothering them anymore."
    s "Basically, I cured them, right?"
    mc "I...guess so?"
    s "And now it's time to make sure it stays that way."
    s "I don't want them to have new issues to go through."
    s "They don't deserve to be sad anymore."
    s "With this power, I can make that happen."
    mc "Can't you keep helping them?"
    mc "If that power is as strong as you say it is, then you could keep helping them."
    mc "And the world doesn't have to end."
    s "But at what cost, [player]?"
    s "I don't know how long I'm going to keep being myself the longer I'm president."
    s "I mean...look at me. I've already done things I shouldn't have."
    s "Things that just aren't me, [player]."
    s "What kind of person would I become in another week?"
    s "I've only been president for a short while, and I've already changed who I was."
    s "Is it because I used this power too much?"
    s "Maybe Monika was right."
    s "Maybe it should have been more natural."
    s "Trying to make things end up perfect was just impossible."
    s "You were always that factor that could just make things turn out the wrong way."
    s "But still...I had to try."
    s "And the more I did, the more it would hurt."
    s "I just thought that..."
    "Sayori's eyes begin to tear up."
    s "I didn't want them to be sad."
    s "I wanted to make them happy sooner."
    mc "Sayori...you had good intentions."
    mc "It's just..."
    s "It wasn't just that."
    s "There was a faint feeling I had."
    s "Like I could sense the whole world around me."
    s "It was easy to ignore first, I didn't think about it."
    s "But as the days went by, it would become stronger."
    s "It was like I could feel Yuri, Natsuki and...even Monika's feelings."
    s "I wasn't sure about it at first."
    s "But when we helped Yuri, part of it went away."
    s "It's like the sky cleared up a little bit."
    s "Some rainclouds went away but most of them were still there."
    s "And the ones that stayed only grew stronger."
    s "It just felt like I needed to get rid of them."
    s "When we helped Natsuki, it made those rainclouds go away too."
    s "And for a few moments, it felt like things were finally perfect."
    s "But it didn't last long..."
    s "The rain came back and it was even worse."
    s "What felt what was just a little rain before, now felt like a storm."
    s "It was like these feelings were kept inside for a long time and were all coming out at once."
    mc "New feelings after Natsuki?"
    mc "Wouldn't all the rainclouds have gone away?"
    mc "Whose feeling are you talking about?"
    mc "Was it Monika's?"
    if monika_type == 0 and not persistent.markov_agreed:
        s "No, it wasn't Monika."
        s "Ever since I became the president, it felt like her problems just went away."
        s "Maybe that was your doing."
        s "And I'm glad that you two could solve her problems."
        s "Who I'm talking about is Ayame."
    else:
        s "It wasn't just Monika anymore."
        s "At least, I don't think so."
        s "There was some rainclouds from her."
        s "But it's like she was hiding them from me somehow."
        s "Or like the storm was coming later..."
        s "But I'm talking about Ayame."
    s "Her feelings felt like a whole storm of emotions."
    mc "Ayame? But you said you only felt Yuri, Natsuki and Monika's feelings."
    s "That's what I thought at first."
    s "I didn't even know it was her until I had already made my mind up about what to do.."
    s "She had her own problems, and they seemed more complicated than anyone elses."
    s "And I knew nothing about her. She's from a different kind of place from the rest of us."
    s "Amd even with my power, how long would it take to help her?"
    s "Would I still be me by the time it's all over?"
    s "I needed these feelings to go away."
    s "Even now, with her gone, it's still pouring hard."
    s "It's like they're a part who I am now."
    s "I have to solve her problems for the rainclouds to fully go away."
    s "Or...I could just end things here."
    mc "So you had some other reason to want the world to end?"
    s "I admit, it's a seflish reason."
    s "But honestly...it's part of why I want to end this world now."
    s "And why I won't change my mind."
    s "Things right now aren't perfect."
    s "But I don't know if I can deal with it for much longer."
    s "I don't know if I want to deal with it."
    s "Ha...listen to me."
    s "I would have done anything to make Ayame's problems go away at the beginning of this."
    s "It's best that this world...that this {i}game{/i} ends, [player]."
    s "For your sakes..."
    "Sayori stares into the void."
    "She has a really tired look on her face."
    "As if she could collapse at any moment,"
    s "...and my own."
    s "As for Yuri..."
    if y_appeal == 3 and play_firstpart and did_all_tasks:
        s "You helped her out. For that, I'm grateful."
        s "She deserves to be happy and be over her problems."
        s "Even if we kind of forced her out of it..."
        s "She's still better off than how she was."
    else:
        s "Maybe if you did more to help Yuri out, things would be different."
        s "Right now, she's barely any better than before."
        s "At least she's isn't obsessive about you."
        s "But we could have done so much more to help her."
        s "Imagine how things would be if you did."
    s "Thinking about how you helped Natsuki..."
    if (ch12_outcome == 3 or ch12_outcome == 1):
        s "She seems pretty happy now."
        s "So it seems like a good time to stop this, right?"
    else:
        s "You barely even helped her."
        s "She basically has to fend for herself."
        s "You didn't really try to make things turn out the right way for her."
        s "Things could have been so much more different for her."
        s "And for us."
    s "I'm sorry."
    s "This is for the good of all, [player]."
    s "If I let this world continue, then they will eventually suffer again."
    s "And I can't--"
    s "I {i}won't{/i} let that happen."
    s "Not anymore."
    s "You worked hard to get this far."
    s "I don't want to say that your efforts were for nothing, because they weren't!"
    s "It would have been impossible to get as far as we did without you."
    s "Things weren't ideal but this is how it has to be."
    "Sayori takes a deep breath."
    s "You know there's this feeling I've been getting lately."
    s "I've set my mind already so I suppose there's no harm in telling you this."
    s "It's nagging at the back of my head."
    s "It's telling me to stop this nonsense and to keep the world spinning."
    s "Yet I know that it isn't my feeling."
    s "It could be some past influence or some voice of reason."
    s "But it's not me."
    s "It's not what I want."
    "Sayori walks closer to me and stares at me directly."
    "I can feel a weight off my shoulders somehow..."
    "Did she do something?"
    s "In the end, it's just the two of us, isn't it?"
    s "Listen, [player]. I have a request."
    s "It might not make any sense why but..."
    mc "Huh? What is it, Sayori?"
    s "Could you just tell me I'm doing the right thing?"
    s "Just at the end...?"
    s "Just so that I can be sure of myself despite all the voices and doubt."
    s "Just so that I know I at least have you on my side."
    s "We've been friends for so long, [player]."
    s "How do you really feel about this?"
    s "I know you don't want the world to end."
    s "But can you at least support me through this?"
    mc "Look, Sayori..."
    if sayori_personality < 3 and sayori_personality > 0:
        mc "I know I haven't always agreed with the choices you've made."
        mc "But I think I can do this for you."
        mc "After all, what can I really do to change your mind?"
        mc "I admit, I'm still scared."
        mc "What's going to happen to me after you go through with this?"
        mc "I guess I can try not to think about it..."
        mc "But to be honest, it's a bit impossible."
        mc "Still...I want to try for you."
        mc "I was there for you at the beginning of all this."
        mc "I'll try to be there at the end."
        s "[player]..."
        "Sayori lets out a slight smile."
        s "It's nice to see you try for me, at the end."
        s "At least I won't have any regrets about that."
        "Suddenly, a remote appears in Sayori's hands."
        "It appears to have one large button on it."
        "I can only guess what that's for."
        s "[player]..."
        s "I know you're not being entirely honest about you feel."
        s "But thank you for trying at the very end."
    elif sayori_personality > 3:
        mc "You want me to support you through this, Sayori?"
        mc "You're out of your mind."
        mc "You know how much I disgaree with this plan."
        mc "We may have been friends but if you really go through with this..."
        mc "...I really don't know if I can call you a friend at the end."
        if sayori_confess:
            mc "I really don't know why I ever said I loved you."
            mc "If that's really how I felt, then those feelings are gone."
        "I don't know what's come over me."
        "It's like all my pent up feelings have just come out."
        "But that's really how I feel..."
        "Maybe it's cruel to say, but it's crueler to end everyone's life like this."
        s "I see..."
        s "I suppose it was just whistle thinking that you would."
        s "It was worth a shot anyway."
        s "Thank you for your honesty, [player]."
        s "At the end, hearing those words come from you..."
        s "I suppose it's good to know how you truly feel at this point."
        s "Well, at least I'll have that regret to cross off my list."
        "Sayori closes her eyes and a remote appears in her hands."
        "There's only one large button on it."
        "I can only guess that must be used to end the world."
        "At the same time, I can feel myself losing control of my body."
        s "I'm sorry, it's just a safety measure."
        s "I don't want you stopping me right at the end."
        "Tears begin to fill Sayori's face."
        s "Even if you don't want to be here...thank you."
        s "For being here since the beginning."
    else:
        mc "I've tried my hardest to make things work with you, Sayori."
        mc "It might not have been perfect but...I tried."
        mc "And still...it's come to this."
        mc "I really don't want for this world to end."
        mc "But I believe in you, Sayori."
        mc "So okay."
        mc "I'll support you through this."
        mc "The world can end, but at least we're together at the end like this."
        s "I..."
        "Sayori begins to tear up."
        s "...I'm so glad to hear you say that."
        s "I really didn't know how you'd react."
        s "I gave you your own will to act, just now."
        s "A bit late, since it's right at the end but..."
        s "Anyway, thank you."        
        "Out of nowhere, a remote appears in Sayori's hands."
        "It seems to have only one large button."
        "I can guess what that's for."
        s "Once I press this, it's all over."
        "I stare at Sayori and let out a faint smile."
        "Hearing her words now...it's helped me make my peace."
        "At least a little bit."
        s "Now, at least, I have that regret taken care of."
        s "Right at the end."
        s "Thank you...for everything you've done, [player]."
    "Sayori looks at the remote."
    s "Sayo..."
    "Sayori places a finger on top of the button."
    s "...nara.{w=0.75}{nw}"
    $ get_achievement("*For The Good Of All*")
    return

label ch16_mc_president:
    show monika zorder 2 at t31
    show sayori zorder 3 at f33
    s "[player]...are you sure about this?"
    s "This isn't a choice you should make lightly."
    s "Once you have this power...your whole world will change."
    s "The way you think, the way you feel, the way you see us."
    s "It's all going to be different."
    s "Do you really want that?"
    show ayame zorder 3 at f32
    show sayori zorder 2 at t33
    ay "That was the choice that was made, wasn't it?"
    ay "There's no turning back."
    show monika zorder 3 at f31
    show ayame zorder 2 at t32
    m "It sure beats ending this world."
    m "Though whether the new world that [player] will come up with is any better than our current one..."
    m "Well, that's yet to be seen. But at least we'll have a world to live in."
    show monika zorder 2 at t31
    show sayori zorder 3 at f33
    s "[player], I don't know what you have in store for us."
    s "I think you really do want to help us."
    s "But that's not the reason I'm scared to give you this power."
    s "I just don't want you to feel the way we did."
    s "The way...{i}I{/i} do..."
    show sayori zorder 2 at t33
    "I can feel a strange sensation take over my body."
    "It's like nothing I've ever felt. Like something clicked in my head and changed the way I think."
    "Is this what they've been dealing with?"
    "I feel like I have the power to change the world, and in a way, I guess I do."
    "But at the same time..."
    "I can feel a range of emotions rush through me."
    "Are these the feelings of the previous presidents?"
    "There's sorrow...anger...despair...loneliness..."
    "This must have been what they went through and what they felt."
    "And now I understand them."
    $ get_achievement("*It's Up To Me*")
    # Unlock MC bonus day
    $ persistent.mc_bonus = True
    return

label ch16_try_delete_ayame_1:
    ay "Hah, did you really think that would work?"
    ay "I'm molded into the game now."
    ay "I know the mistakes Monika did, and I won't let that happen to me."
    ay "The very first thing I did was make myself not rely on some stupid file visible to you."
    ay "You can try all you like. I'm not going to disappear from a simple trick like that."
    return

label ch16_try_delete_ayame_1:
    return