# Seperate into two different files because ch016 was getting huge
label ch16_mainb:
    scene black
    stop music
    "Before I can even react, my whole vision turns dark."
    "I try to move my body but it's like I don't have one."
    "It's a very strange sensation."
    "I can't feel anything, all I have is my thoughts."
    "Is this the next world?"
    "Or was that portal a fake somehow?"
    "No...Ayame was so sure it wasn't."
    "Maybe I did something wrong?"
    "Ayame!"
    "Can she even hear me right now?"
    "I can't even tell if I'm saying this out loud or if it's all in my head."
    "I guess I'll just wait until I hear something..."
    "Any second now..."
    "Any...second..."
    "Maybe I have to do something."
    "I can't just float here and do nothing."
    "But what can I even do?"
    "I don't have a body. It's like I'm just my consciousness."
    "Like a dream..."
    "But if this is like a dream, then I can make it whatever I want it to be...right?"
    "That's it, that's the key."
    "I try to imagine arms and hands."
    "I can sense the feeling of my hands returning."
    "But they feel...different, somehow."
    "They're definitely my hands, they feel like they're not the same."
    "I'm getting sidetracked."
    "I need to get the rest of my body back."
    "One by one, my sense of feeling is coming back to me."
    "As my head comes back, I take a deep breath."
    "There's no air."
    "In my panic, I take another breath. There's still no air."
    "I'm suffocating! What do I do?!"
    "I was just fine before. Why is this happening now?!"
    "Think of air, [player]! Think of air!"
    "I gasp for air."
    "This time I can breath properly."
    "I hyperventilate for a few moments to calm myself down from what just happened."
    "Where the hell did we end up?"
    "There's just nothing here."
    "Do I have to come up with the others as well?"
    "Or do they have to do it themselves?"
    "What if I think about the wrong things and they end up messed up somehow?"
    "They won't be the same person..."
    "Just my perception of them."
    "I have to think. There must be something I can do."
    "Maybe some place for us to be at would be a good start."
    scene bg bedroom_gray
    "Okay...why is it all in black and white?"
    "Is this what this world is?"
    "Or was that because of me?"
    "I examine my hands and notice they're also just black and white."
    "At least it seems familiar."
    "Maybe this world is just another copy?"
    "Sayori wouldn't make it that easy, would she?"
    "Okay, I can do this."
    "I was alone before, I can regroup with them again."
    "How many times are we going to go through this to get to Sayori?"
    "We have to be getting closer."
    ay "We are getting closer."
    "Whoa! What the hell was that?"
    "It sounded like Ayame's voice."
    "But where is she...?"
    "Her voice sounds like it's coming from all directions."
    ay "Yes, hello. It's me."
    ay "I don't have a corporeal form here."
    ay "I guess it's just a side effect of this world."
    ay "You have to give me a form, [player]."
    ay "Something I can use to interact with the world."
    ay "Anything."
    mc "But how do I do that?"
    mc "Do I just think of you?"
    mc "Of what you look like?"
    ay "No. You don't have to do that."
    ay "If you looked at the mirror you could see how well that turned out."
    mc "...Huh?"
    ay "Let's just say you didn't exactly give yourself the best embodiment."
    ay "For me, just imagine something simple."
    ay "Something that I can easily embody and navigate through the world with."
    ay "I don't think we'll be here long, so anything will do."
    ay "After that, we can work out where to go next."
    mc "Okay, here goes nothing."
    ay "Remember, simple."
    ay "Nothing complicated. I wouldn't want to end up like you."
    mc "Got it..."
    "Something simple..."
    "I think I have something in mind."
    "I mean what could be more simple than that, right?"
    "Like Ayame said, we won't be here long."
    "Just something to get the job done..."
    "I think I've done it. But how is she going to embody it?"
    mc "Okay."
    ay "Are you serious?"
    mc "I couldn't think of a more simple thing."
    mc "It's enough, right?"
    ay "...I suppose."
    "Ayame doesn't seem satisfied with what I came up with."
    "But what else could I have done?"
    ay "It won't matter anyway."
    ay "Here goes nothing..."
    "Ayame's voice is gone."
    "For a little while, I'm left alone again."
    mc "Ayame, are you--"
    ay "Yeah...I'm here."
    "The figure I came up with suddenly begins to come to life."
    "I guess she figured it out."
    show ayame stick zorder 2 at t11
    ay "I can't believe you did this."
    "Ayame's voice seems to be coming from the thing I created now."
    "So I think that's a good sign."
    mc "You did say simple."
    mc "You can't possibly put all of the blame of this on me."
    ay "Whatever, let's just get this over with."
    if ch16_ay_companions == 4:
        ay "You need to do the same for the other two as well."
        mc "How come I can't hear their voices?"
        ay "I...don't know. It might be because I'm the only one you still have a link to."
        ay "We didn't exactly re-establish it."
        mc "So what do we do then?"
        ay "They should be around here somewhere, right?"
        ay "Try coming up with something for them to embody."
        ay "Maybe that'll work."
        ay "And maybe--"
        "Before Ayame can finish her sentence, I come up with two more things that mildly resemble Yuri and Natsuki."
        "It suddenly appears in front of us."
        ay "...make it more sophisticated."
        ay "Never mind."
        mc "Well, what do we do now?"
        ay "We wait. Hopefully, they'll begin to move soon."
        ay "All they have to do is walk into it."
        ay "Or...float into it."
        mc "So they have to go into it somehow."
        mc "Then how did I start moving?"
        ay "I don't know. Maybe you created it where you were and did it automatically."
        mc "I guess so."
        "I can't help but feel Ayame is hiding something from me."
        "Like she knows more than what she's letting out."
        "Maybe Natsuki was right..."
        "The figure that resembles Natsuki begins to move."
        "The movements are rigid at first, unlike when Ayame did it."
        "I can only assume that it's Natsuki that's inhabited it."
        "Not long after, the figure resembling Yuri starts moving as well."
        "Their movements are almost robotic."
        "I wonder why they're like that when Ayame could move perfectly fine."
        mc "Are the two of you okay?"
        mc "I didn't mess anything up did I?"
        "The figure resembling Natsuki looks at me."
        "Or at least, I think it is. I didn't exactly give it eyes."
        ay "I think maybe it's trying to talk. It doesn't exactly have a mouth."
        mc "But I can hear you just fine."
        ay "Oh, right. Hold on a second."
        ay "I think that should do it."
        ay "We should be able to communicate properly now."
        ay "I forgot to mention I'm not actually speaking."
        ay "That's why it doesn't sound like my voice is coming from...this thing you made."
        ay "It's like how it was when the whole world was frozen."
        ay "I'm not sure you've realized but you don't have a mouth either, [player]."
        mc "I don't even know how I made myself."
        mc "From what I can see, I don't look any different."
        mc "Or {i}feel{/i} any different."
        ay "I mean...it's probably best you don't look in a mirror."
        ay "Anyway...did the link work? Natsuki? Yuri?"
        show natsuki stick zorder 2 at t31
        n "Are you serious, [player]?"
        "Natsuki's voice echoes in my head."
        "Natsuki's figure starts to move a bit more naturally now."
        "I guess whatever Ayame did work."
        n "What the hell is this?"
        n "Could you have picked a more "
        ay "The link is back up. Yuri, are you here?"
        show yuri stick zorder 2 at t33
        y "I-I'm here. At least, I think I am."
        "Yuri figure raises one of it's hand and tries to make a wave."
        y "What are we doing here?"
        ay "Have you forgotten what we're meant to be doing?"
        y "No, I mean...why are we in [player]'s room?"
        ay "Well..."
        "Ayame's figure--"
        "{i}Ayame{/i} looks towards me."
        mc "It was the first place I thought of."
        mc "This whole place was just a void."
        y "I think you did a good job recreating it."
        y "Everything appears to be as it should be."
        "Yuri looks around the room."
        y "Except...why is it all black and white?"
        mc "I don't know, it was just like that."
        n "Okay, two things."
        n "One, I don't have the journal anymore."
        n "It's just gone, presumably with the rest of my original self."
        ay "We won't need it. I'm sure we can figure this out without it."
        n "That's not even my biggest concern, Ayame."
        n "If [player] made this place, then how are we supposed to figure out where to go?"
        y "That's a good point. The world outside this room doesn't exist, does it?"
        y "It would just be...empty."
        ay "This world, dimension, whatever is definitely different to what we're used to."
        ay "We're going to need to get creative if we're going to get to Sayori."
        n "Can you explain what's going on?"
        ay "I'm not entirely sure, but it seems like [player] can create whatever [player_personal] wants with just a thought."
        ay "Tell me if I'm wrong."
        mc "From what I can tell, you're right."
        mc "I don't entirely understand how it works."
        mc "But just tell me what I should do."
        ay "I can't be completely sure if this will work."
        ay "But I think you have to create us a path to Sayori."
        mc "A path to Sayori? What do you mean?"
        ay "There's nothing out there."
        ay "I mean literally, it's just completely empty."
        "Ayame points to the window and points out the vast emptiness stretching across as far as I can see."
        ay "The only thing that exists is your room and the four of us here."
        mc "Right."
        n "What are you trying to get at, Ayame?"
        ay "I'm speculating that [player] has to create this world."
        y "But how is [player_personal] going to know what to create?"
        ay "Now that's the thing we have to figure out."
        ay "Again, I'm not sure, but I think the bench was a kind of hint."
        ay "You said that you had adventures with her, didn't you?"
        ay "Then maybe..."
        "My adventures with Sayori..."
        "Remember the good times...why am I the only one that can remember that those whispers?"
        "The others forgot about it already, somehow."
        "Yet it's still clear in my head."
        "What was one of our first adventures?"
        "My head is filled with all of these memories that I didn't know existed."
        "Yet one seems to stand out..."
        mc "Remember the good times because the world will end."
        "I say that without even thinking and suddenly the room begins to shake."
        y "W-What's happening?"
        n "Look outside!"
        "Natsuki points out the window and it appears that some sort of beach is forming."
        "Was that because of me?"
        scene bedroom_gray_color
        show natsuki stick zorder 2 at t31
        show ayame stick zorder 2 at t32
        show yuri stick zorder 2 at t33
        "Slowly, the world begins to regain color."
        "I can hear waves crashing and the wind howling outside."
        ay "[player], was this your doing?"
        mc "I don't know. It just sort of happened!"
    elif ch16_ay_companions == 3:
        ay "You have to imagine something for Yuri as well."
        ay "I don't know if she's here because she doesn't have a voice but she should be."
        mc "Why is that anyway? I could hear you just fine."
        ay "It's probably because we didn't re-establish the link."
        ay "That's how I was able to speak to you."
        mc "That makes sense."
        ay "Now imagine something for Yuri to inhabit."
        ay "It doesn't have to be the same as me, it could be--"
        "Before Ayame can finish her sentence, I come up with something that mildly resembles Yuri."
        "It suddenly appears in front of us."
        ay "...a bit more sophisticated."
        ay "Never mind."
        mc "What now?"
        ay "Now, we wait. If my theory is correct it'll start moving soon."
        ay "Yuri, if you can hear me..."
        ay "All you have to do is float into it."
        ay "I know it's not the best thing but just bear with it."
    elif ch16_ay_companions == 2:

    elif ch16_ay_companions == 1:

    elif ch16_ay_companions == 0:

    scene bg beach_day
    with wipeleft_scene
    return
