label ch15_main:
    scene black
    show sayori 1a zorder 2 at t11
    play music mend
    s "You're busy so I won't take up much of your time."
    s "There's just a couple of things I need to say."
    if ch14_m_tellsayori:
        s "For one thing, Monika called me last night."
        s "It was after [player]'s preparations with her."
        s "And I'm kinda worried."
        s "She seems really distressed."
        s "More than before."
        s "What she told me..."
        s "I have to be prepared for it."
        s "We all do..."
        s "I just wish it wasn't timed like this."
        s "It's such a bad time, you know?"
        s "In the middle of all our preparations."
        s "But it's important."
        s "I need to take care of it before it gets out of hand."
        s "Do you even know what it is?"
        s "..."
        s "I guess you can't really answer me."
        s "It doesn't matter, you don't need to know."
        s "If you did, Monika would have told you herself."
        s "Anyway..."
    elif monika_type == 0:
        s "There's that new danger I have to worry about."
        s "You know, that thing that Monika told me something yesterday."
        s "I didn't expect that from her."
        s "Or what she said."
        s "I'm glad she told me in the end."
        s "Otherwise it would have ruined everything."
        s "But..."
        s "For some reason, I have a bad feeling."
        s "Like she's not telling me everything."
        s "I don't know why."
        s "I trust her."
        s "So she must have some reason she's hiding it."
        s "Do you have anything to do about that?"
        s "In any case, I need to be careful."
        s "Anyway..."
    elif monika_type == 1 and ch12_markov_agree:
        s "Yesterday, Monika tried to speak to me."
        s "She said she needed to tell me something urgent."
        s "You were there for the start of it, weren't you?"
        s "What she told me was...worrying."
        s "I don't know if I should tell you."
        s "Because it's something I have to fix myself."
        s "I'm still looking for it."
        s "I'm grateful Monika told me but..."
        s "She was really vague about it."
        s "Maybe I'll ask her more about it."
        s "There has to be a reason for it."
        s "A reason for why it's coming..."
        s "And why it wants to hurt us."
        s "You know, I'm still not sure she's telling the truth."
        s "To be honest, I've been suspicious of her lately."
        s "I don't know why..."
        s "Maybe it's the hair...?"
        s "Ehehe, I don't know."
        s "I guess I'm just worried..."
        s "Anyway..."
    s "The preparations seem to be going well."
    s "Some people haven't really done much but by the time the day comes around, I know they'll be finished."
    s "This day is going to be great, I know it."
    s "With how much effort I've put into making sure everyone else can do their parts..."
    s "It's going to hurt at the end."
    s "But it's for the best, right?"
    s "For everyone..."
    s "For...me."
    if ch14_sayori_date_choice:
        s "I know I said yesterday that [player] and I would go on a date."
        s "But I really don't know if I'll be able to follow through."
        s "I just said that to encourage him to prepare."
        if sayori_personality <= 0:
            s "And lately..."
            s "I've been having second thoughts."
            s "I don't know where they're coming from."
            s "If they're a side effect of becoming the president or..."
            s "...something else."
        else:
            s "I have more important things to worry about."
            s "As much I hate to hurt him..."
            s "It's for the best."
    else:
        s "It's just a matter of finding the right time."
        s "I really haven't planned that far ahead."
        s "Ehehe, I really should though."
        s "But with all the things you can do, it makes things really unpredictable."
        s "I mean that literally."
        s "When I look forward in time, things are a blur."
        s "I assume it's got to do with choices you can make."
        if sayori_personality <= 0:
            s "And right now..."
            s "I don't know if you'll make {i}that{/i} choice."
            s "That's why I have to stay focused."
            s "I can't have any distractions."
        else:
            s "But who really knows?"
            s "It might be something else..."
            s "Something neither of us are really prepared for..."
    s "We should go now."
    s "There's still so much to do before the meeting."
    s "Lots of things that are still unaccounted for."
    s "I don't think it's going to be a long meeting."
    s "There's nothing really to talk about."
    s "We all know what we're doing after all."
    s "And everyone read the book we're going to be doing so..."
    s "..."
    if ch13_name == "Monika":
        s "That reminds me."
        s "You know I've been keeping an eye on everybody, right?"
        s "Just to make sure everything is going okay."
        s "But there's something strange happening with you."
        s "I tried to look at what was happening yesterday."
        s "To you and Monika."
        s "But..."
        s "I just couldn't."
        s "You wouldn't have anything to do about that, would you?"
        if sayori_personality > 2:
            s "Because I really get the feeling you do."
            s "I'm going to find out what it is."
            s "Even if it's nothing big, I need to know why that's happening."
            s "I might try asking Monika..."
        else:
            s "I...don't know why I'm immediately blaming you."
            s "Sorry."
            s "It's just...I..."
            s "Never mind."
            s "It's probably my fault."
            s "Maybe I messed something up."
        s "Anyway..."
    s "Goodbye for now."
    stop music fadeout 2.0
    if ch13_name == "Natsuki" or ch13_name == "Yuri":
        scene bg school_front with dissolve_scene_full
        play music t2
        "[ch13_name] and I were going to talk about our preparations."
        "We didn't have enough time last night so we're going to use some of our lunch to do some more."
        "I did come up with a few ideas of what we could do."
        "I brought the stuff I needed to."
        "I even did what I could last night."
        "I wonder how much [ch13_name] did."
        "Most likely more than me..."
        "She did insist on doing all the harder stuff."
        "So I shouldn't feel too bad."
        "But still..."
        if ch13_name == "Yuri":
            show yuri 1a zorder 2 at t11
            y "Hello, [player]."
            "Yuri appears in front of me carrying a bag full of material."
            y "Sorry, I'm late...I was looking for you."
            mc "No, you're just on time!"
            y "Are you ready to do this?"
            mc "Ready as I'll ever beself."
        else:
            show natsuki 1a zorder 2 at t11
            n "There you are!"
            "Natsuki appears in front of me carrying a bag full of ingredients."
            n "I was looking for you, you know."
            mc "I didn't realize this spot was so out of the way."
            n "Why'd you have to be over here?!"
    else:
        scene bg club_day with dissolve_scene_full
        play music t2
    "Everyone is already here."
    "I guess we're ready to get this over with."
    "We all have to do preparations, after all."
    "The less time we spend in here, the more time we have for that."
    "The day is fast approaching too."
    "Sayori looks like she has to say though..."
    "I better take my seat quickly."
    return

label ch15_end:
    return
