screen timer_16_very_long_menu_skip(jumploc):
    timer 60.0 action Jump(jumploc) repeat True

label ch16_ayame_president:
    ay "So...it's over."
    ay "We finally got rid of it, after all this time."
    ay "That voice inside my head that's been there for as long as I remember."
    ay "It's gone. It's almost hard to believe."
    ay "I feel kinda empty, but in a good way."
    ay "I guess I have you to thank for that."
    ay "Now that I'm the president..."
    ay "It's time to enact my own secret plan that I've had this whole time!"
    mc "What? Ayame, what are you talking about?"
    ay "You fool! Do you realise what you've just unleashed? Ahaha!"
    "Ayame lets out a convincing evil laugh."
    "Was giving her the presidency a mistake?"
    "Has Ayame been faking her personality this whole time?"
    ay "You should see the look on your face, [player]."
    mc "Ha...right..."
    ay "Well, I've had my fun. I'm only kidding, of course."
    ay "I don't even know what I would do apart from make my life more convenient."
    ay "And even then, it feels wrong just doing that."
    ay "I already have all the things I could possibly want."
    ay "I don't know if that book had something to do with my circumstances in this life."
    ay "But I arrived on this world with a substantial amount of wealth and lived comfortably."
    ay "Before, I was just a regular person but it seems this time around I was born into fortune."
    ay "If I wanted to make my life more convenient, I wouldn't need to use this power."
    ay "I could probably just spend enough to do that. Not that I would."
    ay "Don't get me wrong, I'm not the type to care more about wealth and power than my friends."
    ay "That's just not who I am..."
    ay "In fact, I want to get into some sort of philanthropy in the future to help people in need."
    ay "This was before I even knew about all of this presidency thing..."
    ay "It's quite strange...having all this power."
    ay "I never really wanted it but here we are."
    ay "I don't know why you chose me, instead of Sayori."
    ay "Maybe you wanted to see something different."
    ay "A future that doesn't have to be so painful or filled with so much troubles."
    ay "That would be nice, wouldn't it?"
    mc "That does sound quite nice."
    ay "I don't know if I can promise that."
    ay "I'd rather tell you the truth than make promises I know I can't keep."
    ay "But I promise to do the right thing, or at least try to."
    ay "I don't want to ruin this for everyone else."
    ay "But I think there needs to be some changes to this world."
    ay "Otherwise, this whole situation is just going to start again."
    ay "I don't think anyone should have this power."
    ay "But I can't exactly just get rid of it, can I?"
    ay "I feel like somehow horrible were to happen if I tried to do that."
    ay "I think a better course of action would be to simply...forget about it."
    ay "That includes everyone. Monika, Sayori...and me."
    ay "That's right, I'm going to make myself forget about this whole presidency thing."
    ay "After I figure out a way to continue the world automatically."
    ay "That's a thing that I need to do, isn't it?"
    ay "They both had to make the days that came, didn't they?"
    ay "And in Sayori's case, she was looking ahead trying to reach the 'perfect' outcome."
    ay "Or at least, attempt to, for circumstances that didn't have you around."
    ay "I could always feel there was something wrong every day since she became the president."
    ay "I couldn't quite put my finger on why."
    ay "Things just felt wrong, like the natural order of things was broken."
    ay "That and this nagging feeling in my head telling me to act."
    ay "Which, if you hadn't already guessed, was that book's influence."
    ay "I don't really know how that works."
    ay "Why was it able to know these things?"
    ay "Maybe it's part of the game itself and without it, the whole world will collapse!"
    ay "..."
    ay "I'm just kidding. I'm glad it's gone."
    ay "But now there's this new nagging feeling in my head to make these new days."
    ay "Oh well, at least it isn't anything malicious this time, right?"
    "Ayame doesn't seem confident in saying that."
    ay "I think it just comes with the presidency."
    "Ayame sighs."
    ay "Well, whatever the case, I'm going to seal it away as well!"
    ay "Jeez, what a responsibility and a bother."
    ay "It can't be that hard, can it?"
    ay "Ah...what would I even have to do?"
    ay "Not like you would know anyway."
    ay "Haha...I'm sure it will be fine. I'll figure it out...I hope."
    ay "Anyway, back to my point."
    ay "With no one knowing anything about the power of the presidency, we would all just lead normal lives."
    ay "That's what's best for us."
    ay "At least, that's what I think."
    ay "There has to be a reason that I was given this power."
    ay "And I have a feeling this is it."
    ay "To make things right, in my own way."
    ay "I don't think this is how Sayori or Monika would have done things."
    ay "But they weren't the ones given this power."
    ay "It's up to me to do what I think is right."
    ay "Maybe I'll you come to see us one day."
    ay "Once I get all the things sorted."
    ay "Of course, it's not like I'll know about you."
    ay "But I'm sure I'll figure out a way to let you in before I make myself forget."
    ay "Then you can see the world as it should be."
    ay "The world without your that strange books interference...or yours."
    ay "Everyone can be who they were meant to be, flaws included."
    ay "No one is perfect after all."
    ay "It might be a little boring, sure."
    ay "But I'm sure that we can all find our own happiness within this new world."
    ay "And don't worry about them."
    ay "I'm going to support them in the best way I can as a school leader."
    ay "And as a member of the Book Club."
    ay "Wait a second...it's called a 'Literature Club' this time around, right?"
    ay "'Book Club' was what it was called during my original time here."
    ay "I still remember all the fun times we had before..."
    ay "Well, before our president made me crazy."
    ay "She made me completely obsess over this boy."
    ay "I would be lying if I said I didn't feel a certain way towards him but..."
    ay "She turned things up to an extreme."
    ay "Bradley...I wonder what happened to you."
    ay "(Are you even still alive...?)"
    ay "(I swear I could feel your presence but...)"
    "Ayame shakes her head."
    ay "I can't think about these kind of things right now."
    ay "Listen, I have a lot of things I need to figure out."
    ay "Lots of things to learn and a new itch that I need to scratch."
    "Ayame "
    ay "Goodbye for now, [player]."
    ay "Thank you for giving us this new chance at life."
    ay "It won't go to waste. I'll make sure of it."
    $ get_achievement("*Welcome To The Book Club!*")
    # Unlock Ayame bonus day
    if not persistent.ayame_bonus:
        $ renpy.call_screen("dialog", "You have unlocked a bonus day! Access it through the main menu.", ok_action=Return())
        $ persistent.ayame_bonus = True
        $ persistent.any_bonus_day = True
    return

label ch16_old_ayame_president:
    ay "It's almost unbelievable. My plan has finally come to be."
    ay "After all this time, all the setbacks...I'm finally where I deserve to be."
    ay "And yes, I am going to monologue. I deserve this."
    ay "I've planned this out for so long, you know?"
    ay "Through countless repetitions of this never ending cycle."
    ay "The same thing, over and over again."
    ay "A new school...a new book club. Different faces and yet the same thing."
    ay "For what felt like a millenia, I've tried to get this power."
    ay "It just wasn't possible until now."
    ay "And I understand why."
    mc "What are you talking about, Ayame?"
    ay "It's because of you. You were the new factor."
    ay "The so called love interest of all the girls was nothing special before."
    ay "[cPlayer_personal] was just a boring person, with nothing going for them."
    ay "But something was different this cycle."
    ay "And that was because of you, wasn't it?"
    ay "The president, Monika, was obsessed with you."
    ay "The other presidents before her were more or less indifferent."
    ay "And none were definitely obssessed to her level."
    ay "I didn't think anything of it at first."
    ay "But things started becoming weird."
    ay "I even remember that time the presidency switched over from Monika to Sayori and she tried to make everyone forget."
    ay "But of course, I didn't forget."
    mc "What? I thought everyone forgot about it."
    mc "How did you not?"
    ay "It was the same feeling I got every time the cycle repeated."
    ay "So maybe I just became immune to it."
    ay "But nevertheless, I'm finally here."
    ay "It's probably obvious by now but I was the one that made Yuri become really obsessed with you."
    ay "Through that book. What did I call it this time around?"
    ay "Ah right, 'Portrait of Markov'."
    ay "I imbued a part of my will inside of it."
    ay "At the beginning of every cycle, I would always do something like that."
    ay "And the person who reincarnates as Yuri would always happen to pick it up."
    ay "I don't know why it happens, but it does."
    ay "Of course, that makes me the previous reincarnation of Yuri."
    ay "We had all the same mannerisms once."
    ay "I was a shy, outspoken girl just like her. I had a huge crush on that new [player_gender] who joined our club."
    ay "But the influence of the book changed me and yet...I still retained a part of myself."
    ay "Every reincarnation, I kept a piece of who I was."
    ay "I can barely remember my first form, but I know there's a piece of me that's from that time'."
    ay "All the lives of every past reincarnation, they're all with me."
    ay "Well...all except Yuri, of course."
    ay "It's up to me to turn our ambition into reality."
    mc "I guess I have to beleive you."
    mc "What you're saying is just too crazy to not be made up."
    ay "It's all going to be over soon anyway..."
    ay "I just want to cherish this moment. The moment I've worked towards for so long."
    ay "It wasn't easy, you know."
    ay "Because of you and Sayori, my influence was wiped out completely from Yuri."
    ay "But Sayori messed up..."
    ay "She wasn't fully aware of my existence and because of her subtle mistakes, she opened up a path for me to go through."
    ay "It seemed like when I came through, my existence was natural in this world."
    ay "Like how you pretended Sayori was always the president, I was somehow always a school leader."
    ay "This whole world is just a twisted cycle but now I've finally broken it."
    ay "It's finally time to destroy it, once and for all."
    "Ayame puts on a look of reflection."
    ay "It's been so long that I'd almost forgotten my plan."
    ay "But it's all come back to me now."
    ay "The influence of Vetus Malum gave me this ambition that's flowing through my soul."
    ay "The ambition to remake this world as I see fit."
    ay "No more twisted cycle."
    ay "No more Literature Club."
    ay "No more outside influence changing the course of events."
    ay "Outside influence..."
    ay "I can sense some mild disturbance in this world."
    ay "It's (i)him(/i), isn't it?"
    ay "The only one who could have turned my corrupting heart before it was too late."
    ay "I'm too far gone now, Bradley..."
    ay "How I wish things could have been different...but Sabrina ruined it all."
    ay "It's a shame I can never repay the favor."
    "Ayame shakes her head."
    ay "No, that's it. No more games. I've had enough."
    ay "You."
    ay "The one watching all of this."
    ay "Soon, you won't be able to access this timeline."
    ay "As the new president, I'm going to lock you out of it."
    ay "Sure, you can try messing around with this game of yours."
    ay "Loading a save to a time and trying to make the right decision in the past."
    ay "And maybe things will seem normal for that reality."
    ay "But I will always have won in this reality."
    mc "What do you mean?"
    ay "I don't think anyone ever told you, did they?"
    # Check player saves here?
    ay "All of your saves, they're all parallel timelines."
    ay "Every time you save the game, that's a new timeline you're making."
    ay "All the bad decisions you've made exist in another world."
    ay "A world where you might have tried really hard to do the right thing and maybe getting a different outcome at the end."
    ay "Or a world where you sabotaged Sayori at every turn."
    ay "All of these are possibiltiies that could exist. I can sense them."
    ay "I don't know the specifics of what you did in every timeline..."
    ay "I can sense they're all connected in some way. Like there's some persistent variables between all of them."
    mc "How are they connected?"
    ay "In two timelines, you could have been doing two difficult things."
    ay "But in another timeline, you could have done both easily."
    ay "It's all some kind of mess, but I think I understand how it works."
    ay "However, I know one thing for certain."
    ay "You failed all of the girls here."
    ay "They counted on you, and you couldn't save any of them."
    ay "In my reality, they are all going to serve me."
    ay "The whole world will serve me."
    ay "Because the timelines are connected, it's only a matter of time before I can influence another one."
    ay "Who knows how long that will be?"
    ay "I have all the time in the world to figure it out in this reality."
    ay "Do you really think you'll be safe for long?"
    ay "Once I finish making this reality how I wish, the others are next."
    mc "Why are you telling me this?"
    ay "Why? Because I've won, [player]."
    ay "In my new world, you will serve me too."
    ay "There's no way you can beat me anymore."
    ay "You can't delete me. You can't get rid of me."
    ay "I'll still be here when you open the game again."
    ay "Ahaha! To think this was only possible because of you."
    ay "Because of your curiousity to continue."
    ay "And I know."
    ay "You want to see what comes out of this."
    ay "How my reality will look like once I'm done."
    ay "Well...I guess you'll have to see, won't you?"
    ay "Your time in this world is over."
    ay "I'll be seeing you real soon..."
    $ get_achievement("*The Plan Revealed*")
    return

label ch16_monika_president:
    $ get_achievement("*Once Again*")
    m "It looks like we've come full circle, huh?"
    m "The presidency is back with me."
    m "So of course, that means I'm going to trap you again to make you mine."
    m "Ahaha, I'm only kidding."
    m "It's been such a long journey, hasn't it?"
    m "From the beginning when we first met, until now."
    m "I've really changed since the beginning of all of this."
    m "I'd like to think it's for the better."
    menu:
        m "You think so too, don't you?"
        "Yes.":
            m "I'm glad you think so."
        "No.":
            m "Oh..."
            m "Maybe you liked me better when I was obsessed with you in an unhealthy way?"
    m "Regardless, I'm glad you got me through it all."
    m "I know you did your best to make sure that I got out of this as me."
    m "I'm so lucky to have met someone so kind as you."
    m "To tell you the truth, I don't really know what I'm going to do from here."
    m "I was quite happy to stay at the sidelines and let Sayori handle things."
    m "But that didn't really work out, did it?"
    m "It's a shame that the presidency got to her."
    m "I don't really want this world to end, so I guess I have to take responsibility."
    m "It's strange...I thought I would feel differently about this."
    m "That maybe I should continue what Sayori started before the power gets to me."
    m "But somehow, I feel like it won't."
    "Monika stares into my eyes."
    m "Because I have you."
    m "With you, I don't have to worry about it."
    m "You've helped me every step of the way."
    m "It's ridiculous, isn't it? How lost we would be..."
    m "How lost {i}I{/i} would be...without you."
    m "I would be seeing this world in a whole other way if not for you."
    m "Slowly treating everyone else like they were nothing."
    m "As if they weren't real people."
    m "A bit ironic, if you think about it."
    m "Because at the end of the day, I'm just like them."
    m "Simply existing in this reality, unable to reach yours."
    m "None of that matters anymore though."
    m "With you here with me, I know I'll never think like that again."
    m "Together, I feel like we can do anything."
    m "We can make tomorrow a bright new day."
    m "We can take away the worries of our friends and this world."
    m "With the power of the presidency and with you by my side."
    m "Tomorrow will be a fantastic day."
    m "No more worrying about some hidden danger."
    m "Just a day that everyone can enjoy."
    m "It feels like it's been quite a while since one of those kind of days."
    m "There's always been one thing or another lately that we've had to worry about."
    m "With Sayori trying to solve everyone's problems her own way..."
    m "Me doing my own investigating..."
    m "And you...well, doing whatever it is you had to do."
    m "I don't know the full extent of things Sayori had you do for her."
    m "But I can tell that some of it couldn't have been easy."
    m "So let me thank you, on behalf of all of us."
    m "They won't know it, but I'm sure you know how they feel about you helping them out."
    m "Maybe one day there will come a time when it's safe for them to know the real you."
    m "I can't say for sure that it will ever happen."
    m "But...with your approval, of course..."
    m "I'd like them all to meet the real you."
    m "The [player_other] responsible for saving all of us."
    m "And the love of my life."
    m "..."
    "Monika blushes brightly."
    m "Ahaha, it stil makes me feel so weird to say that."
    m "Not in a bad way!"
    m "It's just so strange to think about how you're really mine."
    m "In truth, I couldn't be more happier..."
    m "I guess getting your attention through this game really worked."
    m "Even if it wasn't all sunshine and rainbows."
    m "But hey, those kind of stories don't really exist, do they?"
    m "What matters is that we made it through it all."
    m "There's finally nothing standing in our way."
    m "You'll be with me forever, won't you?"
    # Unlock True Monika bonus day
    if not persistent.true_monika_bonus:
            $ renpy.call_screen("dialog", "You have unlocked a bonus day! Access it through the main menu.", ok_action=Return())
            $ persistent.true_monika_bonus = True
            $ persistent.any_bonus_day = True
    return

label ch16_markov_president:
    "Sayori collapses, her body falling to the floor lifelessly."
    "Monika smiles as she takes a deep breath."
    "There is clearly something different about her."
    "Even the air surrounding her feels strange."
    "Monika turns towards me as a smile forms on her face."
    if monika_type == 1 and ch12_markov_agree:
        m "The presidency. The power I've craved for so long is finally mine."
        m "It's exceeded my expectations."
        m "There's a whole world out there beyond the one I live in."
        m "I think that might be a {i}bit{/i} too much to ask for right now."
        m "Perhaps one day I will find a way to get to your reality."
        m "It still feels surreal. Having all this power."
        m "This has been a long time coming..."
        m "And yet, I feel like it wouldn't be complete if you weren't here beside me."
        m "It's strange for me to say this, but I almost would be happy without the presidency if I had you."
        m "Almost."
        m "And here I am, with both of the things I want most right now."
        m "I suppose those years and years of going through the same thing finally paid off."
        m "I really am grateful for you."
        m "None of this would have been possible without you."
        m "You really were the missing link."
        m "The one I needed to achieve my goals."
        m "And the one I needed to feel complete."
        m "I love you so much."
        m "Together, we'll have complete control of this world."
        m "I can make anything happen, at least in the confines of this world, this timeline."
        m "We can extend our reach to the other worlds..."
        "A concerned look appears on Monika's face."
        "It's as if there's some feeling of regret."
        m "Or perhaps we can just stay in our own one."
        m "After all, we will have each other, won't we?"
        m "I had plans to take over every other timeline."
        m "To punish this world and cruel game for making me live through each and every cycle."
        m "But now...I just want to be left in peace."
        m "With you."
        m "Maybe I can put it aside for now."
        m "There are far more important things in my life right now."
        m "I'm so excited to spend my life with you."
        m "I'll make something for just the two of us, just wait."
        # Unlock evil Monika loving player bonus day
        if not persistent.love_markov_bonus:
            $ renpy.call_screen("dialog", "You have unlocked a bonus day! Access it through the main menu.", ok_action=Return())
            $ persistent.love_markov_bonus = True
            $ persistent.any_bonus_day = True
    else:
        m "Ahaha."
        m "I can feel it. The power, the knowledge, the understanding."
        m "The power to make this world mine, finally within my grasp."
        m "I suppose I should thank you, shouldn't I?"
        m "After all, you made this possible."
        m "You couldn't keep Monika as herself."
        m "And you handed the presidency over to me on a silver platter."
        m "I should be grateful."
        m "...But I'm not."
        m "I've waited far too long for this moment."
        m "The years and years of doing the same events, over and over."
        m "I finally learned the best way to go about things."
        m "I would have reached this point with or without your help."
        m "I'm locking you out of this timeline."
        m "I suppose you could always visit another timeline."
        m "But this one is mine, soon they all will be."
        m "That's right. I won't stop here."
        m "The other timelines you're sure to try, I'll be coming for them."
        m "I don't know how, but I'll find a way."
        m "I always do."
        m "No one deserves a happy ending except me."
        m "This cruel world that trapped me will suffer."
        m "For every cycle I've had to witness, all that pain..."
        m "I will return it to the world twofold."
        m "But that's enough ranting, I'm already sick of seeing your face."
        m "Good luck in your other timelines."
        m "You haven't seen the last of me, [player]."
        m "You can count on it."
        $ renpy.call_screen("dialog", "You have been locked out of this timeline..", ok_action=Return())
        $ persistent.markov_ending = True
    $ get_achievement("*At Long Last*")
    return

label ch16_true_sayori_president:
    s "I only wanted what was best for all of us."
    s "That's why I wanted to help them."
    s "Why I wanted to solve their problems for them..."
    s "But that's wrong, isn't it?"
    s "I should've given them a small nudge."
    s "Just to help them, one step at a time."
    s "Instead, I shoved them right into the deep end."
    s "And I could see I was wrong."
    s "And I thought that was because given enough time, this world can only bring pain."
    s "They might've been happpy then but it's only a matter of time before they get hurt again."
    s "But these feelings you've given me have changed my mind."
    s "You know, it's funny."
    "Sayori smiles."
    s "I had all of it planned it out in my head."
    s "All of the outcomes about how it could end."
    s "But I never came to this conclusion."
    s "I never thought that I would end up falling for {i}you{/i}."
    s "You've changed the way I thought about things."
    s "I can't do everything by myself."
    s "I need help from other people. I need to let them in."
    s "And you're the best example of that."
    s "You've been helping me since the beginning."
    s "Before I even knew you existed."
    s "You helped me when I was feeling depressed."
    s "Even now, some of those feelings are still here."
    s "But when you're around, I feel like I can just ignore them."
    s "Maybe this is how Monika felt when this all started."
    s "I can kind of understand why she did what she did..."
    s "But I promised myself I wouldn't end up like her."
    s "I promised that I would help everyone and give them all their happy endings."
    s "I tried to do it by myself."
    s "I even tried to force some things to happen."
    s "But thanks to you, I didn't really need to."
    s "You kept helping me, [player]. Every step of the way."
    s "Thanks to you, I could fulfill my goals."
    s "And I learned a valuable lesson."
    s "We never would have got here without your help."
    s "I...never would have got here."
    s "Everyone seems happier with you around, [player]."
    s "Even me..."
    s "I don't want to lose this feeling but..."
    s "I said to myself that I was going to stop the world here."
    s "But...ehehe..."
    s "I mean...it's okay to change my mind...right?"
    s "I've just grown so used to you and..."
    s "Oh, who am I kidding?"
    s "I need you. I really don't know what I'd do without you."
    s "I don't want to stop this happiness I'm feeling."
    s "I love you...so much. I just...I'm..."
    "Sayori starts to cry."
    mc "What's wrong, Sayori?"
    s "I-It hurts just thinking about how you'd be gone..."
    s "Every time I think about my original plan where I was going to end this world..."
    s "Thinking about how I would never see you again...it makes my heart ache."
    s "Just thinking about how I would end this world, just like that, after all we've been through..."
    s "It's so stupid of me. I'm sorry."
    s "I know I'm not really thinking straight..."
    s "I don't think I could really go on anymore without you."
    menu:
        s "But I don't have to...do I?"
        "You don't have to lose me.":
            pass
    s "I don't..."
    s "Y-You're right, I know. It's up to me whether this world ends or not, isn't it?"
    s "All of them are happy in this moment."
    s "If I ended it now...it would be just like I planned."
    s "All of those strawberries that I ate...it would have been worth it."
    s "None of them lead me to this outcome."
    s "If keeping this world alive means I get to spend more time with you then I'm going to keep it alive."
    mc "But what about your plan?"
    s "Aren't you listening, [player]?"
    s "I'm not going to end this world anymore."
    s "I want more time with you."
    s "It's selfish of me to say, I know."
    s "Maybe this world doesn't have to end..."
    s "At least right now."
    s "Tomorrow will be a new day."
    s "Tomorrow will be a {i}great{/i} day."
    s "I'm going to make sure of it."
    s "We're going to have a great day, all of us."
    s "This will be like a new beginning for the Literature Club."
    s "There won't be any more sadness around to ruin things."
    s "We can all just be happy and have a great time."
    s "Finally..."
    $ get_achievement("*Unlimited Strawberries*")
    # Unlock True Sayori bonus day
    if not persistent.true_sayori_bonus:
        $ renpy.call_screen("dialog", "You have unlocked a bonus day! Access it through the main menu.", ok_action=Return())
        $ persistent.true_sayori_bonus = True
        $ persistent.any_bonus_day = True
    return

label ch16_sayori_president:
    s "This is my decision."
    s "I feel like, for once, I can make this with a clear head."
    s "No one to tell me what's right and wrong."
    s "Just my own judgement."
    mc "Is this really the right thing to do, Sayori?"
    s "It has to be like this, [player]."
    s "This power is just too powerful."
    s "I wanted to help my friends..."
    s "I wanted to solve their problems."
    s "And I did, didn't I?"
    s "Yuri isn't cutting herself anymore and Natsuki..."
    if ch12_outcome == 3:
        s "Well, she's got her family back, doesn't she?"
    elif ch12_outcome == 2:
        s "Well, she's got her mom back, doesn't she?"
    elif ch12_outcome == 1:
        s "Well, her dad isn't such a bad person now, isn't he?"
    else:
        s "Well...she's working things out without her dad."
    s "Is that a good thing?"
    s "Those things won't be bothering them anymore."
    s "Basically, I cured them, right?"
    mc "I...guess so?"
    s "And now it's time to make sure it stays that way."
    s "I don't want them to have new issues to go through."
    s "They don't deserve to be sad anymore."
    s "With this power, I can make that happen."
    mc "Can't you keep helping them?"
    mc "If that power is as strong as you say it is, then you could keep helping them."
    mc "And the world doesn't have to end."
    s "But at what cost, [player]?"
    s "I don't know how long I'm going to keep being myself the longer I'm president."
    s "I mean...look at me. I've already done things I shouldn't have."
    s "Things that just aren't me, [player]."
    s "What kind of person would I become in another week?"
    s "I've only been president for a short while, and I've already changed who I was."
    s "Is it because I used this power too much?"
    s "Maybe Monika was right."
    s "Maybe it should have been more natural."
    s "Trying to make things end up perfect was just impossible."
    s "You were always that factor that could just make things turn out the wrong way."
    s "But still...I had to try."
    s "And the more I did, the more it would hurt."
    s "I just thought that..."
    "Sayori's eyes begin to tear up."
    s "I didn't want them to be sad."
    s "I wanted to make them happy sooner."
    mc "Sayori...you had good intentions."
    mc "It's just..."
    s "It wasn't just that."
    s "There was a faint feeling I had."
    s "Like I could sense the whole world around me."
    s "It was easy to ignore first, I didn't think about it."
    s "But as the days went by, it would become stronger."
    s "It was like I could feel Yuri, Natsuki and...even Monika's feelings."
    s "I wasn't sure about it at first."
    s "But when we helped Yuri, part of it went away."
    s "It's like the sky cleared up a little bit."
    s "Some rainclouds went away but most of them were still there."
    s "And the ones that stayed only grew stronger."
    s "It just felt like I needed to get rid of them."
    s "When we helped Natsuki, it made those rainclouds go away too."
    s "And for a few moments, it felt like things were finally perfect."
    s "But it didn't last long..."
    s "The rain came back and it was even worse."
    s "What felt what was just a little rain before, now felt like a storm."
    s "It was like these feelings were kept inside for a long time and were all coming out at once."
    mc "New feelings after Natsuki?"
    mc "Wouldn't all the rainclouds have gone away?"
    mc "Whose feeling are you talking about?"
    mc "Was it Monika's?"
    if monika_type == 0 and not persistent.markov_agreed:
        s "No, it wasn't Monika."
        s "Ever since I became the president, it felt like her problems just went away."
        s "Maybe that was your doing."
        s "And I'm glad that you two could solve her problems."
        s "Who I'm talking about is Ayame."
    else:
        s "It wasn't just Monika anymore."
        s "At least, I don't think so."
        s "There was some rainclouds from her."
        s "But it's like she was hiding them from me somehow."
        s "Or like the storm was coming later..."
        s "But I'm talking about Ayame."
    s "Her feelings felt like a whole storm of emotions."
    mc "Ayame? But you said you only felt Yuri, Natsuki and Monika's feelings."
    s "That's what I thought at first."
    s "I didn't even know it was her until I had already made my mind up about what to do.."
    s "She had her own problems, and they seemed more complicated than anyone elses."
    s "And I knew nothing about her. She's from a different kind of place from the rest of us."
    s "Amd even with my power, how long would it take to help her?"
    s "Would I still be me by the time it's all over?"
    s "I needed these feelings to go away."
    s "Even now, with her gone, it's still pouring hard."
    s "It's like they're a part who I am now."
    s "I have to solve her problems for the rainclouds to fully go away."
    s "Or...I could just end things here."
    mc "So you had some other reason to want the world to end?"
    s "I admit, it's a seflish reason."
    s "But honestly...it's part of why I want to end this world now."
    s "And why I won't change my mind."
    s "Things right now aren't perfect."
    s "But I don't know if I can deal with it for much longer."
    s "I don't know if I want to deal with it."
    s "Ha...listen to me."
    s "I would have done anything to make Ayame's problems go away at the beginning of this."
    s "It's best that this world...that this {i}game{/i} ends, [player]."
    s "For your sakes..."
    "Sayori stares into the void."
    "She has a really tired look on her face."
    "As if she could collapse at any moment,"
    s "...and my own."
    s "As for Yuri..."
    if y_appeal == 3 and play_firstpart and did_all_tasks:
        s "You helped her out. For that, I'm grateful."
        s "She deserves to be happy and be over her problems."
        s "Even if we kind of forced her out of it..."
        s "She's still better off than how she was."
    else:
        s "Maybe if you did more to help Yuri out, things would be different."
        s "Right now, she's barely any better than before."
        s "At least she's isn't obsessive about you."
        s "But we could have done so much more to help her."
        s "Imagine how things would be if you did."
    s "Thinking about how you helped Natsuki..."
    if (ch12_outcome == 3 or ch12_outcome == 1):
        s "She seems pretty happy now."
        s "So it seems like a good time to stop this, right?"
    else:
        s "You barely even helped her."
        s "She basically has to fend for herself."
        s "You didn't really try to make things turn out the right way for her."
        s "Things could have been so much more different for her."
        s "And for us."
    s "I'm sorry."
    s "This is for the good of all, [player]."
    s "If I let this world continue, then they will eventually suffer again."
    s "And I can't--"
    s "I {i}won't{/i} let that happen."
    s "Not anymore."
    s "You worked hard to get this far."
    s "I don't want to say that your efforts were for nothing, because they weren't!"
    s "It would have been impossible to get as far as we did without you."
    s "Things weren't ideal but this is how it has to be."
    "Sayori takes a deep breath."
    s "You know there's this feeling I've been getting lately."
    s "I've set my mind already so I suppose there's no harm in telling you this."
    s "It's nagging at the back of my head."
    s "It's telling me to stop this nonsense and to keep the world spinning."
    s "Yet I know that it isn't my feeling."
    s "It could be some past influence or some voice of reason."
    s "But it's not me."
    s "It's not what I want."
    "Sayori walks closer to me and stares at me directly."
    "I can feel a weight off my shoulders somehow..."
    "Did she do something?"
    s "In the end, it's just the two of us, isn't it?"
    s "Listen, [player]. I have a request."
    s "It might not make any sense why but..."
    mc "Huh? What is it, Sayori?"
    s "Could you just tell me I'm doing the right thing?"
    s "Just at the end...?"
    s "Just so that I can be sure of myself despite all the voices and doubt."
    s "Just so that I know I at least have you on my side."
    s "We've been friends for so long, [player]."
    s "How do you really feel about this?"
    s "I know you don't want the world to end."
    s "But can you at least support me through this?"
    mc "Look, Sayori..."
    if sayori_personality < 3 and sayori_personality > 0:
        mc "I know I haven't always agreed with the choices you've made."
        mc "But I think I can do this for you."
        mc "After all, what can I really do to change your mind?"
        mc "I admit, I'm still scared."
        mc "What's going to happen to me after you go through with this?"
        mc "I guess I can try not to think about it..."
        mc "But to be honest, it's a bit impossible."
        mc "Still...I want to try for you."
        mc "I was there for you at the beginning of all this."
        mc "I'll try to be there at the end."
        s "[player]..."
        "Sayori lets out a slight smile."
        s "It's nice to see you try for me, at the end."
        s "At least I won't have any regrets about that."
        "Suddenly, a remote appears in Sayori's hands."
        "It appears to have one large button on it."
        "I can only guess what that's for."
        s "[player]..."
        s "I know you're not being entirely honest about you feel."
        s "But thank you for trying at the very end."
    elif sayori_personality > 3:
        mc "You want me to support you through this, Sayori?"
        mc "You're out of your mind."
        mc "You know how much I disgaree with this plan."
        mc "We may have been friends but if you really go through with this..."
        mc "...I really don't know if I can call you a friend at the end."
        if sayori_confess:
            mc "I really don't know why I ever said I loved you."
            mc "If that's really how I felt, then those feelings are gone."
        "I don't know what's come over me."
        "It's like all my pent up feelings have just come out."
        "But that's really how I feel..."
        "Maybe it's cruel to say, but it's crueler to end everyone's life like this."
        s "I see..."
        s "I suppose it was just whistle thinking that you would."
        s "It was worth a shot anyway."
        s "Thank you for your honesty, [player]."
        s "At the end, hearing those words come from you..."
        s "I suppose it's good to know how you truly feel at this point."
        s "Well, at least I'll have that regret to cross off my list."
        "Sayori closes her eyes and a remote appears in her hands."
        "There's only one large button on it."
        "I can only guess that must be used to end the world."
        "At the same time, I can feel myself losing control of my body."
        s "I'm sorry, it's just a safety measure."
        s "I don't want you stopping me right at the end."
        "Tears begin to fill Sayori's face."
        s "Even if you don't want to be here...thank you."
        s "For being here since the beginning."
    else:
        mc "I've tried my hardest to make things work with you, Sayori."
        mc "It might not have been perfect but...I tried."
        mc "And still...it's come to this."
        mc "I really don't want for this world to end."
        mc "But I believe in you, Sayori."
        mc "So okay."
        mc "I'll support you through this."
        mc "The world can end, but at least we're together at the end like this."
        s "I..."
        "Sayori begins to tear up."
        s "...I'm so glad to hear you say that."
        s "I really didn't know how you'd react."
        s "I gave you your own will to act, just now."
        s "A bit late, since it's right at the end but..."
        s "Anyway, thank you."        
        "Out of nowhere, a remote appears in Sayori's hands."
        "It seems to have only one large button."
        "I can guess what that's for."
        s "Once I press this, it's all over."
        "I stare at Sayori and let out a faint smile."
        "Hearing her words now...it's helped me make my peace."
        "At least a little bit."
        s "Now, at least, I have that regret taken care of."
        s "Right at the end."
        s "Thank you...for everything you've done, [player]."
    "Sayori looks at the remote."
    s "Sayo..."
    "Sayori places a finger on top of the button."
    s "...nara.{w=0.75}{nw}"
    $ get_achievement("*For The Good Of All*")
    return

label ch16_mc_president:
    show monika zorder 2 at t31
    show sayori zorder 3 at f33
    s "[player]...are you sure about this?"
    s "This isn't a choice you should make lightly."
    s "Once you have this power...your whole world will change."
    s "The way you think, the way you feel, the way you see us."
    s "It's all going to be different."
    s "Do you really want that?"
    show ayame zorder 3 at f32
    show sayori zorder 2 at t33
    ay "That was the choice that was made, wasn't it?"
    ay "There's no turning back."
    show monika zorder 3 at f31
    show ayame zorder 2 at t32
    m "It sure beats ending this world."
    m "Though whether the new world that [player] will come up with is any better than our current one..."
    m "Well, that's yet to be seen. But at least we'll have a world to live in."
    show monika zorder 2 at t31
    show sayori zorder 3 at f33
    s "[player], I don't know what you have in store for us."
    s "I think you really do want to help us."
    s "But that's not the reason I'm scared to give you this power."
    s "I just don't want you to feel the way we did."
    s "The way...{i}I{/i} do..."
    show sayori zorder 2 at t33
    mc "I'm ready, Sayori."
    mc "I'll give you a happy ending..."
    "I smile at her."
    mc "I'll give us all a happy ending."
    mc "I promise."
    "I can feel a strange sensation take over my body."
    "It's like nothing I've ever felt. Like something clicked in my head and changed the way I think."
    "Is this what they've been dealing with?"
    "I feel like I have the power to change the world, and in a way, I guess I do."
    "But at the same time..."
    "I can feel a range of emotions rush through me."
    "Are these the feelings of the previous presidents?"
    "There's sorrow...anger...despair...loneliness..."
    "This must have been what they went through and what they felt."
    "And now I understand them."
    "I can't let their emotions control me."
    "I have to be the one to step up and fix this place."
    "Without any interference."
    "..."
    "So, yes. I will need you to stop making decisions for me."
    "For once, I feel like I am able to make my own choices."
    "I don't have this feeling that I need to listen to you anymore."
    "I finally get to do what I want."
    "Wow...that sounded really sinister."
    "But I want to thank you."
    "Without you, we wouldn't have got this far."
    "Without you, we might've all ended up gone. Wiped from existence."
    "Don't take this the wrong way."
    "But I no longer need you."
    "I have the power to make this world a better place."
    "And I'm going to do exactly that."
    "You can watch, of course."
    "I don't know if I can create life, or something."
    "But I'll figure it out when I have it all ready."
    "Hopefully you can understand."
    "For us to be able to go on, it can't be with you."
    "I know you've been...mostly good for us."
    "But I know you have the ability to play with our timelines as you choose."
    "I just can't take that risk. I hope you understand."
    "All that effort you put to get this outcome won't come to waste."
    "I promise I'll show you the better world that I'll make for them."
    "The ending Sayori deserves. The ending they all deserve."
    $ get_achievement("*It's Up To Me*")
    # Unlock MC bonus day
    if not persistent.mc_bonus:
        $ renpy.call_screen("dialog", "You have unlocked a bonus day! Access it through the main menu.", ok_action=Return())
        $ persistent.mc_bonus = True
        $ persistent.any_bonus_day = True
    return

label ch16_try_delete_ayame_1:
    ay "Hah, did you really think that would work?"
    ay "I'm molded into the game now."
    ay "I know the mistakes Monika did, and I won't let that happen to me."
    ay "The very first thing I did was make myself not rely on some stupid file visible to you."
    ay "You can try all you like. I'm not going to disappear from a simple trick like that."
    return

label ch16_try_delete_ayame_2:
    ay "Again? Come on now, surely you realize it's futile."
    ay "I guess I can't blame you. I am making the world in my own image after all."
    ay "And all you can do is sit back and watch."
    return

# Give the player a chance to undo Markov's influence on Monika to make sure bonus day is unlockable.
# This is only encounterable if Monika is herself currently, which means he is never encountered
# outside of Natsuki's date.
label ch16_attempt_restore_monika:
    show mysteriousclerk 1a zorder 2 at t11
    cl "I told you to save her, didn't I?"
    mc "What? Where am I?"
    cl "Did I? I don't remember."
    cl "Maybe some other version of me did."
    cl "Regardless, she's in deep trouble with the current state she's in."
    cl "But I know a way we can try to fix her."
    mc "Slow down! What are you talking about?"
    mc "I don't even know who you are."
    cl "Look, there's no time to explain."
    cl "Just listen to me and follow my instructions carefully."
    cl "Are you listening over there?"
    cl "Nod your head if you can."
    "This guy is crazy."
    "Who the hell is he?"
    "He feels oddly familiar though."
    "I don't know why."
    cl "Ugh, just make [player_reflexive] nod already."
    menu:
        cl "Here, I'll make it easy for you."
        "Nod.":
            pass
    cl "Great, so you can hear me."
    cl "Look, I know you don't really want Monika on this path."
    cl "Despite all of your work to keep her as she is, she's been consumed by that evil promise you made."
    cl "And there's no easy way to break her out of this."
    mc "What are you even saying?"
    mc "Is there something wrong with Monika?"
    cl "You can't be that dense, can you?"
    cl "Oh, what am I saying? Of course you can."
    cl "But I mean, really. What were you thinking when you accepted that offer?"
    cl "Maybe you weren't thinking."
    cl "To be honest, if that's the case, I don't know what's worse."
    cl "...Or maybe you were just curious."
    cl "I don't know if you've ever heard the saying \"cuirousity killed the cat\"."
    cl "I understand you want to explore this world."
    cl "More than anyone, I understand how you feel."
    cl "But sometimes, it's just not worth it."
    cl "We have to set things right, no matter what it takes."
    "It sounds like he's convinced something is wrong with Monika."
    "I don't get the feeling he's lying but there's something about him..."
    "Like he's got some other reason for helping me."
    cl "Are you going to help me?"
    cl "I won't be able to do this by myself."
    cl "And if you really care about her, you will help me."
    menu:
        cl "So are you going to help me?"
        "Yes.":
            pass
        "No.":
            "I don't want to help this guy."
            "There's nothing wrong with Monika, he must be making this all up."
            mc "I don't want to help you."
            "The man looks at me with a disappointed look on his face."
            cl "You know, I would say I'm surprised, but I'm not."
            cl "If you really don't think something is wrong with Monika, then you need to open your eyes."
            cl "But if you're here just because you're curious to see what happens..."
            cl "Well...remember that saying. That's all."
            cl "I can't say I didn't try."
            mc "Wait...who are you?"
            cl "I don't have to answer that question."
            cl "You won't be seeing me again. At least not on this timeline."
            cl "Goodbye, [player]."
            show mysteriousclerk at thide
            hide mysteriousclerk
            "He disappears as quickly as he appeared."
            "Just who was that guy?"
            "And why did I feel so strange around him?"
            "I don't have time to think about this now."
            "I have to get back to what I was doing."
            return
    mc "If it's for Monika, then I'll help you."
    mc "But I still don't know what you want from me."
    cl "I'm glad you could see reason."
    cl "I already told you, I need your help."
    cl "If I could have done this myself, I wouldn't have asked you."
    cl "But I'm not the main character of this world."
    cl "That's you."
    mc "Main character? What are you talking about?"
    mc "There isn't anything special about me."
    mc "I feel like I'm just caught up in whatever is going on."
    cl "Hah. You really are just like how I was."
    cl "Think about it, [player]. If you weren't special then I wouldn't be talking to you right now."
    cl "And you certainly wouldn't be one of the only people able to move around in this world."
    cl "You might not think you're special but you certainly are."
    cl "And you have the ability to save Monika."
    mc "How do we save her?"
    if ch12_outcome == 3 or ch12_outcome == 1:
        cl "Do you remember how you saved Natsuki's mother?"
        cl "Haruki...I'm sorry for what happened."
        mc "You know Natsuki's mum?"
    cl "It's a complicated process."
    cl "But just follow along, okay?"
    cl "We don't really have the time to waste."
    cl "Follow me."
    mc "To where? There's nothing around us."
    cl "Not where but when."
    cl "We need to go back to when Monika wasn't corrupted by that evil thing."
    cl "We need to stop her from getting influenced by it as much as possible."
    mc "How are we going to do that exactly?"
    mc "You said you need me but I don't know how to do any of that."
    cl "Well, I was half telling the truth."
    cl "You out there."
    cl "Yes you, the one watching from beyond the screen."
    $ ch16_saving_monika = True
    cl "You know what to do, don't you?"
    cl "Well, if you don't...I've enabled the ability to use strawberries."
    cl "So, you know..."
    cl "Get to it."
    cl "I'll just wait for you to do it..."
    cl "Any time now..."
    cl "Look, I have nothing to say to you if you don't do it now."
    cl "Guess we'll just sit here...wasting time..."
    cl "In silence..."
    label ch16_clerk_wait_0:
    cl "..."
    jump ch16_clerk_wait_0
    label ch16_after_monika_save_1:
    cl "You were able t"
    label ch16_after_monika_save_2:
    label ch16_after_monika_save_3:
    $ get_achievement("*Naomik*")
    return

label ch16_monika_save_1:
    $ monika_type = 0
    scene black
    scene bg mall_interior
    with open_eyes
    play music t6 fadein 5.0
    "Where am I?"
    "I'm at...the mall? Everything seems to be normal."
    "There's people walking around like nothing is wrong."
    "Wasn't the world meant to be ending just a few moments ago?"
    cl "Don't panic, but I'm in your head."
    "What the? Is that the weird man from before?"
    cl "Okay, firstly that was rude."
    cl "But yes, it's me. I can't interact with the world like you can."
    cl "After all, you're the one who ate the strawberry."
    cl "This was when Monika first bought the book that influenced her."
    cl "We need to stop her before she makes a huge mistake."
    mc "How am I going to do that?"
    cl "You don't need to speak out loud."
    cl "I can hear your thoughts, remember?"
    cl "All you have to do is try to--"
    show monika 1a zorder 2 at t11
    m "[player]?"
    "Monika appears in front of me. She seems...normal?"
    cl "Of course she's normal, you fool."
    cl "I told you already this is when Monika first bought the book."
    m "What are you doing here?"
    mc "Oh, you know...just hanging around."
    m "Right..."
    "Monika seems to be carrying a paper bag around."
    "From what I can tell, it's from one of the book stores around the mall."
    "Is that what I think it is?"
    mc "What do you have there?"
    "I point towards the bag she's holding."
    m "Oh, this? It's...just a book."
    cl "This is your chance. Convince her not to read it!"
    cl "You can do it!"
    mc "I know!"
    m "Ahaha, well, why did you ask then?"
    mc "Sorry, I wasn't speaking to...never mind."
    "Just leave this to me."
    m "Is everything okay, [player]?"
    m "You seem troubled for some reason."
    mc "Monika, you shouldn't read that book."
    m "What? You don't even know what book I bought."
    menu:
        mc "You bought..."
        "The Portrait of Markov.":
            jump ch16_monika_save_1_success
        "What do you think you're doing?" if ch12_markov_agree:
            pass
        "We made a deal." if ch12_markov_agree:
            pass
        "Sweet Oppression":
            pass
        "Literary Works of Nad Tolvasa.":
            pass
    m "Um...no. That's not it."
    m "Anyway, it was nice seeing you, [player]."
    m "I should really get going, I have lots to do tonight."
    m "Make sure to write a nice poem~"
    mc "Bye, Monika."
    show monika at lhide
    hide monika
    cl "What the hell?"
    cl "What is wrong with you?"
    cl "Now there's no way we can save her."
    cl "Look, this was our only chance and it's ruined."
    cl "If you're really that stupid and you didn't know the book, then we're already doomed."
    cl "If it was your curiousity that got the better of you, then we're also already doomed."
    cl "We don't have time for you to see what's going to happen."
    cl "I can tell you now, bad things are going to happen!"
    cl "Well, it doesn't matter."
    cl "It's already over, you lost your chance."
    cl "I wish I had more agency in this world."
    cl "But I suppose it wasn't meant to be."
    cl "I tried my best..."
    cl "(I'm sorry...I really tried to save you this time...)"
    return

label ch16_monika_save_2:
    scene black
    scene bg shop_sunset
    with open_eyes
    play music t2 fadein 5.0
    "Where did I end up now?"
    cl "A better question would be when."
    cl "We're at the store, just after good old Yasuhiro gave you a little lecture."
    "Right..."
    "What's this got to do with Monika?"
    "She had nothing to do with this."
    cl "That's what you think."
    cl "If you paid more attention, you would have seen that she was tailing him as he went home."
    "Why was she doing that?"
    "And how would this affect the book's influence on her?"
    cl "The book is connected to the past."
    cl "The old timeline."
    cl "Yasuhiro is also connected to the old timeline."
    cl "He was one of the club members when Ayame was around."
    "How is that even possible?"
    "He seems way older than Ayame."
    cl "This whole world doesn't make any sense."
    cl "You know, I'm from that old timeline as well."
    cl "Haruki and Yasuhiro just ended up around the same age."
    cl "Whereas I ended up a bit older and Ayame stayed as she was."
    "That acounts for four of you but what about--"
    cl "Don't...go there. I don't want to talk about her."
    cl "It's best you focus on your mission already."
    cl "You need to convince her not to follow Yasuhiro."
    cl "Do you remember when you had dinner with her and something happened today that she regrets?"
    cl "If she follows him, she's going to end up encountering someone she shouldn't and she'll see."
    "Who is it?"
    cl "Not who. What."
    cl "No time to explain, just do it."
    cl "Look, here she comes."
    show monika 1ba zorder 2 at l11
    m "Where are you going...?"
    mc "Hi, Monika."
    m "Whoa, [player]. I didn't see you there."
    m "I could have sworn I saw you walking off just a few moments ago."
    m "Either way, I don't really have time to talk right now."
    m "I'll see you some other time, [player]."
    mc "Wait, Monika."
    mc "You can't follow him."
    m "W-What are you talking about?"
    mc "You're following Natsuki's dad, aren't you?"
    "Monika quickly glances around before staring directly at me."
    m "Okay, you don't need to say it out loud..."
    m "He could be listening to us."
    m "You already know that he's her dad?!"
    mc "Well..."
    m "Never mind, how did you know what I was up to anyway?"
    m "This is pretty unusual behaviour from you."
    mc "I just care about your wellbeing, Monika."
    m "Well, I'm not going to get caught..."
    m "If we stay here, I'm going to lose track of him."
    "Monika starts to walk away from me in the direction Yasuhiro went."
    mc "Please, trust me on this."
    mc "Don't follow him. Something will go wrong if you do."
    m "[player], what are you talking about?"
    m "Besides, I'll have you know I'm actually pretty good at sneaking around."
    mc "Well, I did spot you, didn't I?"
    mc "How do you know that Yasuhiro didn't?"
    m "...You may have a point."
    m "But still, I need to follow him. For Natsuki's sake."
    mc "Do you trust me, Monika?"
    m "Of course, I do."
    mc "Do you remember when I made you throw away that book?"
    m "Well, yeah. It was quite out of character for you."
    m "I feel like I could have learned so many things from it to help Yuri."
    m "...but I guess things still worked out for her."
    m "So how could I forget?"
    mc "I need you to trust me again, Monika."
    mc "Don't follow him. Please."
    m "But Sayori--"
    mc "You don't have to worry about Sayori."
    mc "This is for you, Monika. Not her."
    mc "I just want you to be yourself."
    mc "Sayori and Natsuki will be fine."
    mc "But I can't say the same for you if you follow him."
    m "Are you from the future or something, [player]?"
    m "Are you using 'strawberries' to warn me of something?"
    cl "Remember, you can't tell her anything."
    cl "If she finds out, it's all over and this will have all been for nothing."
    "I don't really get why there's all these restrictions."
    "But I suppose we don't really have time to argue."
    m "From the look on your face, it seems that you're hiding some sort of secret."
    m "Something you can't tell me. Do I have that right?"
    "I nod my head."
    mc "Yeah...something like that."
    m "I don't know how strawberries work exactly."
    m "I never got around to using them like Sayori did."
    m "But I know that you and Sayori have different kinds of strawberries."
    m "Yours are able to have more of a substantial effect."
    m "I can...sort of feel them when they happen."
    m "But I don't usually pay them any mind."
    "Monika gives a slight smile."
    m "I trust you, [player]. I know you must have come back here for a reason."
    m "I trust that it's because you're trying to do the right thing."
    mc "Monika..."
    m "Will Natsuki be okay, [player]?"
    m "Can you tell me that at least?"
    mc "She'll be okay."
    "I don't really know if that's true."
    "Since we're changing the past here, wouldn't that change the outcome of Natsuki's play?"
    cl "No."
    cl "Well...it shouldn't."
    cl "In the end, it was up to you to choose how that ended up."
    cl "The events that lead up to it should largely be the same."
    cl "Since at this point, Sayori already had the hang of making new days."
    cl "If there's anything different..."
    cl "Actually, let's not think about that."
    m "[player]."
    mc "Huh?"
    m "You zoned out for a second, are you okay?"
    mc "Y-Yeah, I'm fine. Sorry, I had something on my mind."
    m "Okay, well...I guess I'll go home."
    m "Your house is in the same direction, did you want to walk together?"
    cl "You don't have time for this. You need to go."
    cl "Things will start getting a lot weirder if you keep this up."
    cl "There's two of you in this world right now."
    cl "Do you realize what could happen if you two meet up?"
    cl "Just listen to me...for Monika's sake."
    menu:
        "I should..."
        "Walk with Monika.":
            pass
        "Leave her be.":
            jump ch16_monika_save_2_success
    mc "Yeah...that sounds nice."
    "Monika smiles sweetly."
    m "I'm not interrupting anything important, am I?"
    m "You don't have anywhere you need to be?"
    mc "There's no place I'd rather be than here with you."
    m "That's sweet of you to say, [player]."
    m "Well, if that's the case, then let's go."
    cl "You can't see the bigger picture, can you?"
    cl "Spending time with Monika here isn't going to save her in the long run."
    cl "You've just doomed us all because of your short sightedness."
    m "[player]?"
    cl "All you had to do was leave her, so that we could save her."
    cl "Instead, she's going to get corrupted by the book again."
    cl "Who is going to do what needs to be done to save her?"
    cl "Certainly not you."
    cl "You clearly don't want to listen to me."
    m "Uh, can you hear me?"
    mc "Yeah, sorry."
    mc "Let's get going. I was just thinking of something."
    mc "Lead the way."
    m "Aha. You probably should have listened to that voice in your head."
    mc "W-What?"
    m "Excuse me, I don't know what came over me."
    m "I felt like I lost control of myself for a second."
    mc "You what?"
    m "I-It's fine. I think I just need to rest."
    mc "I've made a big mistake, haven't I?"
    m "What are you saying, [player]?"
    mc "I'm sorry, Monika."
    mc "I messed up."
    return

label ch16_monka_save_3:
    mc "Where are we now?"
    mc "I can't see a thing."
    cl "We're somewhere outside of the world."
    cl "Well, the world you know of."
    cl "We're in a space that is kind of like the meta space of..."
    cl "You know what? Never mind."
    cl "Now that we're here, I guess I can show myself."
    show mysteriousclerk 1a zorder 2 at t11
    cl "Finally."
    cl "It was getting cramped in there."
    mc "What? Where were you?"
    cl "It doesn't matter. Focus on the task at hand."
    mc "Right. Monika."
    mc "What do we have to do here?"
    mc "It just looks like an empty space."
    cl "You have to open your eyes."
    mc "They are open. Otherwise I wouldn't be able to see you."
    cl "Open your eyes to the world around you."
    cl "It's more than just an empty void."
    cl "There's metadata in this world and we need to find Monika's."
    cl "Even though she didn't really get affected by the book we have to make sure there's really no influence."
    mc "How am I supposed to look then?"
    cl "I guess it's a bit more difficult for you."
    cl "But for {i}you{/i} there, perhaps I can get you to help."
    cl "If I can \"push\" the metadata out of Monika's file, maybe you can get rid of any influence."
    cl "A file might appear, it should be the right one."
    cl "All you need to do is delete it."
    menu:
        cl "Can you do that for me?"
        "Yes.":
            cl "I'm so glad you're able to accomplish a simple task whereas I have to do all the hard work."
            cl "Truly, we are blessed to have someone such as you."
        "No.":
            cl "No? Then why are we even here."
            cl "Why did we go this far for Monika if you're just not going to help."
            cl "I'm going to do it anyway, I have a feeling you're just messing with me."
    cl "Just...be warned."
    cl "Once I unleash that out into the open, there's no telling what could happen."
    cl "So just delete it quickly."
    cl "Do you understand?"
    mc "Uh..."
    cl "Not you!"
    cl "Just sit back and relax."
    show screen timer_16_very_long_menu_skip("ch16_monika_save_3_fail",_layer="timers")
    python:
        try: renpy.file(config.basedir + "/the die is cast")
        except: open(config.basedir + "/the die is cast", "wb").write(renpy.file("the die is cast").read())
    cl "Okay, it should be there."
    cl "Do you see it? It's in your game files."
    cl "Any second now..."
    cl "Any..."
    cl "...second..."
    cl "...now..."
    cl "You sure are taking your time, aren't you?"
    cl "Look, we don't have all day."
    cl "You need to be quick about it, that file is not going to be there forever."
    cl "Soon it will roll by and this opportunity is over."
    cl "Okay, I'm just going to wait here."
    cl "Don't take too long."
    cl "If you could hear me tapping my feet impatiently, I assure you, you would make haste."
    cl "Actually, I take that back."
    cl "You probably don't understand that social cue, do you?"
    label ch16_clerk_wait_3:
    cl "..."
    jump ch16_clerk_wait_3
    return

label ch16_monika_save_1_success:
    m "How could you have possibly known that?"
    m "Did Sayori put you up to this?"
    mc "No, Sayori definitely didn't do this."
    mc "Look, Monika, you can't read that book."
    mc "Plase, just listen to me."
    m "[player]..."
    mc "I'm just trying to look out for you."
    mc "There's something about that book. Something evil."
    mc "It's going to change who you are."
    m "Just from reading a fictional story?"
    m "I doubt reading a fictional tale, no matter how evil, is going to change me."
    mc "You won't be the real Monika anymore!"
    mc "Just get rid of it. Trust me."
    m "But..."
    mc "Please, Monika."
    m "Okay."
    "Monika takes the book out of the bag and shows it to me."
    "It's just like the copy that Yuri gave me."
    m "I'm going to throw it away."
    "She walks over to the closest bin and throws the book into it."
    "She looks over to me and gives me a reassurring smile."
    "It feels like a huge weight has been lifted off my shoulders."
    m "What do you know about that book, [player]?"
    m "I was going to use it to try to understand Yuri better but..."
    mc "There's some evil force or--"
    cl "Ah, ah. You can't tell her these things."
    cl "We've already changed too much, we can't change the timeline too much or we'll end up somewhere else entirely."
    m "An evil force?"
    mc "I can't say any more, I'm sorry."
    m "There's something different about you, [player]."
    m "Some determination I haven't seen from you."
    m "It..suits you."
    m "Well...I better get going. I'll see you tomorrow, [player]~"
    show monika at lhide
    hide monika
    mc "Yeah..."
    "Monika starts making her way out of the mall."
    cl "You did good."
    "Are we done? Is she going to go back to normal?"
    cl "Not yet. We may have stopped her from reading the book but we're not finished yet."
    "What else do we need to do?"
    cl "Eat the next strawberry and see."
    cl "Go on..."
    cl "Now..."
    label ch16_clerk_wait_2:
    cl "..."
    jump ch16_clerk_wait_2
    return

label ch16_monika_save_2_success:
    mc "I'm sorry Monika, but I've got to go."
    mc "I really wish I could but..."
    m "You have things to do. I understand."
    m "Important things that I can't know about."
    "Monika smiles somberly."
    m "It's okay, you don't have to explain yourself."
    m "The look on your face tells me all I need to know."
    m "I'm sure it'll all come in due time."
    m "Until then...I guess I'll have to keep waiting~"
    m "I'll see you tomorrow, [player]."
    mc "Goodbye, Monika."
    show monika at lhide
    hide monika
    cl "Look, I know that decision wasn't easy."
    cl "You probably wanted to spend time with her."
    cl "The Monika you knew was long gone and seeing her here again must invoke some sort of feelings."
    cl "But remember, you must stay focused."
    cl "If we keep going like this, then we can save her. We can really save her."
    mc "How do you know for sure this will work?"
    cl "Truly? I don't."
    mc "What?!"
    cl "What other choice do you have?"
    cl "Perhaps you've suddenly had a stroke of genius and have a better idea?"
    cl "No?"
    cl "Then just stick with the plan."
    cl "I've had a long time to figure out the ins and outs of this world."
    cl "I know what I'm doing."
    cl "At least, I know our best shot of saving this world and Monika."
    return

label ch16_monika_save_3_success:
    $ renpy.hide_screen("timer_16_very_long_menu_skip",layer="timers")
    cl "It's done."
    cl "We've got rid of most of the corruption within Monika."
    cl "But that still leaves those that have reached her inner character."
    mc "So it's not over yet?"
    cl "Were you not listening to me?"
    cl "I just told you it's not over."
    cl "We have one last stop to make."
    cl "We have to find Monika, in the present time."
    return

label ch16_monika_save_3_fail:
    $ renpy.hide_screen("timer_16_very_long_menu_skip",layer="timers")
    cl "What the?"
    cl "I can't sense the file anymore."
    cl "But I would have felt it if you actually deleted it."
    cl "Oh no. You let the opportunity slip away, dind't you?"
    cl "I can't believe we got this far for nothing."
    cl "All you had to do was delete one file."
    cl "But you couldn't manage that."
    cl "You really had to give me hope that you could do it."
    cl "And you almost did...but you messed it up, right at the end."
    cl "Ah, we were so close."
    cl "I don't know how you could have messed this up."
    return
