label natsuki_exclusive_1:
    scene bg club_day
    with wipeleft_scene
    n "Ugh...!"
    "I hear Natsuki utter an exasperated sigh from within the closet."
    "She seems to be annoyed by something."
    "I approach her, in case she needs a hand."
    play music t6 fadeout 1
    scene bg closet
    show natsuki 4r zorder 2 at t11
    with wipeleft_scene
    mc "You looking for something in there?"
    n 4x "Freaking Monika..."
    n "She never puts my stuff back in the right spot!"
    n "What's the point in keeping your collection organized if someone else is just gonna mess it up?"
    "Natsuki slides a bunch of stacked books and boxes across the shelf."
    mc "Manga..."
    n 2c "You read manga, right?"
    mc "Ah--"
    mc "...Sometimes..."
    "Manga is one of those things where you can't admit you're really into it until you figure out where the other person stands."
    mc "...How did you know, anyway?"
    n 2k "I heard you bring it up at some point."
    n "Besides, it's kind of written on your face."
    "What's that supposed to mean...?"
    mc "I-I see..."
    "There's a lone volume of manga amidst a stack of various books on the side of one of the shelves."
    "Curious, I pull it out of the stack."
    n 1b "{i}There{/i} it is!"
    "Natsuki snatches it out of my hand."
    "She then turns to a box of manga and slips the volume right into the middle of the rest."
    n 4d "Aah, much better!"
    n "Seeing a box set with one book missing is probably the most irritating sight in the world."
    mc "I know that feel..."
    "I get a closer look at the box set she's admiring."
    mc "Parfait Girls...?"
    "It's a series I've never heard of in my life."
    "That probably means it's either way out of my demographic, or it's simply terrible."
    n 5g "If you're gonna judge, you can go do it through the glass on that door."
    "She points to the classroom door."
    mc "H-Hey, I wasn't judging anything...!"
    mc "I didn't even say anything."
    n 5c "It was the tone of your voice."
    n "But I'll tell you one thing, [player]."
    n 4l "Consider this a lesson straight from the Literature Club: Don't judge a book by its cover!"
    n "In fact--"
    "Natsuki pulls out the first volume of Parfait Girls from the box."
    n "I'm gonna show you exactly why!"
    "She shoves the book right into my hands."
    mc "Ah..."
    "I stare at the cover."
    "It features four girls in colorful attire striking animated feminine poses."
    "It's...exceedingly \"moe\"."
    n 4b "Don't just stand there!"
    mc "Uwa--"
    show natsuki zorder 1 at thide
    hide natsuki
    "Natsuki grabs my arm and pulls me out of the closet."
    "She then takes a seat against the wall, beneath the windowsills."
    "She pats on the ground next to her, signaling me to sit there."
    show bg club_day
    show natsuki 2a zorder 2 at t11
    with wipeleft
    mc "Wouldn't chairs be more comfortable...?"
    "I take my seat."
    n 2k "Chairs wouldn't work."
    n "We can't read at the same time like that."
    mc "Eh? Why's that?"
    mc "Ah...I guess it's easier to be close together like this..."
    n 2o "--!"
    n 5r "D-Don't just say that!"
    n "You'll make me feel weird about it!"
    "Natsuki crosses her arms and scootches an inch away from me."
    mc "Sorry..."
    show natsuki 5g
    "I didn't exactly expect to be sitting this close to her, either..."
    "Not that I can say it's a particularly bad thing."
    "I open the book."
    "It's only a few seconds before Natsuki once again inches closer, reclaiming the additional space while she hopes I won't notice."
    "I can feel her peering over my shoulder, much more eager to begin reading than I am."
    n 1k "Wow, how long has it been since I read the beginning...?"
    mc "Hm?"
    mc "You don't go back and flip through the older volumes every now and then?"
    n 2k "Not really."
    n "Maybe sometimes after I've already finished the series."
    n 2c "Hey, are you paying attention?"
    mc "Uh..."
    "I am, but nothing's really happened yet, so I can talk at the same time."
    "It looks like it's about a bunch of friends in high school."
    "Typical slice-of-life affair."
    "I kind of grew out of these, since it's rare for the writing to be entertaining enough to make up for the lack of plot."
    mc "So..."
    mc "What should I expect from this?"
    mc "Is there going to be plot?"
    n 4w "Well, obviously!"
    n "You think I would enjoy something that didn't have a plot?"
    n 4c "I mean..."
    n 2c "Well, I guess I know what you're saying..."
    n 2k "A lot of the beginning is about simple things..."
    n "Like there's a really funny chapter where they're obsessed with a guy at the ice cream shop..."
    n 2c "But that just helps you get to know the characters!"
    n "And besides, it's still entertaining."
    n 2d "But later on, there's all kinds of drama..."
    n "Like when they get into all their backstories, and when some of the romance starts to happen..."
    n "That's really what makes it so good."
    n 2a "There are so many touching parts."
    mc "Ah, is that so?"
    mc "It sounds like you really know what you're talking about."
    mc "Maybe I underestimated you."
    n 2z "Ehehe."
    n 1f "...Hey, wait!"
    n "What's {i}that{/i} supposed to mean?!"
    mc "Uwa--"
    "Natsuki gives me a little shove."
    mc "I just meant that I haven't yet seen you at your full power..."
    n 5s "Hmph. Good save."
    mc "Ah... This chapter seems like it's about baking."
    mc "This is just a guess, but is there a lot of baking in this manga?"
    n 5b "Well--"
    "Natsuki pauses for a moment, as if she doesn't want to admit something."
    n 2q "...Yeah."
    n "Why does that matter?"
    mc "It doesn't, I was just curious..."
    mc "Since you enjoy baking too, right?"
    n 1o "That's--"
    n "Just a coincidence!"
    n 1t "I just happened to get into baking around the same time I got this manga."
    n "Like I would ever get into anything because it's in a manga."
    n 4y "I feel bad for anyone that impressionable."
    n "Ahaha!"
    "Definitely not a coincidence..."
    "I guess that explains Natsuki's interest in baking."
    "Still, of all the hobbies to pick up from a manga, that's definitely one of the better ones."
    "Not to mention she's really good at it, so who am I to judge?"
    $ persistent.clear[0] = True
    $ renpy.save_persistent()
    scene n_cg1_bg
    show n_cg1_base
    with dissolve_cg
    "..."
    "We read on for a few more minutes."
    "I've finished a couple chapters at this point."
    mc "..."
    mc "...Are you sure this isn't boring for you?"
    n "It's not!"
    mc "Even though you're just watching me read?"
    n "Well...!"
    n "I'm...fine with that."
    mc "If you say so..."
    mc "...I guess it's fun sharing something you like with someone else."
    mc "I always get excited when I convince any of my friends to pick up a series I enjoy."
    mc "You know what I mean?"
    n "...?"
    mc "Hm?"
    mc "You don't?"
    show n_cg1_exp2 at cgfade
    n "Um..."
    n "That's not..."
    n "Well, I wouldn't really know."
    mc "...What do you mean?"
    mc "Don't you share your manga with your friends?"
    hide n_cg1_exp2
    show n_cg1_exp3 at cgfade
    n "Could you not rub it in?"
    n "Jeez..."
    mc "Ah... Sorry..."
    n "Hmph."
    n "Like I could ever get my friends to read this..."
    n "They just think manga is for kids."
    n "I can't even bring it up without them being all like..."
    n "'Eh? You still haven't grown out of that yet?'"
    n "Makes me want to punch them in the face..."
    mc "Urgh, I know those kinds of people..."
    mc "Honestly, it takes a lot of effort to find friends who don't judge, much less friends who are also into it..."
    mc "I'm already kind of a loser, so I guess I gravitated toward the other losers over time."
    mc "But it's probably harder for someone like you..."
    hide n_cg1_exp3
    n "Hm."
    n "Yeah, that's pretty accurate."
    "{i}...Wait, which part??{/i}"
    n "I mean, I feel like I can't even keep it in my own room..."
    n "I don't even know what my dad would do if he found this."
    n "At least it's safe here in the clubroom."
    show n_cg1_exp3 at cgfade
    n "'Cept Monika was kind of a jerk about it..."
    n "Ugh! I just can't win, can I?"
    mc "Well, it paid off in the end, didn't it?"
    mc "I mean, here I am, reading it."
    n "Well, it's not like that solves any of my problems."
    mc "Maybe..."
    mc "But at least you're enjoying yourself, right?"
    hide n_cg1_exp3
    show n_cg1_exp2 at cgfade
    n "--"
    n "..."
    n "...So?"
    mc "Ahaha."
    hide n_cg1_exp2
    show n_cg1_exp3 at cgfade
    n "Jeez, that's enough!"
    n "Are you gonna keep reading, or what?"
    mc "Yeah, yeah..."
    "I flip the page."
    "Suddenly, Natsuki starts laughing."
    hide n_cg1_exp3
    show n_cg1_exp1 at cgfade
    n "Ahahaha!"
    n "I totally forgot that happens!"
    "Natsuki puts her finger on one of the panels."
    n "Minori is my favorite character."
    n "You always feel a little bad for her, since she's so unlucky."
    n "But it gets especially bad when--"
    hide n_cg1_exp1
    n "Uu..."
    n "I shouldn't be talking about that yet!"
    n "Just finish this chapter!"
    scene bg club_day
    with dissolve_cg
    "Natsuki's voice sparkles with excitement."
    "It's a stark contrast to her usual bossy tone."
    "But if she's not used to sharing her favorite manga with her friends, I can understand why."
    "It's hard to express in words the feeling you get when connecting with someone like that."
    "And being able to provide that to Natsuki, for whom it's a rare experience..."
    "The thought makes me smile a little to myself."
    show monika 4b zorder 3 at f21
    m "Okay, everyone!"
    mc "Eh?"
    m "Are you all ready with today's poems?"
    mc "..."
    show monika zorder 2 at t21
    show natsuki 4w zorder 3 at f22
    n "Oh, come on!"
    n "Could your timing be any worse?"
    show natsuki zorder 2 at t22
    show monika zorder 3 at f21
    m 5 "Sorry~!"
    m "I just need to make sure we have enough time."
    m "Though you do look pretty cozy over there. Ahaha!"
    show monika zorder 2 at t21
    show natsuki zorder 3 at f22
    n 4o "Eh...?"
    n 1p "A-Ah!"
    "Natsuki suddenly notices how close she's gotten to me."
    "She hastily slides herself a good twelve inches away from me."
    show monika zorder 1 at thide
    show natsuki 1s zorder 2 at t11
    hide monika
    mc "Alright..."
    mc "Guess I'll stop here for now."
    "I close the book and hand it towards Natsuki."
    n 2m "You're just giving it back...?"
    n "Don't you want to know what happens?"
    mc "Ah... Yeah, but..."
    mc "Monika just said--"
    n 2u "Don't be dumb."
    n "Just take it home with you."
    mc "Eh?"
    mc "...Is that really alright?"
    "I say that mostly because I really didn't plan on using my spare time to read this..."
    n 4h "Well, of course."
    n "It would take forever to finish if you didn't take it home."
    n "Just finish that one before tomorrow, so we can start the next one."
    n 4g "And if it gets bent, I'll kill you."
    mc "By tomorrow...?"
    show natsuki zorder 1 at thide
    hide natsuki
    "I only got partway through the volume so far."
    "I might fall behind on some shows if I try to get through this..."
    "But I suppose that's a necessary sacrifice in exchange for seeing Natsuki's enthusiastic face."
    "Or am I more scared of what will happen if I {i}don't{/i} finish it...?"
    mc "Alright, then!"
    "I stand up."
    "I return to where I put my stuff and carefully slip the book into my bag."
    return


label natsuki_exclusive_2:
    $ n_exclusivewatched = True
    play music t6 fadeout 1
    scene bg club_day
    show natsuki 4c zorder 2 at t11
    with wipeleft_scene
    n "..."
    "It's not long before Natsuki comes up to me expectantly."
    mc "Yeah, yeah."
    mc "Don't worry, I kept my promise."
label natsuki_exclusive_2_ch3:
    "I pull the first volume of Parfait Girls out from my bag."
    "Natsuki takes it from my hands, then quickly turns it over, presumably to check for wrinkles."
    mc "Hey, I'm not that careless..."
    mc "I handle manga all the time, you know."
    n 1m "I just wanted to make sure!"
    n 1c "Can you blame me for being paranoid?"
    n "I don't give people my manga every day, you know."
    mc "That's true..."
    mc "I don't blame you."
    n 2j "Well anyway, let me put this one back."
    n "I'm gonna get the next one, okay?"
    show natsuki zorder 1 at thide
    hide natsuki
    "Natsuki makes her way to the closet."
    "I follow."
    show bg closet
    show natsuki 2l zorder 2 at t11
    with wipeleft
    n "So you're gonna tell me everything you thought, right??"
    n 2k "Where did this volume leave off again? I forget."
    mc "Ah, the chapter ended when Minori and Alice found--"
    show natsuki 1e at h11
    n "{i}Monika!!{/i}"
    "Natsuki's voice resonates out from inside the closet."
    mc "Eh...?"
    "I peer inside."
    "All of Natsuki's books are lined up on the top shelf."
    n "Did you move my manga again?!"
    show monika 3l at l31
    m "Ah, sorry, sorry!"
    m "The teacher got mad at me for taking up so much space in her closet..."
    m "So I had to move some stuff around and clean up a little bit."
    m 3b "It's all still there, I just had to organize it a bit!"
    show monika zorder 1 at thide
    hide monika
    n 1r "Ugh..."
    "The top shelf is far above Natsuki's head."
    show natsuki at h11
    "She makes a futile hop, trying to figure out how to reach her manga."
    n 1q "Jeez...!"
    n "This is so inconvenient!"
    n 1c "I'm moving these all back down."
    n "There's plenty of room on these shelves."
    n "And besides..."
    n 4w "They're really pretty to look at when they're all lined up!"
    n "Why would you waste that on the top shelf?"
    mc "Ah, Natsuki..."
    mc "There's a stool on the wall there."
    "In the closet, there's a collapsible stool that's hanging on the wall."
    mc "If you want, I can reach up there and hand them to you..."
    n 1g "I can get them myself!"
    "Natsuki grabs the stool from the wall and unfolds it."
    n "You think I'm too short or something?"
    mc "I mean--"
    n 5x "I {i}knew{/i} it!"
    n 5w "Well, you know what?"
    n "Just watch me!"
    "Natsuki hops onto the stool, which ends up being a little wobbly because of its collapsible design."
    n 1f "A-Ah..."
    mc "Careful..."
    n 1r "I know what I'm doing!!"
    "Standing on the stool, Natsuki's fingertips reach the top shelf."
    "The stool would be enough for me to easily grab the books, but Natsuki is being stubborn as usual."
    n "U-Uuuh..."
    "Natsuki uses her fingers to scoot one of the smaller boxes to the edge of the shelf."
    n 1t "See...?"
    n 1v "Kyah--!"
    "The box suddenly tips."
    "Natsuki barely catches it before it falls to the floor."
    "The stool wobbles."
    show natsuki at h11
    n "Wawaa--"
    "Losing balance, Natsuki hops off the stool."
    "Thankfully, she was able to stay on her feet."
    "She holds the box triumphantly."
    n 4y "T-There!"
    "Having almost fell, Natsuki is a bit shaken up."
    mc "Jeez..."
    mc "No need to prove yourself to me."
    mc "There's no way you'll be able to get the bigger boxes like that."
    mc "I can reach them, so just--"
    n 2h "I said I can do it!"
    n "I don't want your help, okay?"
    mc "Sigh..."
    n "I'm gonna get a chair, so just hang on."
    show natsuki zorder 1 at thide
    hide natsuki
    "Natsuki forces her way past me out of the closet."
    n "Let's see..."
    "The classroom chairs have the desks attached, so they're too inconvenient to fit into the closet."
    n "Aha!"
    "Natsuki trots over to the teacher's desk, which has a computer chair behind it."
    "She rolls it on its wheels back over to the closet."
    show natsuki 4a zorder 2 at t11
    mc "Ah--"
    "It's a little dangerous, since the chair swivels and rolls."
    "But I've already learned my lesson, so I keep my mouth shut."
    n 1 "Ush--"
    "Natsuki climbs onto the chair, then slowly balances onto her feet."
    "Since she refuses my help, I take a seat with my back against the side of the doorway and simply watch."
    $ persistent.clear[1] = True
    $ renpy.save_persistent()
    scene n_cg2_bg
    show n_cg2_base
    with dissolve_cg
    n "Aha! There we go!"
    n "See? I can easily do it now."
    "Natsuki grabs a stack of manga and bends down to put it on the shelf below."
    show n_cg2_base at n_cg2_wiggle
    n "W-Wahh--"
    "The chair swivels."
    "Natsuki catches herself on the shelf."
    show n_cg2_exp1 at cgfade
    n "What are you doing??"
    n "Can you at least hold the chair steady instead of sitting and doing nothing?"
    "{i}(Who was it who told me not to help...?){/i}"
    mc "Yeah, yeah...I got you."
    hide n_cg2_exp1
    "I hold the chair while Natsuki reaches back up."
    mc "--!"
    "I can..."
    "{i}I can almost see up her skirt?!{/i}"
    mc "Guh--"
    "I force myself to turn away."
    "Natsuki seriously didn't think this through...!"
    "Once she realizes, I'll be dead!"
    show n_cg2_base at n_cg2_wiggle
    n "Hup--"
    "Natsuki wraps her arms around the Parfait Girls box set, easily the largest one on the shelf."
    n "Uu...heavy..."
    show n_cg2_exp1 at cgfade
    n "Hey, [player]..."
    n "I-I don't think I can bend down without falling...!"
    n "Hurry and take this one..."
    mc "Eh?"
    mc "But then I have to let go of the chair..."
    n "That's fine...!"
    n "Just for a second!"
    n "Hurry up..."
    mc "Alright...!"
    mc "Let me just stand up."
    "I slowly release my grip from the chair."
    n "What do you mean 'stand up'?"
    "Natsuki looks down at me."
    n "Why are you all the way back--"
    stop music fadeout 1
    n "E-Eh...?"
    "Natsuki looks like she just realized something, but she'll lose her balance if she moves."
    mc "Natsuki, the box--"
    play music t7
    show n_cg2_exp2 at cgfade
    n "{i}W-What are you looking at?!{/i}"
    mc "--!"
    show n_cg2_base at n_cg2_wiggle_loop
    show n_cg2_exp1 at n_cg2_wiggle_loop
    show n_cg2_exp2 at n_cg2_wiggle_loop
    n "You're trying to look at my...m-my..."
    "Natsuki's legs shake."
    mc "I-I'm not! I was just--"
    mc "--Natsuki, don't try to move!"
    mc "Just give me the box!"
    n "You...you perv!"
    n "You set me up!!"
    n "Go away!"
    n "Get out!"
    mc "But--"
    n "I'll do it myself!!"
    hide n_cg2_exp2
    n "A-Ah--"
    "The chair suddenly swivels beneath Natsuki's feet."
    mc "Natsuki--!"
    show n_cg2_base at n_cg2_wiggle_loop
    show n_cg2_exp1 at n_cg2_wiggle_loop
    show n_cg2_exp2 at n_cg2_wiggle_loop
    n "{i}Kyaaaaa!{/i}"
    "The scene turns to chaos in a split second."
    "The chair flies from under Natsuki's feet."
    "Frantically, I try to catch her."
    "The box topples out of her hands, and the books go flying."
    mc "I got you--"
    show n_cg2_base at n_cg2_zoom
    show n_cg2_exp1 at n_cg2_zoom
    show n_cg2_exp2 at n_cg2_zoom
    show black:
        alpha 0
        0.10
        linear 0.10 alpha 1
    $ pause(0.20)
    stop music
    play sound "sfx/fall2.ogg"
    "{i}Crash!{/i}"
    "The full force of Natsuki's body against me throws me to the ground."
    "A whole bunch of books pelt me in the face."
    "Natsuki tries to shield herself with her own arms as her face lands straight on my chest."
    mc "Ungh..."
    "My right arm and my back seriously felt the impact."
    play music t8 fadeout 1.0
    scene bg closet
    show natsuki 1v at face
    with dissolve_cg
    n "U-Uu..."
    "Slowly, Natsuki comes to her senses."
    mc "Ghk--!"
    "She presses her arms straight into me to prop herself up."
    n 1h "Eh...?"
    "Natsuki seems to realize that it's not the floor that's beneath her."
    n 1o "G-Guuuuu...!!"
    n "Gross! Gross!"
    mc "Ghak--!"
    "A fist pounds into my chest."
    "Natsuki then hoists herself to her feet."
    show natsuki 1x zorder 2 at t11
    n "What were you thinking?!"
    n "You sicko!"
    show monika 1d zorder 3 at f31
    m "Everything okay over there...?"
    m "I heard a loud noise..."
    "Monika suddenly peers in."
    show monika zorder 2 at t31
    show natsuki zorder 3 at f11
    n 1e "Monika!"
    n "See what happens when you put the manga on the top shelf?!"
    n 1w "Are you trying to kill your club members or something?"
    n "Jeez!"
    show natsuki zorder 2 at t11
    show monika zorder 3 at f31
    m 5 "S-Sorry, sorry!"
    m "Ahaha..."
    show monika zorder 2 at t31
    show natsuki zorder 3 at f11
    n 5r "Oh, and one more thing."
    n "It seems like your most recent club member is a total pervert."
    n "So I hope you're happy."
    show natsuki zorder 2 at t11
    mc "I didn't--!"
    "Somehow, it's impossible for me to explain this whole bizarre situation to Monika."
    mc "I didn't do anything, I swear...!"
    show monika zorder 3 at f31
    m 1l "I know, I know, don't worry~"
    show monika zorder 1 at thide
    hide monika
    "Monika says that quietly to me."
    "Looks like I'm off the hook..."
    stop music fadeout 1
    n 1p "Oh no...!"
    n "My...my..."
    show natsuki 1m
    mc "Eh?"
    "I look down."
    "Natsuki is kneeling on the floor, holding one of the books that are scattered all over."
    "There's a large diagonal crease along the page that she's desperately trying to smooth out."
    mc "Ah, it must have landed on the page..."
    stop music fadeout 1
    "Natsuki tries a bit more to fix the crease, but she can't get it out."
    show natsuki 12b
    "Suddenly, she gives up and slams the book shut, then throws it to the floor."
    "Instead of continuing to yell, she just lowers her head."
    play music t9
    show natsuki 12d at s11
    n "{i}*Sob*{/i}"
    mc "...Natsuki, are you--"
    show natsuki zorder 2 at t11
    n 12f "No!"
    "Natsuki's voice squeaks."
    "I see tears on her face."
    mc "Ah..."
    mc "I'll help get the crease out, okay?"
    mc "It's partially my fault, so..."
    "Natsuki shakes her head, still looking down."
    n "No..."
    n "I don't even care that much..."
    n "I'm just..."
    n "Having a really bad day today..."
    "Natsuki sobs again."
    n 12i "I didn't mean to take it out on you..."
    n "I really didn't mean to!"
    mc "It's...it's fine."
    mc "...Is there anything you want to talk about?"
    show natsuki 12f
    "Natsuki shakes her head."
    n "Just..."
    n "Every day..."
    n "...is...so hard."
    n "I just want to..."
    n "...come to the club and..."
    n "..."
    "Natsuki falls silent again."
    "I can't press her, so I can only do what I know how to do."
    mc "Alright..."
    mc "Well, I'll help clean this up."
    mc "And I'll move the rest of your manga for you."
    mc "Ah."
    "I pick up volume 2 of Parfait Girls."
    mc "We'll set this one aside."
    mc "This'll help cheer you up a bit, right?"
    mc "We can get started on it once I'm done here."
    show natsuki 12h
    "Natsuki looks up with her glossy eyes."
    "Her lip quivers."
    n "You're..."
    n "You're really nice to me..."
    mc "Eh?"
    "That sounds really strange, coming from Natsuki."
    "I didn't expect it at all."
    mc "Well..."
    mc "I'm just treating you like a friend, you know?"
    n 12f "Nn..."
    show natsuki at thide
    hide natsuki
    "Natsuki lowers her head and stifles another sob."
    "I'm not sure what happened to her today, but being nice is the least I could do."
    "The next couple minutes are silent between us as I begin gathering the scattered books."
    "I make sure to slip them into the box in their correct order."
    "After a little bit, Natsuki starts helping."
    "It isn't long before we're done, and I hoist the box onto the shelf where Natsuki wanted to put it."
    "Then, I get on the stool and quickly finish moving the rest of her books from the top shelf."
    mc "Alright--!"
    mc "That should do it."
    "I hop off the stool."
    "Natsuki averts her gaze."
    show natsuki 5u at t11
    n "T-Thanks..."
    mc "Ahaha..."
    mc "It's nothing."
    "Natsuki is holding the volume I set aside in her hands."
    mc "Alright, I'm ready."
    n 2n "Good."
    n "Even if you weren't, I'd make you anyway."
    n 2u "You're taking responsibility for what you said."
    n "The thing about cheering me up."
    mc "If you insist!"
    play music t8 fadeout 1
    scene bg club_day
    with wipeleft_scene
    "We sit in the same spot as last time, and I open the second volume."
    "Natsuki's mood quickly improves, laughing and pointing things out to me."
    "She's surprisingly sharp, making note of a lot of subtle repeated jokes and background elements."
    "In the end, I'm pretty impressed by how everything ties together in this manga."
    "I guess Natsuki has good taste after all."
    "After some time, Monika gets our attention as usual, and it's time to share poems again."
    show natsuki 2j zorder 2 at t11
    mc "Guess I'll be holding onto this for now."
    n "Yep!"
    n "Even you sound more enthusiastic this time."
    mc "Well, I'm starting to get into it, you know."
    n 4z "Ehehe."
    n "Told you."
    mc "Yeah, yeah..."
    show natsuki zorder 1 at thide
    hide natsuki
    "I return to my seat and slip the book into my bag."
    return

label natsuki_exclusive_3:
    $ ch5_name = "Natsuki"
    if ch4_name == "Natsuki":
        mc "Well, I did intend on spending some time with Natsuki."
        mc "We really made a connection on Sunday baking those cupcakes together."
    else:
        mc "I didn't get to spend any time with Natsuki on the weekend."
        mc "So I'm going to make it up to her by spending this time with her now."
    m 1a "Okay [player]~"
    m "Do you know where the food stalls are?"
    m "They moved it from the courtyard."
    m "But I'm sure they won't be hard to find, just follow the smell."
    mc "Thanks, I'll get on it."
    m "Have fun [player]!"
    m "Enjoy your time with Natsuki."
    play music t6say fadeout 1
    scene bg corridor
    with wipeleft_scene
    "I make my way out of the clubroom and see Sayori talking to some people."
    show sayori 4d zorder 2 at t11
    s "Hi [player]~"
    s "Where are you going?"
    mc "I was just going to see Natsuki before we do our thing."
    mc "Are you holding up okay?"
    s 4a "Yeah, just fine."
    s 4q "In fact, look at everybody who wants to see what we have planned!"
    "She points excitedly at the dozen or so people talking to each other."
    mc "Wow, that's definitely a lot more than I expected."
    s 4d "Yeah, I promised each of them two cupcakes..."
    mc "Do we even have that many?"
    show sayori 5b at s11
    s "Well..."
    s "Maybe?"
    show sayori 4j at t11
    s "Um...anyway you should go find Natsuki now, right?"
    mc "Oh, yeah. Good luck!"
    "I give her a wave before trying to find the food stalls."
    scene bg gym
    with wipeleft_scene
    "Well, the smell of food led me to the gym."
    "This is a really strange spot to be putting food stalls."
    "They must be doing it to guilt people into joining sports clubs."
    "I notice Natsuki arguing with one of the people at a stall."
    "It isn't long before Natsuki leaves frustrated."
    "I take this as my opportunity to approach her."
    show natsuki 4s at t11
    n "Hmph."
    mc "Natsuki, are you okay?"
    n 4p "[player]?!"
    n "What are you doing here?"
    mc "Well, I wanted to spend some time with you."
    n 1o "What?!"
    if ch4_name == "Natsuki":
        n 1u "..."
        n "I'm sorry about earlier..."
        n 1m "I can't even remember why I snapped at you."
        mc "I can't remember either..."
        mc "Everything is a bit hazy..."
    else:
        n 1q "You can't be serious..."
        n "Wouldn't you rather be with someone else?"
        n "But..."
        n 1n "I'm not going to stop you either way."
        mc "I am serious."
        mc "I didn't come here just to eat some food."
    mc "But anyway..."
    mc "Why are you here?"
    n 1g "Ugh..."
    n "I was just looking for something to eat..."
    n "But everyone here expects money for their food!"
    n 2e "There's no free samples or anything!"
    mc "Well, what's wrong with expecting money for their work?"
    mc "If you sold your cupcakes you could make a lot of money."
    n 1e "Oh, come on [player]."
    n "I make cupcakes for my friends."
    n "There's no way I'd sell them..."
    n 1u "{i}(He'd probably take all the money anyway...){/i}"
    mc "What? I didn't catch that last part..."
    n 1p "N-Nothing! I'm not gonna sell my cupcakes no matter what!"
    mc "Alright..."
    mc "I didn't mean to strike a nerve or anything."
    n 1u "..."
    n "It's not your fault."
    n "I just..."
    n "Well...there's no point telling you."
    n 1g "You wanted to spend time with me, right?"
    n "Well, why don't you buy me something?"
    mc "Eh?"
    "It's true I did choose to spend time with her."
    "But I didn't expect to be spending money for her..."
    mc "Well...I suppose I can spare some money."
    n 1e "Jeez, if you're going to be like that then you can just leave."
    n "I'm not going to force you spend your time with me."
    mc "..."
    mc "It's not that, it's just I've only spent money on Sayori."
    mc "It's a little weird spending it for someone else."
    mc "But you're one of my friends so I'll make an exception."
    n 1q "{i}([cPlayer_personal] thinks of me as one of [player_possessive] friends?){/i}"
    "Suddenly Natsuki's face lightens up."
    n 1d "W-Well, I am a great friend, aren't I?"
    n "Ehehe."
    mc "Well, I never said that..."
    n 1t "But it's true, right?"
    mc "If you say so..."
    mc "Anything you wanted here in particular?"
    n 1s "Umm..."
    "Natsuki reluctantly points at the food stall she was at before."
    mc "Alright, I'm on it."
    show natsuki at thide
    hide natsuki
    "From what I can tell, the stall sells all sorts of meals containing assorted fruits and vegetables."
    "They also have their own homemade desserts."
    "I decide to buy her some strawberry parfaits, not knowing what she really wanted."
    if ch4_name == "Natsuki":
        "I did notice that she had a manga called Parfait Girls though..."
    "But this was in the middle of their price range so I hope Natsuki will be satisfied."
    show natsuki 4c at t11
    n "Well, what did you get me?"
    "I show her the parfaits and she hastily takes them from me."
    n 4s "[player]..."
    mc "Sorry, I didn't know if you'd like it."
    mc "So I took a wild guess..."
    mc "But the strawberries in it reminded me of you."
    n 3u "This is..."
    n "Y-You didn't have to spend so much for me..."
    n "Now you're making me feel bad about it..."
    mc "Don't worry about it."
    mc "If it was Sayori she'd probably get me to buy everything at the stall."
    mc "So it's nice to only spend a little bit, in comparison."
    n 3t "Ahaha!"
    n "Are you serious?"
    mc "It's a bit sad to admit..."
    mc "...but I am."
    n 2c "Wow, I thought I knew a lot about our President."
    n "But there's so much stuff I clearly don't know about her, huh?"
    mc "Yeah, I've been her best friend for so long..."
    mc "And it feels like I'm learning new things about her every week."
    "Thinking back on it, didn't I learn something about her last week?"
    "What was it...?"
    "I'm pretty sure it was important..."
    n 1c "Can we go outside?"
    n "I'd like to be in some place a bit more quiet."
    "I shrug and follow her outside."
    scene n_cg4_bg
    show n_cg1_base
    with dissolve_cg
    "When Natsuki meant outside, I thought she meant at a table."
    "Instead, Natsuki decided to sit down right outside the gym."
    "She puts away the parfaits."
    mc "You aren't going to eat them now?"
    show n_cg1_exp2 at cgfade
    n "Of course not!"
    n "We have food in the Literature Club, don't we?"
    n "The cupcakes and..."
    n "Umm..."
    "There weren't actually that many cupcakes to begin with - only two trays worth."
    "Now that Sayori's giving people two each to bribe them into visiting the club..."
    "I don't think there will be any left."
    "But I play along with Natsuki, it's easier that way."
    mc "Yeah, I suppose there is..."
    hide n_cg1_exp2
    show n_cg1_exp3 at cgfade
    n "And if I ate these now, my attention wouldn't be on you."
    n "It's rude to do that, you know."
    n "E-Especially since you were the one who..."
    n "...wanted to spend time with me."
    n "[player]..."
    n "I wanted to ask you something."
    mc "And what would that be?"
    hide n_cg1_exp3
    n "Well, this may seem odd..."
    n "But do you remember my first poem?"
    mc "Uh..."
    "I try my hardest to try to remember her poem."
    "My memory fails me, so instead of lying I'm just going to be honest."
    "I figure that giving her a bad answer will probably make her feel worse."
    mc "Well, I honestly can't..."
    mc "My memory is acting up..."
    n "Hmm..."
    n "So it's not just you, huh?"
    "Natsuki scratches her head as if she is trying to remember something as well."
    show n_cg1_exp3 at cgfade
    n "But anyway, I'll remind you."
    "That went a lot better than I thought it would."
    "But what does she mean by 'not just you'?"
    n "It was about all the great things people do around you."
    n "And how disheartening it can be..."
    "Natsuki sighs."
    n "I wasn't originally planning on going to the food stalls."
    n "It was just conveniently placed."
    n "My main intention was going to the gym here."
    n "I was hoping that it wouldn't be occupied but I was wrong."
    mc "Why were you planning on going to the gym?"
    hide n_cg1_exp3
    show n_cg1_exp2 at cgfade
    n "Ah--"
    mc "I'm not going to judge you or anything!"
    mc "I was just curious."
    hide n_cg1_exp2
    show n_cg1_exp3 at cgfade
    n "I already said more than I wanted to!"
    n "But maybe I'll tell you one day..."
    "She sighs and gets up before walking back into the gym."
    "I follow behind her."
    scene bg gym
    show natsuki 2 at i11
    with dissolve_cg
    n "This place is really full today..."
    n "And even if I didn't go here intentionally..."
    n 2d "I'm glad I went here today!"
    n 2l "Ehehe..."
    "I smile at Natsuki."
    "She's so happy about some parfaits, I'm not entirely sure why."
    "But I'm not going to ruin that for her."
    "Suddenly she notices me smiling."
    n 2p "H-Hey! What's so funny?!"
    mc "I've just never seen someone so happy about some parfait before."
    n 2o "Don't be so dumb."
    n "It's not just the parfaits..."
    n 2u "You might not know but it's got some sentimental value to me..."
    if ch4_name == "Natsuki":
        mc "Well, I did notice your manga was called \"Parfait Girls\"."
        mc "I actually bought it thinking of that."
    else:
        n "I've got a manga collection and those parfaits..."
        n "Well..."
        n "Let's just say they mean a lot more than you think."
    n 2n "It's just a little sad that we didn't get to spend much time together in the last week."
    mc "Yeah..."
    mc "I mean we could always hang out after our performances are done."
    mc "The festival won't suddenly be over after we finish performing."
    n 1t "You really want to spend more time with me?"
    n "That's--"
    n 1k "Wait!"
    n "That reminds me!"
    n 1b "It's almost time to start our poetry performances!"
    mc "Oh, you're right."
    n "We should head back, right now!"
    "I nod and follow her to the clubroom."
    # Basically Copy Paste This Part For Yuri
    scene bg corridor
    show yuri 1a zorder 2 at i21
    show sayori 1a zorder 2 at i22
    with wipeleft_scene
    "Natsuki and I make our way back to the clubroom."
    "Yuri and Sayori are already waiting outside."
    show natsuki 1k zorder 2 at l31
    show yuri zorder 2 at t32
    show sayori zorder 2 at t33
    "The amount of people ready to see what we have in store hasn't changed."
    "That means Sayori didn't let them get too bored at least."
    show natsuki 1i zorder 3 at f31
    n "Sorry we're late!"
    n "We lost track of time and..."
    "Natsuki looks at me as if she's asking me to back her up."
    show natsuki zorder 2 at t31
    mc "It's my fault."
    mc "If I didn't distract her then she would have been here earlier."
    mc "I'm sorry if I caused any trouble."
    show sayori 1r zorder 3 at f33
    s "Ehehe~"
    s "It's alright you two. You're just in time!"
    s 1d "Besides, Monika isn't here yet..."
    s "But I'm sure she won't be too long, so let's head inside."
    return

label natsuki_exclusive_4:
    $ natsuki_approval += 1
    $ yuri_approval -= 1
    show natsuki 4bi zorder 2 at t11
    if ch4_name == "Natsuki":
        n "It's..."
        n "...been a while."
    else:
        n "So...this is where you live?"
    mc "Natsuki..."
    mc "Thanks for coming."
    n "I-It's fine..."
    n 2bn "It's better than being at home with..."
    n "Well, never mind."
    n 2br "Are you going to let me in or what?"
    mc "Oh, right."
    scene bg kitchen
    with wipeleft_scene
    play music t6say fadeout 1.0
    show natsuki 1bs zorder 2 at t11
    "As I make my way up the stairs to my room, Natsuki stops at the kitchen."
    "She stands there for a while before I finally decide to say something."
    mc "Are you coming upstairs?"
    n "U-Um..."
    n "Do you mind if..."
    n 1bu "...I get something to eat?"
    "That's an odd request."
    "But I have plenty of food available."
    mc "Sure, go ahead."
    "Natsuki opens up my fridge and begins rummaging through my leftover food."
    "There's a bit of everything in there, from pizza, to chicken and even sushi."
    "Before long, Natsuki pulls out two plates from the fridge."
    "It seems that she has taken the pizza and some pasta I had leftover."
    "I didn't think she'd need that much, but I'm not really judging."
    mc "I'll just wait for you upstairs."
    mc "Take all the time you need."
    n 1bq "..."
    scene bg bedroom
    with wipeleft_scene
    "I wait in my room for what feels like a good fifteen minutes."
    "I decide to go downstairs and check on her..."
    "Suddenly the door opens."
    show natsuki 4bh zorder 2 at t11
    n "Your cooking isn't bad."
    n "There's some things you still need to learn though."
    n 4bb "Like your pizza was pretty bland, it had barely any taste..."
    n 4be "Don't even get me started on your pasta."
    mc "Eh?"
    mc "I thought we were here to read a novel..."
    mc "Not insult my cooking skills."
    n 4bh "W-Well, obviously!"
    n "I was just waiting for you to finish!"
    "I was the one waiting for her, so I don't know what she's talking about."
    n 1bq "Are we going to start, or what?"
    mc "I guess..."
    "I pull out my copy of the novel from my bag."
    "She does the same with hers."
    n 1bk "Where am I going to sit?"
    n "There's only one chair in here and you're already sitting on it."
    mc "Well, I suppose I could let you have the seat."
    mc "Or you can sit on my bed."
    "I immediately regret saying that."
    n 1bo "W-What?!"
    "Natsuki's face turns bright red."
    n "No way!"
    n 1bp "I-I'd rather sit on the ground."
    "It's best if I make this as less awkward as possible."
    "So that we can actually get through the novel before tomorrow."
    mc "If that's what you want, then I'll sit with you."
    mc "That way it will be easier to read together."
    mc "Besides, my cleaning skills are pretty good so the floor is clean enough to sit on."
    "Natsuki looks around the room."
    n 4bt "Well, they're definitely better than your cooking skills."
    "She sits down with her back against the wall."
    "I follow her lead and sit next to her."
    "She pulls out a protein bar from her pocket."
    "Did she get that from my pantry?"
    n 1bs "You can read first."
    mc "Right..."
    "I open the book to the seventh chapter."
    "It's called 'Manipulation'."
    "I read it out loud unenthusiastically but at a quick pace."
    "I quickly glance at Natsuki."
    "She isn't looking at her own book."
    "In fact, hers isn't even open."
    "Instead, she's staring at me with a protein bar in her mouth."
    "After a brief silence, she finally notices me looking at her."
    n 3bo "...!"
    n "W-Why did you stop reading?"
    n 3bp "And when did you start looking at me?!"
    mc "I should be asking you that."
    mc "Your book isn't even open and you were staring directly at me..."
    n "W-Well...!"
    n 3bq "I think you're better at this than me."
    n "You know I don't read this sort of stuff..."
    n 3bs "So it's better if I listen to you..."
    n "T-That way we'll both understand the story."
    mc "Your reading in the club earlier today was good though."
    mc "I enjoyed listening to you because of the way you read."
    n 4bp "Ah...!"
    n 4bt "{i}(Wait, that was a compliment...right?){/i}"
    n 4bw "Y-Yeah! I know just because I don't read it, doesn't mean I'm not good at reading it!"
    n "If you're trying to say otherwise then you're wrong!"
    mc "But..."
    mc "I'm not--"
    n 1bl "Alright, [player]!"
    n "Just finish up your chapter already so I can start reading my part."
    "Natsuki is suddenly feeling better."
    "It's like that's the best thing she's heard all week."
    "I decide to quickly finish off the chapter."
    n 1bk "Well, that was boring."
    n "Nothing happened at all..."
    mc "Yeah..."
    mc "What's with the author mentioning all those random details too?"
    mc "Like the older daughter buying extra rope and the wife plucking her skin?"
    n 2bm "Don't forget the younger daughter eating less and less..."
    mc "Oh...I didn't notice that."
    n 2bc "It must be the writer's way of suggesting something is gonna happen."
    n "But I've got no idea..."
    mc "Maybe those minor details will become important in the future..."
    mc "Anyway, you said you were going to read..."
    n 2be "I know, let me just get in a better spot!"
    show natsuki at d11
    "Natsuki puts away the wrapper of the protein bar and moves slightly closer towards me."
    "Our shoulders are barely touching."
    n 1bd "Now, listen to a master in action."
    "Natsuki opens her book and starts looking for the latest chapter."
    "She eventually finds it and begins reading."
    "It's called '\"The End\"', but judging by the quotation marks and how much there is left of the book..."
    "It probably isn't actually the end."
    "Natsuki's reading sounds more enthusiastic this time around."
    "At least it sounds that way when you compare it to her in the club."
    "It's like she's actively trying to sound positive..."
    "...despite the chapter taking a dark turn."
    "Soon enough, she finishes reading."
    n 4by "I'm a great reader, aren't I?"
    mc "I guess..."
    mc "But don't you feel anything for what just happened?"
    mc "Some people just died!"
    n 1bs "It's not real, [player]..."
    n 1br "Anyway, that's why I decided to keep a positive tone."
    n 1bq "I didn't want you to think I was a bad reader or anything..."
    mc "Why would I think that?"
    mc "It's not like you're the writer of the book or anything."
    mc "You only read the chapter."
    mc "Still, thanks for trying..."
    n 1be "Oh come on, it wasn't that bad."
    n 1bg "Besides..."
    n "There's probably gonna be a happy ending."
    mc "What makes you think that?"
    n 1bh "I mean Sayori chose the book."
    n "I think she's the type of person who would go for a happy ending."
    mc "You're probably right..."
    mc "There's only one chapter left though..."
    mc "Do you think they'll actually end up happy?"
    n 1bm "The lumberjack and the wanderer?"
    n "I don't think so. The relationship seems kinda one-sided."
    n "And if he ever finds out what she did then it's all over, right?"
    n 1bq "As for a happy ending..."
    n "I don't know."
    mc "I guess the only way to find out is to finish the book."
    mc "Do you want me to read it or...?"
    n 1bs "How about a page each until we're done?"
    mc "That sounds kinda..."
    n "Just do it."
    "I was going to say that it would probably make the reading slower."
    "Then I realize that Natsuki probably did that intentionally."
    "The chapter is called 'The End', without the quotations."
    "I decide to start reading a bit slower than I usually do."
    "After my page ends, she starts reading."
    "She's also reading slower than before."
    "She even started asking me how to pronounce some of the words on the page..."
    "...even though she had said it before."
    "As we slowly progress through the chapter, Natsuki begins to read slower and slower."
    "It almost sounds like she's tearing up as well."
    "The book must have had a really big effect on her..."
    "We finally reach the final page of the book."
    "It's my turn to read, so I read as slow as possible."
    "But eventually, it ends."
    n "..."
    n 1br "T-Thank you..."
    n "I-I know that you didn't have to..."
    mc "It's okay..."
    mc "You don't need to say anything."
    n 1bs "So..."
    n "I guess I have to go home now..."
    n 1bq "I really wish I didn't have to..."
    mc "You can stay longer, if you want."
    mc "There's plenty of food as well."
    n 12ba "[player]..."
    show natsuki 12bf
    "Natsuki sobs."
    mc "Are you okay?"
    mc "I know the chapter was pretty sad but they ended up fine..."
    n 12bi "Y-You don't get it...do you?"
    n "It's really more than that."
    n 12bf "I don't care about if their whole family made it."
    n "I don't even care about the book."
    n "Like I said in the beginning, it's only because we all had to do it."
    n 12bh "And the Literature Club is the only--"
    n 12be "{i}Was{/i} the only place that I felt happy."
    mc "..."
    n 1bu "Now there's only one thing..."
    n "One {i}person{/i} that can make me feel like that."
    n 1bx "A-And..."
    n 1bw "Ugh..."
    n "Forget I said anything."
    mc "What do you mean by the club being the only place you felt happy?"
    mc "Does it not feel like that anymore?"
    n 1bu "N-No..."
    n "Do you remember at the start of this week..."
    n "...when I said my friendships are looking up?"
    n 1br "I was wrong."
    n "No one even cares about what I say in the club anymore."
    n 1bn "You're the only one who even listens to what I have to say."
    n "And not just at the club too, at home it's--"
    n 1bs "There's no point."
    n "You can't do anything about it and neither can I."
    n "So let's just leave it at that."
    mc "Alright...I won't pry if you don't want me to."
    mc "I guess I'll see you tomorrow for the play, right?"
    n 1bq "Yeah..."
    n "T-Thanks for letting me come over."
    mc "That's not a problem."
    mc "I like spending time with you, so I should be thanking you."
    n 1bi "..."
    n 1bm "Hey, [player]?"
    n "Um..."
    n 1bq "I'll see you tomorrow..."
    show natsuki at thide
    hide natsuki
    "As Natsuki leaves I'm left reflecting on the book."
    "What exactly did Sayori have in mind when she chose this...?"
    "I should ask her about it sometime..."
    "But I hope everything turns out okay for tomorrow."
    scene black
    with dissolve_scene_full
    return
